// openapi-ts (P0-11, ADR-0003): the typed client, TanStack Query hooks and zod
// schemas in src/api, generated from the backend's committed OpenAPI document by
// `make gen`. Never edit src/api by hand; CI regenerates it and fails on a diff.
// OPENAPI_TS_OUTPUT redirects the output (the backend's contract test compares a
// fresh run with the committed folder).
import { defineConfig } from "@hey-api/openapi-ts";

// The fetch client runtime openapi-ts copies into src/api/{client,core} is
// hey-api's own code, written without `exactOptionalPropertyTypes`; it is the
// only output rendered without a `file` (the API-specific files are), and it
// alone is left out of type checking. Everything generated from our OpenAPI
// document (types, sdk, zod, hooks) is checked under the full tsconfig.
const HEADER = "// This file is auto-generated by @hey-api/openapi-ts";

export default defineConfig({
  input: "../schemas/openapi.json",
  output: {
    path: process.env.OPENAPI_TS_OUTPUT ?? "src/api",
    // Typed loosely on purpose: the runtime copy is rendered without a file.
    header: (ctx: { file?: unknown }) =>
      ctx.file ? [HEADER] : ["// @ts-nocheck", HEADER],
    postProcess: ["prettier"],
  },
  plugins: [
    "@hey-api/client-fetch",
    "@tanstack/react-query",
    "zod",
    // Validate responses with the generated zod schemas.
    { name: "@hey-api/sdk", validator: { response: "zod" } },
  ],
});
