"""`tumnis gen`: the code is the only source of contracts (P0-11, ADR-0003).

One run writes, under the repository root:

- `schemas/<family>/v<N>/<name>.json`: every published payload model (`tumnis.core.schemas`);
- `schemas/openapi.json`: the app's OpenAPI document (what `/v1/openapi.json` serves with
  real adapters, so the test routes are left out);
- `backend/tests/contract/generated/test_schema_<family>.py`: one contract test per family,
  validating each hand-written fixture against its schema file and its model.

`frontend/src/api` is generated from `schemas/openapi.json` by openapi-ts (`make gen`).
Everything is deterministic, so CI regenerates and fails on any diff.
"""

from pathlib import Path
from typing import Final, Literal

from fastapi import FastAPI

from tumnis.core import schemas

What = Literal["schemas", "openapi", "contract-tests", "all"]
REPO_ROOT: Final = Path(__file__).resolve().parents[2]
OPENAPI_PATH: Final = f"{schemas.SCHEMAS_DIR}/openapi.json"
GENERATED_TESTS: Final = "backend/tests/contract/generated"
FIXTURES: Final = "backend/tests/contract/fixtures"
HEADER: Final = (
    "# @generated by `tumnis gen contract-tests`. Do not edit; spec-guard skips this folder."
)
# Placeholders only: create_app does no I/O, and nothing here connects.
_DSN: Final = "postgresql+psycopg://gen:gen@127.0.0.1:1/gen"


def load_all() -> None:
    """Import everything that registers a payload model: every module's api and events
    (tumnis.wiring) and every router (tumnis.app)."""
    import tumnis.app  # noqa: PLC0415
    import tumnis.wiring  # noqa: F401, PLC0415


def api_app() -> FastAPI:
    """The production app shape, built from fixed settings rather than the environment,
    so the document does not depend on who runs the generator."""
    from tumnis.app import create_app  # noqa: PLC0415
    from tumnis.settings import Settings  # noqa: PLC0415

    settings = Settings(
        database_url=_DSN,
        database_direct_url=_DSN,
        database_owner_url=None,
        dbos_system_database_url=_DSN,
        deployment_env="dev",
        tumnis_adapters="real",
        master_key_file="/nonexistent/tumnis-gen-master-key",
        metrics_token_file=None,
        tumnis_disabled_modules="",
        sentry_dsn=None,
    )
    return create_app(settings=settings)


def openapi_files() -> dict[str, str]:
    return {OPENAPI_PATH: schemas.dump_json(api_app().openapi())}


def _fixture(spec: schemas.SchemaSpec) -> str:
    return f"{FIXTURES}/{spec.family}/{spec.name}/v{spec.version}.json"


def render_contract_test(family: str, specs: list[schemas.SchemaSpec]) -> str:
    cases = "".join(
        f'    (\n        "{s.family}",\n        "{s.name}",\n        {s.version},\n'
        f'        "{_fixture(s)}",\n    ),\n'
        for s in specs
    )
    return f'''{HEADER}
"""Schema contract tests for the `{family}` family: each hand-written fixture validates against
its committed JSON Schema and parses through `parse_versioned`."""

import json
from pathlib import Path

import pytest
from jsonschema import Draft202012Validator

from tumnis.core.schemas import parse_versioned

CASES = [
{cases}]


@pytest.mark.contract
@pytest.mark.req("FR-14.7")
@pytest.mark.wp("P0-11")
@pytest.mark.parametrize(("family", "name", "version", "fixture"), CASES)
def test_fixture_matches_schema_and_model(
    family: str, name: str, version: int, fixture: str, repo_root: Path
) -> None:
    data = json.loads((repo_root / fixture).read_text())
    schema = json.loads((repo_root / f"schemas/{{family}}/v{{version}}/{{name}}.json").read_text())
    Draft202012Validator(schema).validate(data)
    assert parse_versioned(family, name, data).schema_version >= version
'''


def contract_test_files() -> dict[str, str]:
    by_family: dict[str, list[schemas.SchemaSpec]] = {}
    for spec in schemas.registry().published():
        by_family.setdefault(spec.family, []).append(spec)
    files = {f"{GENERATED_TESTS}/__init__.py": f"{HEADER}\n"}
    for family, specs in sorted(by_family.items()):
        files[f"{GENERATED_TESTS}/test_schema_{family}.py"] = render_contract_test(family, specs)
    return files


def _present_tests(root: Path) -> set[str]:
    folder = root / GENERATED_TESTS
    return {f"{GENERATED_TESTS}/{p.name}" for p in folder.glob("test_schema_*.py")}


def _parts(what: What) -> tuple[str, ...]:
    return ("schemas", "openapi", "contract-tests") if what == "all" else (what,)


def generate(out: Path, what: What = "all") -> list[Path]:
    """Write the generated files under `out` (the repository root); stale schema files
    and generated tests are removed. Returns the files written."""
    load_all()
    parts = _parts(what)
    written: list[Path] = []
    if "schemas" in parts:
        written += schemas.write_all(out)
    expected: dict[str, str] = {}
    if "openapi" in parts:
        expected |= openapi_files()
    if "contract-tests" in parts:
        tests = contract_test_files()
        for stale in _present_tests(out) - tests.keys():
            (out / stale).unlink()
        expected |= tests
    for rel, text in sorted(expected.items()):
        path = out / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        written.append(path)
    return written


def check(root: Path, what: What = "all") -> list[str]:
    """Generated files under `root` that do not match the code (missing, different or
    stale), relative to root; empty when the tree is current."""
    load_all()
    parts = _parts(what)
    differing: list[str] = []
    if "schemas" in parts:
        differing += schemas.check(root)
    if "openapi" in parts:
        differing += schemas.diff_files(root, openapi_files(), set())
    if "contract-tests" in parts:
        differing += schemas.diff_files(root, contract_test_files(), _present_tests(root))
    return sorted(differing)
