"""Deterministic load set: `generate(projects=10, tasks=2000, seed=42)` in the seed format.

Writes backend/fixtures/load/load.yaml when run as a script. The file is committed and
regenerated only when the seed format changes:

    uv run python -m fixtures.load.generate
"""

from __future__ import annotations

import random
from pathlib import Path
from typing import Any

import yaml

OUTPUT = Path(__file__).with_name("load.yaml")
STATUSES = ("backlog", "today", "in_progress", "waiting_on_human", "in_review", "done")
STATUS_WEIGHTS = (50, 10, 10, 5, 5, 20)
LABELS = ("human", "ai", "hybrid", None)
LABEL_WEIGHTS = (50, 20, 20, 10)
VERBS = ("Draft", "Review", "Send", "Fix", "Plan", "Write", "Check", "Call", "Update", "Ship")
NOUNS = ("brief", "invoice", "deck", "report", "draft", "estimate", "newsletter", "roadmap")


def _task(rng: random.Random, key: str) -> dict[str, Any]:
    label = rng.choices(LABELS, LABEL_WEIGHTS)[0]
    task: dict[str, Any] = {
        "key": key,
        "title": f"{rng.choice(VERBS)} the {rng.choice(NOUNS)} {key[-4:]}",
        "label": label,
        "status": rng.choices(STATUSES, STATUS_WEIGHTS)[0],
        "priority": rng.randint(0, 3),
    }
    if label in {"human", "hybrid"}:
        task["estimate_minutes"] = rng.choice((10, 15, 20, 30, 45, 60, 90, 120))
    if rng.random() < 0.4:  # noqa: PLR2004
        task["due"] = f"{rng.randint(-14, 30):+d}d"
    return task


def generate(*, projects: int = 10, tasks: int = 2000, seed: int = 42) -> dict[str, Any]:
    """`projects` projects holding `tasks` tasks in all (subtasks included)."""
    rng = random.Random(seed)  # noqa: S311 (test data, not security)
    per_project = [tasks // projects + (1 if i < tasks % projects else 0) for i in range(projects)]
    out_projects: list[dict[str, Any]] = []
    for p, budget in enumerate(per_project, start=1):
        remaining = budget
        counter = 0
        top: list[dict[str, Any]] = []

        def next_key(p: int = p) -> str:
            nonlocal counter
            counter += 1
            return f"t_load_{p:02d}_{counter:04d}"

        while remaining:
            task = _task(rng, next_key())
            remaining -= 1
            if remaining >= 3 and rng.random() < 0.1:  # noqa: PLR2004
                task["subtasks"] = [_task(rng, next_key()) for _ in range(rng.randint(1, 3))]
                remaining -= len(task["subtasks"])
            top.append(task)
        out_projects.append(
            {
                "key": f"p_load_{p:02d}",
                "name": f"Load project {p:02d}",
                "client": f"Client {rng.randint(1, 5)}",
                "goal": f"Carry {budget} tasks for performance tests",
                "deadline": f"+{rng.randint(7, 90)}d",
                "tasks": top,
            }
        )
    return {
        "schema_version": 1,
        "workspace": {"key": "ws_load", "name": "Load workspace", "timezone": "America/New_York"},
        "users": [
            {
                "key": "u_load",
                "email": "load@example.test",
                "password": "load-password-please-change",
                "totp_secret": "JBSWY3DPEHPK3PXP",
            }
        ],
        "projects": out_projects,
    }


def main() -> None:
    OUTPUT.write_text(
        "# Generated by fixtures/load/generate.py (seed 42); do not edit by hand.\n"
        + yaml.safe_dump(generate(), sort_keys=False, width=100)
    )


if __name__ == "__main__":
    main()
