// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AuditExportAuditCsvData,
  AuditExportAuditCsvErrors,
  AuditExportAuditCsvResponses,
  AuditListAuditData,
  AuditListAuditErrors,
  AuditListAuditResponses,
  AuthCreateKeyData,
  AuthCreateKeyErrors,
  AuthCreateKeyResponses,
  AuthListKeysData,
  AuthListKeysErrors,
  AuthListKeysResponses,
  AuthListSessionsData,
  AuthListSessionsErrors,
  AuthListSessionsResponses,
  AuthLoginData,
  AuthLoginErrors,
  AuthLoginResponses,
  AuthLogoutData,
  AuthLogoutErrors,
  AuthLogoutResponses,
  AuthRevokeKeyData,
  AuthRevokeKeyErrors,
  AuthRevokeKeyResponses,
  AuthRevokeSessionData,
  AuthRevokeSessionErrors,
  AuthRevokeSessionResponses,
  AuthRotateKeyData,
  AuthRotateKeyErrors,
  AuthRotateKeyResponses,
  AuthSetupData,
  AuthSetupErrors,
  AuthSetupResponses,
  AuthSetupTotpData,
  AuthSetupTotpErrors,
  AuthSetupTotpResponses,
  AuthSignOutOtherDevicesData,
  AuthSignOutOtherDevicesErrors,
  AuthSignOutOtherDevicesResponses,
  AuthTotpData,
  AuthTotpErrors,
  AuthTotpResponses,
  DeadLettersGetDeadLettersData,
  DeadLettersGetDeadLettersErrors,
  DeadLettersGetDeadLettersResponses,
  DeadLettersPostDiscardData,
  DeadLettersPostDiscardErrors,
  DeadLettersPostDiscardResponses,
  DeadLettersPostRetryData,
  DeadLettersPostRetryErrors,
  DeadLettersPostRetryResponses,
  HealthLiveData,
  HealthLiveResponses,
  HealthReadyData,
  HealthReadyErrors,
  HealthReadyResponses,
  ProjectsArchiveProjectData,
  ProjectsArchiveProjectErrors,
  ProjectsArchiveProjectResponses,
  ProjectsCreateProjectData,
  ProjectsCreateProjectErrors,
  ProjectsCreateProjectResponses,
  ProjectsGetProjectData,
  ProjectsGetProjectErrors,
  ProjectsGetProjectResponses,
  ProjectsListProjectsData,
  ProjectsListProjectsErrors,
  ProjectsListProjectsResponses,
  ProjectsReorderProjectData,
  ProjectsReorderProjectErrors,
  ProjectsReorderProjectResponses,
  ProjectsUnarchiveProjectData,
  ProjectsUnarchiveProjectErrors,
  ProjectsUnarchiveProjectResponses,
  ProjectsUpdateProjectData,
  ProjectsUpdateProjectErrors,
  ProjectsUpdateProjectResponses,
  SettingsGetWorkspaceSettingsData,
  SettingsGetWorkspaceSettingsErrors,
  SettingsGetWorkspaceSettingsResponses,
  SettingsPutWorkspaceSettingsData,
  SettingsPutWorkspaceSettingsErrors,
  SettingsPutWorkspaceSettingsResponses,
  UsageGetUsageData,
  UsageGetUsageErrors,
  UsageGetUsageResponses,
} from "./types.gen";
import {
  zAuditListAuditResponse,
  zAuthCreateKeyResponse,
  zAuthListKeysResponse,
  zAuthListSessionsResponse,
  zAuthLoginResponse,
  zAuthLogoutResponse,
  zAuthRevokeKeyResponse,
  zAuthRevokeSessionResponse,
  zAuthRotateKeyResponse,
  zAuthSetupResponse,
  zAuthSetupTotpResponse,
  zAuthSignOutOtherDevicesResponse,
  zAuthTotpResponse,
  zDeadLettersGetDeadLettersResponse,
  zDeadLettersPostDiscardResponse,
  zDeadLettersPostRetryResponse,
  zHealthLiveResponse,
  zProjectsArchiveProjectResponse,
  zProjectsCreateProjectResponse,
  zProjectsGetProjectResponse,
  zProjectsListProjectsResponse,
  zProjectsReorderProjectResponse,
  zProjectsUnarchiveProjectResponse,
  zProjectsUpdateProjectResponse,
  zSettingsGetWorkspaceSettingsResponse,
  zSettingsPutWorkspaceSettingsResponse,
  zUsageGetUsageResponse,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Live
 */
export const healthLive = <ThrowOnError extends boolean = false>(
  options?: Options<HealthLiveData, ThrowOnError>,
): RequestResult<HealthLiveResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<HealthLiveResponses, unknown, ThrowOnError>({
    responseValidator: async (data) =>
      await zHealthLiveResponse.parseAsync(data),
    url: "/health/live",
    ...options,
  });

/**
 * Ready
 */
export const healthReady = <ThrowOnError extends boolean = false>(
  options?: Options<HealthReadyData, ThrowOnError>,
): RequestResult<HealthReadyResponses, HealthReadyErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    HealthReadyResponses,
    HealthReadyErrors,
    ThrowOnError
  >({ url: "/health/ready", ...options });

/**
 * List Audit
 *
 * The workspace's audit log, newest first.
 */
export const auditListAudit = <ThrowOnError extends boolean = false>(
  options?: Options<AuditListAuditData, ThrowOnError>,
): RequestResult<AuditListAuditResponses, AuditListAuditErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    AuditListAuditResponses,
    AuditListAuditErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuditListAuditResponse.parseAsync(data),
    url: "/v1/audit",
    ...options,
  });

/**
 * Export Audit Csv
 *
 * The workspace's audit log as CSV, newest first; the export is audited.
 */
export const auditExportAuditCsv = <ThrowOnError extends boolean = false>(
  options?: Options<AuditExportAuditCsvData, ThrowOnError>,
): RequestResult<
  AuditExportAuditCsvResponses,
  AuditExportAuditCsvErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AuditExportAuditCsvResponses,
    AuditExportAuditCsvErrors,
    ThrowOnError
  >({ url: "/v1/audit.csv", ...options });

/**
 * Login
 *
 * The password step: answers `{"step": "totp", "preauth": ...}` and sets no cookie.
 */
export const authLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthLoginData, ThrowOnError>,
): RequestResult<AuthLoginResponses, AuthLoginErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthLoginResponses,
    AuthLoginErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthLoginResponse.parseAsync(data),
    url: "/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Logout
 *
 * Ends this session and clears its cookies.
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthLogoutData, ThrowOnError>,
): RequestResult<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    AuthLogoutResponses,
    AuthLogoutErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthLogoutResponse.parseAsync(data),
    url: "/v1/auth/logout",
    ...options,
  });

/**
 * Sign Out Other Devices
 *
 * Revokes every session of this user but the calling one (R-21).
 */
export const authSignOutOtherDevices = <ThrowOnError extends boolean = false>(
  options?: Options<AuthSignOutOtherDevicesData, ThrowOnError>,
): RequestResult<
  AuthSignOutOtherDevicesResponses,
  AuthSignOutOtherDevicesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    AuthSignOutOtherDevicesResponses,
    AuthSignOutOtherDevicesErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthSignOutOtherDevicesResponse.parseAsync(data),
    url: "/v1/auth/sessions",
    ...options,
  });

/**
 * List Sessions
 *
 * This user's signed-in devices, newest first, the calling one `current`.
 */
export const authListSessions = <ThrowOnError extends boolean = false>(
  options?: Options<AuthListSessionsData, ThrowOnError>,
): RequestResult<
  AuthListSessionsResponses,
  AuthListSessionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AuthListSessionsResponses,
    AuthListSessionsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthListSessionsResponse.parseAsync(data),
    url: "/v1/auth/sessions",
    ...options,
  });

/**
 * Revoke Session
 *
 * Revokes one of this user's sessions.
 */
export const authRevokeSession = <ThrowOnError extends boolean = false>(
  options: Options<AuthRevokeSessionData, ThrowOnError>,
): RequestResult<
  AuthRevokeSessionResponses,
  AuthRevokeSessionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    AuthRevokeSessionResponses,
    AuthRevokeSessionErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthRevokeSessionResponse.parseAsync(data),
    url: "/v1/auth/sessions/{session_id}",
    ...options,
  });

/**
 * Totp
 *
 * The TOTP step: sets the session and CSRF cookies.
 */
export const authTotp = <ThrowOnError extends boolean = false>(
  options: Options<AuthTotpData, ThrowOnError>,
): RequestResult<AuthTotpResponses, AuthTotpErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthTotpResponses,
    AuthTotpErrors,
    ThrowOnError
  >({
    responseValidator: async (data) => await zAuthTotpResponse.parseAsync(data),
    url: "/v1/auth/totp",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Dead Letters
 */
export const deadLettersGetDeadLetters = <ThrowOnError extends boolean = false>(
  options?: Options<DeadLettersGetDeadLettersData, ThrowOnError>,
): RequestResult<
  DeadLettersGetDeadLettersResponses,
  DeadLettersGetDeadLettersErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    DeadLettersGetDeadLettersResponses,
    DeadLettersGetDeadLettersErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zDeadLettersGetDeadLettersResponse.parseAsync(data),
    url: "/v1/dead-letters",
    ...options,
  });

/**
 * Post Discard
 */
export const deadLettersPostDiscard = <ThrowOnError extends boolean = false>(
  options: Options<DeadLettersPostDiscardData, ThrowOnError>,
): RequestResult<
  DeadLettersPostDiscardResponses,
  DeadLettersPostDiscardErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    DeadLettersPostDiscardResponses,
    DeadLettersPostDiscardErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zDeadLettersPostDiscardResponse.parseAsync(data),
    url: "/v1/dead-letters/{dead_letter_id}/discard",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Post Retry
 */
export const deadLettersPostRetry = <ThrowOnError extends boolean = false>(
  options: Options<DeadLettersPostRetryData, ThrowOnError>,
): RequestResult<
  DeadLettersPostRetryResponses,
  DeadLettersPostRetryErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    DeadLettersPostRetryResponses,
    DeadLettersPostRetryErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zDeadLettersPostRetryResponse.parseAsync(data),
    url: "/v1/dead-letters/{dead_letter_id}/retry",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Keys
 *
 * The workspace's API keys: name, prefix, scopes, projects, created, expires, last
 * used, revoked; never the secret.
 */
export const authListKeys = <ThrowOnError extends boolean = false>(
  options?: Options<AuthListKeysData, ThrowOnError>,
): RequestResult<AuthListKeysResponses, AuthListKeysErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    AuthListKeysResponses,
    AuthListKeysErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthListKeysResponse.parseAsync(data),
    url: "/v1/keys",
    ...options,
  });

/**
 * Create Key
 *
 * A new key; the response shows `key` once. 422 `unknown_scope`.
 */
export const authCreateKey = <ThrowOnError extends boolean = false>(
  options: Options<AuthCreateKeyData, ThrowOnError>,
): RequestResult<AuthCreateKeyResponses, AuthCreateKeyErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthCreateKeyResponses,
    AuthCreateKeyErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthCreateKeyResponse.parseAsync(data),
    url: "/v1/keys",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Revoke Key
 *
 * Revokes the key: every process refuses it within a second.
 */
export const authRevokeKey = <ThrowOnError extends boolean = false>(
  options: Options<AuthRevokeKeyData, ThrowOnError>,
): RequestResult<AuthRevokeKeyResponses, AuthRevokeKeyErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    AuthRevokeKeyResponses,
    AuthRevokeKeyErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthRevokeKeyResponse.parseAsync(data),
    url: "/v1/keys/{id}",
    ...options,
  });

/**
 * Rotate Key
 *
 * A new secret on the same key, shown once; the old one stops at once or after
 * `grace_minutes` (0 to 1,440). 409 `key_revoked`.
 */
export const authRotateKey = <ThrowOnError extends boolean = false>(
  options: Options<AuthRotateKeyData, ThrowOnError>,
): RequestResult<AuthRotateKeyResponses, AuthRotateKeyErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthRotateKeyResponses,
    AuthRotateKeyErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthRotateKeyResponse.parseAsync(data),
    url: "/v1/keys/{id}/rotate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Projects
 *
 * Projects in board order; archived ones with `include_archived=true`.
 */
export const projectsListProjects = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectsListProjectsData, ThrowOnError>,
): RequestResult<
  ProjectsListProjectsResponses,
  ProjectsListProjectsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ProjectsListProjectsResponses,
    ProjectsListProjectsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsListProjectsResponse.parseAsync(data),
    url: "/v1/projects",
    ...options,
  });

/**
 * Create Project
 */
export const projectsCreateProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsCreateProjectData, ThrowOnError>,
): RequestResult<
  ProjectsCreateProjectResponses,
  ProjectsCreateProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectsCreateProjectResponses,
    ProjectsCreateProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsCreateProjectResponse.parseAsync(data),
    url: "/v1/projects",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Project
 */
export const projectsGetProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsGetProjectData, ThrowOnError>,
): RequestResult<
  ProjectsGetProjectResponses,
  ProjectsGetProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectsGetProjectResponses,
    ProjectsGetProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsGetProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}",
    ...options,
  });

/**
 * Update Project
 */
export const projectsUpdateProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsUpdateProjectData, ThrowOnError>,
): RequestResult<
  ProjectsUpdateProjectResponses,
  ProjectsUpdateProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    ProjectsUpdateProjectResponses,
    ProjectsUpdateProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsUpdateProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Archive Project
 */
export const projectsArchiveProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsArchiveProjectData, ThrowOnError>,
): RequestResult<
  ProjectsArchiveProjectResponses,
  ProjectsArchiveProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectsArchiveProjectResponses,
    ProjectsArchiveProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsArchiveProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/archive",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reorder Project
 *
 * Moves the project between two neighbours (either may be null: an open end).
 */
export const projectsReorderProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsReorderProjectData, ThrowOnError>,
): RequestResult<
  ProjectsReorderProjectResponses,
  ProjectsReorderProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectsReorderProjectResponses,
    ProjectsReorderProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsReorderProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/reorder",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Unarchive Project
 */
export const projectsUnarchiveProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsUnarchiveProjectData, ThrowOnError>,
): RequestResult<
  ProjectsUnarchiveProjectResponses,
  ProjectsUnarchiveProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectsUnarchiveProjectResponses,
    ProjectsUnarchiveProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsUnarchiveProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/unarchive",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Workspace Settings
 */
export const settingsGetWorkspaceSettings = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SettingsGetWorkspaceSettingsData, ThrowOnError>,
): RequestResult<
  SettingsGetWorkspaceSettingsResponses,
  SettingsGetWorkspaceSettingsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    SettingsGetWorkspaceSettingsResponses,
    SettingsGetWorkspaceSettingsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsGetWorkspaceSettingsResponse.parseAsync(data),
    url: "/v1/settings/workspace",
    ...options,
  });

/**
 * Put Workspace Settings
 */
export const settingsPutWorkspaceSettings = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SettingsPutWorkspaceSettingsData, ThrowOnError>,
): RequestResult<
  SettingsPutWorkspaceSettingsResponses,
  SettingsPutWorkspaceSettingsErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    SettingsPutWorkspaceSettingsResponses,
    SettingsPutWorkspaceSettingsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsPutWorkspaceSettingsResponse.parseAsync(data),
    url: "/v1/settings/workspace",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Setup
 *
 * First run: creates the workspace and its owner and shows the TOTP secret once.
 * 409 `already_set_up`; 403 `signup_disabled` in hosted mode.
 */
export const authSetup = <ThrowOnError extends boolean = false>(
  options: Options<AuthSetupData, ThrowOnError>,
): RequestResult<AuthSetupResponses, AuthSetupErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthSetupResponses,
    AuthSetupErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthSetupResponse.parseAsync(data),
    url: "/v1/setup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Setup Totp
 *
 * Confirms the first code; completes setup and signs the owner in.
 */
export const authSetupTotp = <ThrowOnError extends boolean = false>(
  options: Options<AuthSetupTotpData, ThrowOnError>,
): RequestResult<AuthSetupTotpResponses, AuthSetupTotpErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthSetupTotpResponses,
    AuthSetupTotpErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthSetupTotpResponse.parseAsync(data),
    url: "/v1/setup/totp",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Usage
 */
export const usageGetUsage = <ThrowOnError extends boolean = false>(
  options: Options<UsageGetUsageData, ThrowOnError>,
): RequestResult<UsageGetUsageResponses, UsageGetUsageErrors, ThrowOnError> =>
  (options.client ?? client).get<
    UsageGetUsageResponses,
    UsageGetUsageErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zUsageGetUsageResponse.parseAsync(data),
    url: "/v1/usage",
    ...options,
  });
