// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AgentsCancelRunData,
  AgentsCancelRunErrors,
  AgentsCancelRunResponses,
  AgentsCheckProfileHealthData,
  AgentsCheckProfileHealthErrors,
  AgentsCheckProfileHealthResponses,
  AgentsCreateRunnerData,
  AgentsCreateRunnerErrors,
  AgentsCreateRunnerResponses,
  AgentsGetProfileToolsData,
  AgentsGetProfileToolsErrors,
  AgentsGetProfileToolsResponses,
  AgentsGetRunData,
  AgentsGetRunErrors,
  AgentsGetRunResponses,
  AgentsGetTaskPacketData,
  AgentsGetTaskPacketErrors,
  AgentsGetTaskPacketResponses,
  AgentsListProfilesData,
  AgentsListProfilesErrors,
  AgentsListProfilesResponses,
  AgentsListRunEventsData,
  AgentsListRunEventsErrors,
  AgentsListRunEventsResponses,
  AgentsListRunnersData,
  AgentsListRunnersErrors,
  AgentsListRunnersResponses,
  AgentsPostResultData,
  AgentsPostResultErrors,
  AgentsPostResultResponses,
  AgentsRegisterProfileData,
  AgentsRegisterProfileErrors,
  AgentsRegisterProfileResponses,
  AgentsRequestRunData,
  AgentsRequestRunErrors,
  AgentsRequestRunResponses,
  AgentsRotateRunnerTokenData,
  AgentsRotateRunnerTokenErrors,
  AgentsRotateRunnerTokenResponses,
  AgentsUpdateProfileData,
  AgentsUpdateProfileErrors,
  AgentsUpdateProfileResponses,
  AuditExportAuditCsvData,
  AuditExportAuditCsvErrors,
  AuditExportAuditCsvResponses,
  AuditListAuditData,
  AuditListAuditErrors,
  AuditListAuditResponses,
  AuthConfirmTotpEnrolmentData,
  AuthConfirmTotpEnrolmentErrors,
  AuthConfirmTotpEnrolmentResponses,
  AuthCreateKeyData,
  AuthCreateKeyErrors,
  AuthCreateKeyResponses,
  AuthGetAccountData,
  AuthGetAccountErrors,
  AuthGetAccountResponses,
  AuthListKeysData,
  AuthListKeysErrors,
  AuthListKeysResponses,
  AuthListSessionsData,
  AuthListSessionsErrors,
  AuthListSessionsResponses,
  AuthLoginData,
  AuthLoginErrors,
  AuthLoginResponses,
  AuthLogoutData,
  AuthLogoutErrors,
  AuthLogoutResponses,
  AuthRevokeKeyData,
  AuthRevokeKeyErrors,
  AuthRevokeKeyResponses,
  AuthRevokeSessionData,
  AuthRevokeSessionErrors,
  AuthRevokeSessionResponses,
  AuthRotateKeyData,
  AuthRotateKeyErrors,
  AuthRotateKeyResponses,
  AuthSetupData,
  AuthSetupErrors,
  AuthSetupResponses,
  AuthSetupTotpData,
  AuthSetupTotpErrors,
  AuthSetupTotpResponses,
  AuthSignOutOtherDevicesData,
  AuthSignOutOtherDevicesErrors,
  AuthSignOutOtherDevicesResponses,
  AuthStartTotpEnrolmentData,
  AuthStartTotpEnrolmentErrors,
  AuthStartTotpEnrolmentResponses,
  AuthTotpData,
  AuthTotpErrors,
  AuthTotpResponses,
  CalendarListAccountsData,
  CalendarListAccountsErrors,
  CalendarListAccountsResponses,
  CalendarOauthCallbackData,
  CalendarOauthCallbackErrors,
  CalendarOauthStartData,
  CalendarOauthStartErrors,
  CalendarOauthStartResponses,
  CalendarSelectCalendarsData,
  CalendarSelectCalendarsErrors,
  CalendarSelectCalendarsResponses,
  CalendarSyncNowData,
  CalendarSyncNowErrors,
  CalendarSyncNowResponses,
  CoolifyListDeployStatusData,
  CoolifyListDeployStatusErrors,
  CoolifyListDeployStatusResponses,
  DeadLettersGetDeadLettersData,
  DeadLettersGetDeadLettersErrors,
  DeadLettersGetDeadLettersResponses,
  DeadLettersPostDiscardData,
  DeadLettersPostDiscardErrors,
  DeadLettersPostDiscardResponses,
  DeadLettersPostRetryData,
  DeadLettersPostRetryErrors,
  DeadLettersPostRetryResponses,
  DecisionsEditThresholdData,
  DecisionsEditThresholdErrors,
  DecisionsEditThresholdResponses,
  DecisionsGetCalibrationData,
  DecisionsGetCalibrationErrors,
  DecisionsGetCalibrationResponses,
  GithubWebhookData,
  GithubWebhookErrors,
  GithubWebhookResponses,
  HealthLiveData,
  HealthLiveResponses,
  HealthReadyData,
  HealthReadyErrors,
  HealthReadyResponses,
  KnowledgeAddLinkData,
  KnowledgeAddLinkErrors,
  KnowledgeAddLinkResponses,
  KnowledgeCreateLocationData,
  KnowledgeCreateLocationErrors,
  KnowledgeCreateLocationResponses,
  KnowledgeCreateTextEntryData,
  KnowledgeCreateTextEntryErrors,
  KnowledgeCreateTextEntryResponses,
  KnowledgeGetBriefData,
  KnowledgeGetBriefErrors,
  KnowledgeGetBriefResponses,
  KnowledgeGetDocumentData,
  KnowledgeGetDocumentErrors,
  KnowledgeGetDocumentResponses,
  KnowledgeGetFileData,
  KnowledgeGetFileErrors,
  KnowledgeGetFileResponses,
  KnowledgeGetQuotaData,
  KnowledgeGetQuotaErrors,
  KnowledgeGetQuotaResponses,
  KnowledgeListDocumentsData,
  KnowledgeListDocumentsErrors,
  KnowledgeListDocumentsResponses,
  KnowledgeListLocationsData,
  KnowledgeListLocationsErrors,
  KnowledgeListLocationsResponses,
  KnowledgeListVersionsData,
  KnowledgeListVersionsErrors,
  KnowledgeListVersionsResponses,
  KnowledgeRestoreDocumentData,
  KnowledgeRestoreDocumentErrors,
  KnowledgeRestoreDocumentResponses,
  KnowledgeSearchData,
  KnowledgeSearchErrors,
  KnowledgeSearchResponses,
  KnowledgeSetDefaultLocationData,
  KnowledgeSetDefaultLocationErrors,
  KnowledgeSetDefaultLocationResponses,
  KnowledgeSetProjectFolderData,
  KnowledgeSetProjectFolderErrors,
  KnowledgeSetProjectFolderResponses,
  KnowledgeSetTrustData,
  KnowledgeSetTrustErrors,
  KnowledgeSetTrustResponses,
  KnowledgeTestLocationData,
  KnowledgeTestLocationErrors,
  KnowledgeTestLocationResponses,
  KnowledgeTrashDocumentData,
  KnowledgeTrashDocumentErrors,
  KnowledgeTrashDocumentResponses,
  KnowledgeUpdateDocumentData,
  KnowledgeUpdateDocumentErrors,
  KnowledgeUpdateDocumentResponses,
  KnowledgeUploadDocumentData,
  KnowledgeUploadDocumentErrors,
  KnowledgeUploadDocumentResponses,
  PlanningGetDayCalendarData,
  PlanningGetDayCalendarErrors,
  PlanningGetDayCalendarResponses,
  PlanningGetProjectWeekData,
  PlanningGetProjectWeekErrors,
  PlanningGetProjectWeekResponses,
  PlanningSchedulePlanItemData,
  PlanningSchedulePlanItemErrors,
  PlanningSchedulePlanItemResponses,
  ProjectsArchiveProjectData,
  ProjectsArchiveProjectErrors,
  ProjectsArchiveProjectResponses,
  ProjectsCreateProjectData,
  ProjectsCreateProjectErrors,
  ProjectsCreateProjectResponses,
  ProjectsGetProjectContextData,
  ProjectsGetProjectContextErrors,
  ProjectsGetProjectContextResponses,
  ProjectsGetProjectData,
  ProjectsGetProjectErrors,
  ProjectsGetProjectResponses,
  ProjectsListProjectsData,
  ProjectsListProjectsErrors,
  ProjectsListProjectsResponses,
  ProjectsReorderProjectData,
  ProjectsReorderProjectErrors,
  ProjectsReorderProjectResponses,
  ProjectsUnarchiveProjectData,
  ProjectsUnarchiveProjectErrors,
  ProjectsUnarchiveProjectResponses,
  ProjectsUpdateProjectData,
  ProjectsUpdateProjectErrors,
  ProjectsUpdateProjectResponses,
  PurgesPurgeData,
  PurgesPurgeErrors,
  PurgesPurgeResponses,
  SearchSearchData,
  SearchSearchErrors,
  SearchSearchResponses,
  SearchTypeaheadProjectsData,
  SearchTypeaheadProjectsErrors,
  SearchTypeaheadProjectsResponses,
  SearchTypeaheadTasksData,
  SearchTypeaheadTasksErrors,
  SearchTypeaheadTasksResponses,
  SettingsGetSectionData,
  SettingsGetSectionErrors,
  SettingsGetSectionResponses,
  SettingsGetWorkingHoursData,
  SettingsGetWorkingHoursErrors,
  SettingsGetWorkingHoursResponses,
  SettingsGetWorkspaceSettingsData,
  SettingsGetWorkspaceSettingsErrors,
  SettingsGetWorkspaceSettingsResponses,
  SettingsListModulesData,
  SettingsListModulesErrors,
  SettingsListModulesResponses,
  SettingsPutSectionData,
  SettingsPutSectionErrors,
  SettingsPutSectionResponses,
  SettingsPutWorkingHoursData,
  SettingsPutWorkingHoursErrors,
  SettingsPutWorkingHoursResponses,
  SettingsPutWorkspaceSettingsData,
  SettingsPutWorkspaceSettingsErrors,
  SettingsPutWorkspaceSettingsResponses,
  SettingsSetModuleData,
  SettingsSetModuleErrors,
  SettingsSetModuleResponses,
  TasksAddCommentData,
  TasksAddCommentErrors,
  TasksAddCommentResponses,
  TasksChangeStatusData,
  TasksChangeStatusErrors,
  TasksChangeStatusResponses,
  TasksCreateTaskData,
  TasksCreateTaskErrors,
  TasksCreateTaskResponses,
  TasksDecideReviewData,
  TasksDecideReviewErrors,
  TasksDecideReviewResponses,
  TasksDeleteRecurrenceData,
  TasksDeleteRecurrenceErrors,
  TasksDeleteRecurrenceResponses,
  TasksGetBoardData,
  TasksGetBoardErrors,
  TasksGetBoardResponses,
  TasksGetColumnsData,
  TasksGetColumnsErrors,
  TasksGetColumnsResponses,
  TasksGetRecurrenceData,
  TasksGetRecurrenceErrors,
  TasksGetRecurrenceResponses,
  TasksGetReviewCountData,
  TasksGetReviewCountErrors,
  TasksGetReviewCountResponses,
  TasksGetTaskData,
  TasksGetTaskErrors,
  TasksGetTaskResponses,
  TasksLinkContextItemData,
  TasksLinkContextItemErrors,
  TasksLinkContextItemResponses,
  TasksLinkPullRequestData,
  TasksLinkPullRequestErrors,
  TasksLinkPullRequestResponses,
  TasksListCommentsData,
  TasksListCommentsErrors,
  TasksListCommentsResponses,
  TasksListPullRequestsData,
  TasksListPullRequestsErrors,
  TasksListPullRequestsResponses,
  TasksListRecurrenceData,
  TasksListRecurrenceErrors,
  TasksListRecurrenceResponses,
  TasksListReviewData,
  TasksListReviewErrors,
  TasksListReviewKindsData,
  TasksListReviewKindsErrors,
  TasksListReviewKindsResponses,
  TasksListReviewResponses,
  TasksListTasksData,
  TasksListTasksErrors,
  TasksListTasksResponses,
  TasksMoveTaskData,
  TasksMoveTaskErrors,
  TasksMoveTaskResponses,
  TasksPutColumnsData,
  TasksPutColumnsErrors,
  TasksPutColumnsResponses,
  TasksPutRecurrenceData,
  TasksPutRecurrenceErrors,
  TasksPutRecurrenceResponses,
  TasksTrashTaskData,
  TasksTrashTaskErrors,
  TasksTrashTaskResponses,
  TasksUndoTaskData,
  TasksUndoTaskErrors,
  TasksUndoTaskResponses,
  TasksUpdateEstimateData,
  TasksUpdateEstimateErrors,
  TasksUpdateEstimateResponses,
  TasksUpdateTaskData,
  TasksUpdateTaskErrors,
  TasksUpdateTaskResponses,
  UsageGetUsageData,
  UsageGetUsageErrors,
  UsageGetUsageResponses,
} from "./types.gen";
import {
  zAgentsCancelRunResponse,
  zAgentsCheckProfileHealthResponse,
  zAgentsCreateRunnerResponse,
  zAgentsGetProfileToolsResponse,
  zAgentsGetRunResponse,
  zAgentsGetTaskPacketResponse,
  zAgentsListProfilesResponse,
  zAgentsListRunEventsResponse,
  zAgentsListRunnersResponse,
  zAgentsPostResultResponse,
  zAgentsRegisterProfileResponse,
  zAgentsRequestRunResponse,
  zAgentsRotateRunnerTokenResponse,
  zAgentsUpdateProfileResponse,
  zAuditListAuditResponse,
  zAuthConfirmTotpEnrolmentResponse,
  zAuthCreateKeyResponse,
  zAuthGetAccountResponse,
  zAuthListKeysResponse,
  zAuthListSessionsResponse,
  zAuthLoginResponse,
  zAuthLogoutResponse,
  zAuthRevokeKeyResponse,
  zAuthRevokeSessionResponse,
  zAuthRotateKeyResponse,
  zAuthSetupResponse,
  zAuthSetupTotpResponse,
  zAuthSignOutOtherDevicesResponse,
  zAuthStartTotpEnrolmentResponse,
  zAuthTotpResponse,
  zCalendarListAccountsResponse,
  zCalendarOauthStartResponse,
  zCalendarSelectCalendarsResponse,
  zCalendarSyncNowResponse,
  zCoolifyListDeployStatusResponse,
  zDeadLettersGetDeadLettersResponse,
  zDeadLettersPostDiscardResponse,
  zDeadLettersPostRetryResponse,
  zDecisionsEditThresholdResponse,
  zDecisionsGetCalibrationResponse,
  zGithubWebhookResponse,
  zHealthLiveResponse,
  zKnowledgeAddLinkResponse,
  zKnowledgeCreateLocationResponse,
  zKnowledgeCreateTextEntryResponse,
  zKnowledgeGetBriefResponse,
  zKnowledgeGetDocumentResponse,
  zKnowledgeGetFileResponse,
  zKnowledgeGetQuotaResponse,
  zKnowledgeListDocumentsResponse,
  zKnowledgeListLocationsResponse,
  zKnowledgeListVersionsResponse,
  zKnowledgeRestoreDocumentResponse,
  zKnowledgeSearchResponse,
  zKnowledgeSetDefaultLocationResponse,
  zKnowledgeSetProjectFolderResponse,
  zKnowledgeSetTrustResponse,
  zKnowledgeTestLocationResponse,
  zKnowledgeTrashDocumentResponse,
  zKnowledgeUpdateDocumentResponse,
  zKnowledgeUploadDocumentResponse,
  zPlanningGetDayCalendarResponse,
  zPlanningGetProjectWeekResponse,
  zPlanningSchedulePlanItemResponse,
  zProjectsArchiveProjectResponse,
  zProjectsCreateProjectResponse,
  zProjectsGetProjectContextResponse,
  zProjectsGetProjectResponse,
  zProjectsListProjectsResponse,
  zProjectsReorderProjectResponse,
  zProjectsUnarchiveProjectResponse,
  zProjectsUpdateProjectResponse,
  zPurgesPurgeResponse,
  zSearchSearchResponse,
  zSearchTypeaheadProjectsResponse,
  zSearchTypeaheadTasksResponse,
  zSettingsGetSectionResponse,
  zSettingsGetWorkingHoursResponse,
  zSettingsGetWorkspaceSettingsResponse,
  zSettingsListModulesResponse,
  zSettingsPutSectionResponse,
  zSettingsPutWorkingHoursResponse,
  zSettingsPutWorkspaceSettingsResponse,
  zSettingsSetModuleResponse,
  zTasksAddCommentResponse,
  zTasksChangeStatusResponse,
  zTasksCreateTaskResponse,
  zTasksDecideReviewResponse,
  zTasksDeleteRecurrenceResponse,
  zTasksGetBoardResponse,
  zTasksGetColumnsResponse,
  zTasksGetRecurrenceResponse,
  zTasksGetReviewCountResponse,
  zTasksGetTaskResponse,
  zTasksLinkContextItemResponse,
  zTasksLinkPullRequestResponse,
  zTasksListCommentsResponse,
  zTasksListPullRequestsResponse,
  zTasksListRecurrenceResponse,
  zTasksListReviewKindsResponse,
  zTasksListReviewResponse,
  zTasksListTasksResponse,
  zTasksMoveTaskResponse,
  zTasksPutColumnsResponse,
  zTasksPutRecurrenceResponse,
  zTasksTrashTaskResponse,
  zTasksUndoTaskResponse,
  zTasksUpdateEstimateResponse,
  zTasksUpdateTaskResponse,
  zUsageGetUsageResponse,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Live
 */
export const healthLive = <ThrowOnError extends boolean = false>(
  options?: Options<HealthLiveData, ThrowOnError>,
): RequestResult<HealthLiveResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<HealthLiveResponses, unknown, ThrowOnError>({
    responseValidator: async (data) =>
      await zHealthLiveResponse.parseAsync(data),
    url: "/health/live",
    ...options,
  });

/**
 * Ready
 */
export const healthReady = <ThrowOnError extends boolean = false>(
  options?: Options<HealthReadyData, ThrowOnError>,
): RequestResult<HealthReadyResponses, HealthReadyErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    HealthReadyResponses,
    HealthReadyErrors,
    ThrowOnError
  >({ url: "/health/ready", ...options });

/**
 * List Profiles
 *
 * Agent profiles by name, with their last health check; `project_id` narrows them to
 * that project's agent (the project header, P1-06).
 */
export const agentsListProfiles = <ThrowOnError extends boolean = false>(
  options?: Options<AgentsListProfilesData, ThrowOnError>,
): RequestResult<
  AgentsListProfilesResponses,
  AgentsListProfilesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AgentsListProfilesResponses,
    AgentsListProfilesErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsListProfilesResponse.parseAsync(data),
    url: "/v1/agents/profiles",
    ...options,
  });

/**
 * Register Profile
 *
 * Register a Hermes profile. 422 `invalid_profile_name`, `invalid_profile`; 404 for
 * an unknown runner or project; 409 `master_exists`, `project_agent_exists`,
 * `profile_exists`.
 */
export const agentsRegisterProfile = <ThrowOnError extends boolean = false>(
  options: Options<AgentsRegisterProfileData, ThrowOnError>,
): RequestResult<
  AgentsRegisterProfileResponses,
  AgentsRegisterProfileErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AgentsRegisterProfileResponses,
    AgentsRegisterProfileErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsRegisterProfileResponse.parseAsync(data),
    url: "/v1/agents/profiles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update Profile
 *
 * Move a profile to another runner or endpoint, or pause it. 409 `stale_version`.
 */
export const agentsUpdateProfile = <ThrowOnError extends boolean = false>(
  options: Options<AgentsUpdateProfileData, ThrowOnError>,
): RequestResult<
  AgentsUpdateProfileResponses,
  AgentsUpdateProfileErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    AgentsUpdateProfileResponses,
    AgentsUpdateProfileErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsUpdateProfileResponse.parseAsync(data),
    url: "/v1/agents/profiles/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Check Profile Health
 *
 * Ask the profile's runner (or endpoint) for its health; the answer lands in the
 * profile's `health` (reachable, authenticated, version).
 */
export const agentsCheckProfileHealth = <ThrowOnError extends boolean = false>(
  options: Options<AgentsCheckProfileHealthData, ThrowOnError>,
): RequestResult<
  AgentsCheckProfileHealthResponses,
  AgentsCheckProfileHealthErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AgentsCheckProfileHealthResponses,
    AgentsCheckProfileHealthErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsCheckProfileHealthResponse.parseAsync(data),
    url: "/v1/agents/profiles/{id}/health-check",
    ...options,
  });

/**
 * Get Profile Tools
 *
 * The profile's MCP servers from its last health check, read-only (FR-5.12): each
 * matched against its project's allowlist, and its GitHub and Coolify tokens' reach.
 */
export const agentsGetProfileTools = <ThrowOnError extends boolean = false>(
  options: Options<AgentsGetProfileToolsData, ThrowOnError>,
): RequestResult<
  AgentsGetProfileToolsResponses,
  AgentsGetProfileToolsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    AgentsGetProfileToolsResponses,
    AgentsGetProfileToolsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsGetProfileToolsResponse.parseAsync(data),
    url: "/v1/agents/profiles/{id}/tools",
    ...options,
  });

/**
 * List Audit
 *
 * The workspace's audit log, newest first.
 */
export const auditListAudit = <ThrowOnError extends boolean = false>(
  options?: Options<AuditListAuditData, ThrowOnError>,
): RequestResult<AuditListAuditResponses, AuditListAuditErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    AuditListAuditResponses,
    AuditListAuditErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuditListAuditResponse.parseAsync(data),
    url: "/v1/audit",
    ...options,
  });

/**
 * Export Audit Csv
 *
 * The workspace's audit log as CSV, newest first; the export is audited.
 */
export const auditExportAuditCsv = <ThrowOnError extends boolean = false>(
  options?: Options<AuditExportAuditCsvData, ThrowOnError>,
): RequestResult<
  AuditExportAuditCsvResponses,
  AuditExportAuditCsvErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AuditExportAuditCsvResponses,
    AuditExportAuditCsvErrors,
    ThrowOnError
  >({ url: "/v1/audit.csv", ...options });

/**
 * Get Account
 *
 * The signed-in user's email and second factor.
 */
export const authGetAccount = <ThrowOnError extends boolean = false>(
  options?: Options<AuthGetAccountData, ThrowOnError>,
): RequestResult<AuthGetAccountResponses, AuthGetAccountErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    AuthGetAccountResponses,
    AuthGetAccountErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthGetAccountResponse.parseAsync(data),
    url: "/v1/auth/account",
    ...options,
  });

/**
 * Login
 *
 * The password step: answers `{"step": "totp", "preauth": ...}` and sets no cookie.
 */
export const authLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthLoginData, ThrowOnError>,
): RequestResult<AuthLoginResponses, AuthLoginErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthLoginResponses,
    AuthLoginErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthLoginResponse.parseAsync(data),
    url: "/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Logout
 *
 * Ends this session and clears its cookies.
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthLogoutData, ThrowOnError>,
): RequestResult<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    AuthLogoutResponses,
    AuthLogoutErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthLogoutResponse.parseAsync(data),
    url: "/v1/auth/logout",
    ...options,
  });

/**
 * Sign Out Other Devices
 *
 * Revokes every session of this user but the calling one (R-21).
 */
export const authSignOutOtherDevices = <ThrowOnError extends boolean = false>(
  options?: Options<AuthSignOutOtherDevicesData, ThrowOnError>,
): RequestResult<
  AuthSignOutOtherDevicesResponses,
  AuthSignOutOtherDevicesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    AuthSignOutOtherDevicesResponses,
    AuthSignOutOtherDevicesErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthSignOutOtherDevicesResponse.parseAsync(data),
    url: "/v1/auth/sessions",
    ...options,
  });

/**
 * List Sessions
 *
 * This user's signed-in devices, newest first, the calling one `current`.
 */
export const authListSessions = <ThrowOnError extends boolean = false>(
  options?: Options<AuthListSessionsData, ThrowOnError>,
): RequestResult<
  AuthListSessionsResponses,
  AuthListSessionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AuthListSessionsResponses,
    AuthListSessionsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthListSessionsResponse.parseAsync(data),
    url: "/v1/auth/sessions",
    ...options,
  });

/**
 * Revoke Session
 *
 * Revokes one of this user's sessions.
 */
export const authRevokeSession = <ThrowOnError extends boolean = false>(
  options: Options<AuthRevokeSessionData, ThrowOnError>,
): RequestResult<
  AuthRevokeSessionResponses,
  AuthRevokeSessionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    AuthRevokeSessionResponses,
    AuthRevokeSessionErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthRevokeSessionResponse.parseAsync(data),
    url: "/v1/auth/sessions/{session_id}",
    ...options,
  });

/**
 * Totp
 *
 * The TOTP step: sets the session and CSRF cookies.
 */
export const authTotp = <ThrowOnError extends boolean = false>(
  options: Options<AuthTotpData, ThrowOnError>,
): RequestResult<AuthTotpResponses, AuthTotpErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthTotpResponses,
    AuthTotpErrors,
    ThrowOnError
  >({
    responseValidator: async (data) => await zAuthTotpResponse.parseAsync(data),
    url: "/v1/auth/totp",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Start Totp Enrolment
 *
 * With the password: a new TOTP secret (shown once) and its enrolment token. 401
 * `invalid_credentials`, 429 `locked_out`.
 */
export const authStartTotpEnrolment = <ThrowOnError extends boolean = false>(
  options: Options<AuthStartTotpEnrolmentData, ThrowOnError>,
): RequestResult<
  AuthStartTotpEnrolmentResponses,
  AuthStartTotpEnrolmentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthStartTotpEnrolmentResponses,
    AuthStartTotpEnrolmentErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthStartTotpEnrolmentResponse.parseAsync(data),
    url: "/v1/auth/totp/enrol",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Confirm Totp Enrolment
 *
 * A code from the new secret replaces the old one. 401 `invalid_code`,
 * `invalid_enrol_token`.
 */
export const authConfirmTotpEnrolment = <ThrowOnError extends boolean = false>(
  options: Options<AuthConfirmTotpEnrolmentData, ThrowOnError>,
): RequestResult<
  AuthConfirmTotpEnrolmentResponses,
  AuthConfirmTotpEnrolmentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthConfirmTotpEnrolmentResponses,
    AuthConfirmTotpEnrolmentErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthConfirmTotpEnrolmentResponse.parseAsync(data),
    url: "/v1/auth/totp/enrol/confirm",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Accounts
 */
export const calendarListAccounts = <ThrowOnError extends boolean = false>(
  options?: Options<CalendarListAccountsData, ThrowOnError>,
): RequestResult<
  CalendarListAccountsResponses,
  CalendarListAccountsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    CalendarListAccountsResponses,
    CalendarListAccountsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zCalendarListAccountsResponse.parseAsync(data),
    url: "/v1/calendar/accounts",
    ...options,
  });

/**
 * Select Calendars
 */
export const calendarSelectCalendars = <ThrowOnError extends boolean = false>(
  options: Options<CalendarSelectCalendarsData, ThrowOnError>,
): RequestResult<
  CalendarSelectCalendarsResponses,
  CalendarSelectCalendarsErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    CalendarSelectCalendarsResponses,
    CalendarSelectCalendarsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zCalendarSelectCalendarsResponse.parseAsync(data),
    url: "/v1/calendar/accounts/{calendar_account_id}/calendars",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Sync Now
 */
export const calendarSyncNow = <ThrowOnError extends boolean = false>(
  options: Options<CalendarSyncNowData, ThrowOnError>,
): RequestResult<
  CalendarSyncNowResponses,
  CalendarSyncNowErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CalendarSyncNowResponses,
    CalendarSyncNowErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zCalendarSyncNowResponse.parseAsync(data),
    url: "/v1/calendar/accounts/{calendar_account_id}/sync",
    ...options,
  });

/**
 * Oauth Callback
 */
export const calendarOauthCallback = <ThrowOnError extends boolean = false>(
  options: Options<CalendarOauthCallbackData, ThrowOnError>,
): RequestResult<unknown, CalendarOauthCallbackErrors, ThrowOnError> =>
  (options.client ?? client).get<
    unknown,
    CalendarOauthCallbackErrors,
    ThrowOnError
  >({ url: "/v1/calendar/oauth/callback", ...options });

/**
 * Oauth Start
 */
export const calendarOauthStart = <ThrowOnError extends boolean = false>(
  options?: Options<CalendarOauthStartData, ThrowOnError>,
): RequestResult<
  CalendarOauthStartResponses,
  CalendarOauthStartErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    CalendarOauthStartResponses,
    CalendarOauthStartErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zCalendarOauthStartResponse.parseAsync(data),
    url: "/v1/calendar/oauth/start",
    ...options,
  });

/**
 * List Deploy Status
 *
 * Deploy status per project in board order; projects without apps are left out.
 */
export const coolifyListDeployStatus = <ThrowOnError extends boolean = false>(
  options?: Options<CoolifyListDeployStatusData, ThrowOnError>,
): RequestResult<
  CoolifyListDeployStatusResponses,
  CoolifyListDeployStatusErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    CoolifyListDeployStatusResponses,
    CoolifyListDeployStatusErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zCoolifyListDeployStatusResponse.parseAsync(data),
    url: "/v1/coolify/status",
    ...options,
  });

/**
 * Get Dead Letters
 */
export const deadLettersGetDeadLetters = <ThrowOnError extends boolean = false>(
  options?: Options<DeadLettersGetDeadLettersData, ThrowOnError>,
): RequestResult<
  DeadLettersGetDeadLettersResponses,
  DeadLettersGetDeadLettersErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    DeadLettersGetDeadLettersResponses,
    DeadLettersGetDeadLettersErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zDeadLettersGetDeadLettersResponse.parseAsync(data),
    url: "/v1/dead-letters",
    ...options,
  });

/**
 * Post Discard
 */
export const deadLettersPostDiscard = <ThrowOnError extends boolean = false>(
  options: Options<DeadLettersPostDiscardData, ThrowOnError>,
): RequestResult<
  DeadLettersPostDiscardResponses,
  DeadLettersPostDiscardErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    DeadLettersPostDiscardResponses,
    DeadLettersPostDiscardErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zDeadLettersPostDiscardResponse.parseAsync(data),
    url: "/v1/dead-letters/{dead_letter_id}/discard",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Post Retry
 */
export const deadLettersPostRetry = <ThrowOnError extends boolean = false>(
  options: Options<DeadLettersPostRetryData, ThrowOnError>,
): RequestResult<
  DeadLettersPostRetryResponses,
  DeadLettersPostRetryErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    DeadLettersPostRetryResponses,
    DeadLettersPostRetryErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zDeadLettersPostRetryResponse.parseAsync(data),
    url: "/v1/dead-letters/{dead_letter_id}/retry",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Calibration
 *
 * Per decision point: the threshold in force, the recheck flag, and accuracy once 100
 * labeled outcomes exist (until then, how many more are needed).
 */
export const decisionsGetCalibration = <ThrowOnError extends boolean = false>(
  options?: Options<DecisionsGetCalibrationData, ThrowOnError>,
): RequestResult<
  DecisionsGetCalibrationResponses,
  DecisionsGetCalibrationErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    DecisionsGetCalibrationResponses,
    DecisionsGetCalibrationErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zDecisionsGetCalibrationResponse.parseAsync(data),
    url: "/v1/decisions/calibration",
    ...options,
  });

/**
 * Edit Threshold
 *
 * Set the point's threshold with a reason; it clears the recheck flag.
 */
export const decisionsEditThreshold = <ThrowOnError extends boolean = false>(
  options: Options<DecisionsEditThresholdData, ThrowOnError>,
): RequestResult<
  DecisionsEditThresholdResponses,
  DecisionsEditThresholdErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    DecisionsEditThresholdResponses,
    DecisionsEditThresholdErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zDecisionsEditThresholdResponse.parseAsync(data),
    url: "/v1/decisions/thresholds/{point}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get File
 *
 * The document's original file, always as a download (`attachment`, octet-stream,
 * `nosniff`); 409 `not_available` until the document is `ready`. `version` is a version
 * number.
 */
export const knowledgeGetFile = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeGetFileData, ThrowOnError>,
): RequestResult<
  KnowledgeGetFileResponses,
  KnowledgeGetFileErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    KnowledgeGetFileResponses,
    KnowledgeGetFileErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeGetFileResponse.parseAsync(data),
    url: "/v1/files/{document_id}",
    ...options,
  });

/**
 * Webhook
 */
export const githubWebhook = <ThrowOnError extends boolean = false>(
  options: Options<GithubWebhookData, ThrowOnError>,
): RequestResult<GithubWebhookResponses, GithubWebhookErrors, ThrowOnError> =>
  (options.client ?? client).post<
    GithubWebhookResponses,
    GithubWebhookErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zGithubWebhookResponse.parseAsync(data),
    url: "/v1/github/webhook/{workspace_id}",
    ...options,
  });

/**
 * List Keys
 *
 * The workspace's API keys: name, prefix, scopes, projects, created, expires, last
 * used, revoked; never the secret.
 */
export const authListKeys = <ThrowOnError extends boolean = false>(
  options?: Options<AuthListKeysData, ThrowOnError>,
): RequestResult<AuthListKeysResponses, AuthListKeysErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    AuthListKeysResponses,
    AuthListKeysErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthListKeysResponse.parseAsync(data),
    url: "/v1/keys",
    ...options,
  });

/**
 * Create Key
 *
 * A new key; the response shows `key` once. 422 `unknown_scope`.
 */
export const authCreateKey = <ThrowOnError extends boolean = false>(
  options: Options<AuthCreateKeyData, ThrowOnError>,
): RequestResult<AuthCreateKeyResponses, AuthCreateKeyErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthCreateKeyResponses,
    AuthCreateKeyErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthCreateKeyResponse.parseAsync(data),
    url: "/v1/keys",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Revoke Key
 *
 * Revokes the key: every process refuses it within a second.
 */
export const authRevokeKey = <ThrowOnError extends boolean = false>(
  options: Options<AuthRevokeKeyData, ThrowOnError>,
): RequestResult<AuthRevokeKeyResponses, AuthRevokeKeyErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    AuthRevokeKeyResponses,
    AuthRevokeKeyErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthRevokeKeyResponse.parseAsync(data),
    url: "/v1/keys/{id}",
    ...options,
  });

/**
 * Rotate Key
 *
 * A new secret on the same key, shown once; the old one stops at once or after
 * `grace_minutes` (0 to 1,440). 409 `key_revoked`.
 */
export const authRotateKey = <ThrowOnError extends boolean = false>(
  options: Options<AuthRotateKeyData, ThrowOnError>,
): RequestResult<AuthRotateKeyResponses, AuthRotateKeyErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthRotateKeyResponses,
    AuthRotateKeyErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthRotateKeyResponse.parseAsync(data),
    url: "/v1/keys/{id}/rotate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Documents
 *
 * A project's knowledge items (none: the workspace knowledge base's), oldest first.
 */
export const knowledgeListDocuments = <ThrowOnError extends boolean = false>(
  options?: Options<KnowledgeListDocumentsData, ThrowOnError>,
): RequestResult<
  KnowledgeListDocumentsResponses,
  KnowledgeListDocumentsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    KnowledgeListDocumentsResponses,
    KnowledgeListDocumentsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeListDocumentsResponse.parseAsync(data),
    url: "/v1/knowledge/documents",
    ...options,
  });

/**
 * Upload Document
 *
 * Upload a file (multipart: `file`, and optionally `project_id` and `title`). The
 * answer is 202 with the document in `pending_scan`: it is scanned, its type read from its
 * content and its text extracted by the extract worker. 413 `too_large` past 50 MiB.
 */
export const knowledgeUploadDocument = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeUploadDocumentData, ThrowOnError>,
): RequestResult<
  KnowledgeUploadDocumentResponses,
  KnowledgeUploadDocumentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    KnowledgeUploadDocumentResponses,
    KnowledgeUploadDocumentErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseValidator: async (data) =>
      await zKnowledgeUploadDocumentResponse.parseAsync(data),
    url: "/v1/knowledge/documents",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Add Link
 *
 * A link as a knowledge item; its content is never fetched.
 */
export const knowledgeAddLink = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeAddLinkData, ThrowOnError>,
): RequestResult<
  KnowledgeAddLinkResponses,
  KnowledgeAddLinkErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    KnowledgeAddLinkResponses,
    KnowledgeAddLinkErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeAddLinkResponse.parseAsync(data),
    url: "/v1/knowledge/documents/link",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Text Entry
 *
 * A text entry (Markdown) in a project or the workspace knowledge base: version 1,
 * searchable at once, trusted when a person writes it (FR-15.5, `_origin`); in a project
 * with a folder, also `notes/`.
 */
export const knowledgeCreateTextEntry = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeCreateTextEntryData, ThrowOnError>,
): RequestResult<
  KnowledgeCreateTextEntryResponses,
  KnowledgeCreateTextEntryErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    KnowledgeCreateTextEntryResponses,
    KnowledgeCreateTextEntryErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeCreateTextEntryResponse.parseAsync(data),
    url: "/v1/knowledge/documents/text",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Trash Document
 *
 * To the trash: hidden from lists, reads and search until restored.
 */
export const knowledgeTrashDocument = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeTrashDocumentData, ThrowOnError>,
): RequestResult<
  KnowledgeTrashDocumentResponses,
  KnowledgeTrashDocumentErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    KnowledgeTrashDocumentResponses,
    KnowledgeTrashDocumentErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeTrashDocumentResponse.parseAsync(data),
    url: "/v1/knowledge/documents/{document_id}",
    ...options,
  });

/**
 * Get Document
 *
 * A document's state (status, reason, kind, path): what the upload flow polls.
 */
export const knowledgeGetDocument = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeGetDocumentData, ThrowOnError>,
): RequestResult<
  KnowledgeGetDocumentResponses,
  KnowledgeGetDocumentErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    KnowledgeGetDocumentResponses,
    KnowledgeGetDocumentErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeGetDocumentResponse.parseAsync(data),
    url: "/v1/knowledge/documents/{document_id}",
    ...options,
  });

/**
 * Update Document
 *
 * Edit a document: a text entry's Markdown body (a new version, its note file
 * rewritten), any document's title, tags or pin. 409 `stale_version` with the current
 * document; 409 `not_text` for a body on anything but a text entry.
 */
export const knowledgeUpdateDocument = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeUpdateDocumentData, ThrowOnError>,
): RequestResult<
  KnowledgeUpdateDocumentResponses,
  KnowledgeUpdateDocumentErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    KnowledgeUpdateDocumentResponses,
    KnowledgeUpdateDocumentErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeUpdateDocumentResponse.parseAsync(data),
    url: "/v1/knowledge/documents/{document_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Restore Document
 *
 * Back from the trash; 404 for a document that is not in it.
 */
export const knowledgeRestoreDocument = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeRestoreDocumentData, ThrowOnError>,
): RequestResult<
  KnowledgeRestoreDocumentResponses,
  KnowledgeRestoreDocumentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    KnowledgeRestoreDocumentResponses,
    KnowledgeRestoreDocumentErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeRestoreDocumentResponse.parseAsync(data),
    url: "/v1/knowledge/documents/{document_id}/restore",
    ...options,
  });

/**
 * Set Trust
 *
 * A person marks the document trusted or untrusted (audited); keys and agents
 * cannot (403 `session_required`).
 */
export const knowledgeSetTrust = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeSetTrustData, ThrowOnError>,
): RequestResult<
  KnowledgeSetTrustResponses,
  KnowledgeSetTrustErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    KnowledgeSetTrustResponses,
    KnowledgeSetTrustErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeSetTrustResponse.parseAsync(data),
    url: "/v1/knowledge/documents/{document_id}/trust",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Versions
 *
 * Every kept version of a live document, oldest first, each with its body.
 */
export const knowledgeListVersions = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeListVersionsData, ThrowOnError>,
): RequestResult<
  KnowledgeListVersionsResponses,
  KnowledgeListVersionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    KnowledgeListVersionsResponses,
    KnowledgeListVersionsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeListVersionsResponse.parseAsync(data),
    url: "/v1/knowledge/documents/{document_id}/versions",
    ...options,
  });

/**
 * List Locations
 */
export const knowledgeListLocations = <ThrowOnError extends boolean = false>(
  options?: Options<KnowledgeListLocationsData, ThrowOnError>,
): RequestResult<
  KnowledgeListLocationsResponses,
  KnowledgeListLocationsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    KnowledgeListLocationsResponses,
    KnowledgeListLocationsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeListLocationsResponse.parseAsync(data),
    url: "/v1/knowledge/locations",
    ...options,
  });

/**
 * Create Location
 */
export const knowledgeCreateLocation = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeCreateLocationData, ThrowOnError>,
): RequestResult<
  KnowledgeCreateLocationResponses,
  KnowledgeCreateLocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    KnowledgeCreateLocationResponses,
    KnowledgeCreateLocationErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeCreateLocationResponse.parseAsync(data),
    url: "/v1/knowledge/locations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Set Default Location
 */
export const knowledgeSetDefaultLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<KnowledgeSetDefaultLocationData, ThrowOnError>,
): RequestResult<
  KnowledgeSetDefaultLocationResponses,
  KnowledgeSetDefaultLocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    KnowledgeSetDefaultLocationResponses,
    KnowledgeSetDefaultLocationErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeSetDefaultLocationResponse.parseAsync(data),
    url: "/v1/knowledge/locations/{storage_location_id}/default",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Test Location
 */
export const knowledgeTestLocation = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeTestLocationData, ThrowOnError>,
): RequestResult<
  KnowledgeTestLocationResponses,
  KnowledgeTestLocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    KnowledgeTestLocationResponses,
    KnowledgeTestLocationErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeTestLocationResponse.parseAsync(data),
    url: "/v1/knowledge/locations/{storage_location_id}/test",
    ...options,
  });

/**
 * Set Project Folder
 */
export const knowledgeSetProjectFolder = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeSetProjectFolderData, ThrowOnError>,
): RequestResult<
  KnowledgeSetProjectFolderResponses,
  KnowledgeSetProjectFolderErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    KnowledgeSetProjectFolderResponses,
    KnowledgeSetProjectFolderErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeSetProjectFolderResponse.parseAsync(data),
    url: "/v1/knowledge/projects/{project_id}/folder",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Quota
 *
 * The workspace's knowledge bytes against its quota, and the scope's item count.
 */
export const knowledgeGetQuota = <ThrowOnError extends boolean = false>(
  options?: Options<KnowledgeGetQuotaData, ThrowOnError>,
): RequestResult<
  KnowledgeGetQuotaResponses,
  KnowledgeGetQuotaErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    KnowledgeGetQuotaResponses,
    KnowledgeGetQuotaErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeGetQuotaResponse.parseAsync(data),
    url: "/v1/knowledge/quota",
    ...options,
  });

/**
 * Search
 *
 * Full-text search of a project's items and the workspace knowledge base (none: the
 * whole workspace), citing document, heading path and page (FR-15.3).
 */
export const knowledgeSearch = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeSearchData, ThrowOnError>,
): RequestResult<
  KnowledgeSearchResponses,
  KnowledgeSearchErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    KnowledgeSearchResponses,
    KnowledgeSearchErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeSearchResponse.parseAsync(data),
    url: "/v1/knowledge/search",
    ...options,
  });

/**
 * Get Project Week
 */
export const planningGetProjectWeek = <ThrowOnError extends boolean = false>(
  options: Options<PlanningGetProjectWeekData, ThrowOnError>,
): RequestResult<
  PlanningGetProjectWeekResponses,
  PlanningGetProjectWeekErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    PlanningGetProjectWeekResponses,
    PlanningGetProjectWeekErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zPlanningGetProjectWeekResponse.parseAsync(data),
    url: "/v1/plan/week/{monday}",
    ...options,
  });

/**
 * Get Day Calendar
 */
export const planningGetDayCalendar = <ThrowOnError extends boolean = false>(
  options: Options<PlanningGetDayCalendarData, ThrowOnError>,
): RequestResult<
  PlanningGetDayCalendarResponses,
  PlanningGetDayCalendarErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    PlanningGetDayCalendarResponses,
    PlanningGetDayCalendarErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zPlanningGetDayCalendarResponse.parseAsync(data),
    url: "/v1/plan/{day}/calendar",
    ...options,
  });

/**
 * Schedule Plan Item
 */
export const planningSchedulePlanItem = <ThrowOnError extends boolean = false>(
  options: Options<PlanningSchedulePlanItemData, ThrowOnError>,
): RequestResult<
  PlanningSchedulePlanItemResponses,
  PlanningSchedulePlanItemErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PlanningSchedulePlanItemResponses,
    PlanningSchedulePlanItemErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zPlanningSchedulePlanItemResponse.parseAsync(data),
    url: "/v1/plan/{day}/items/{task_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Projects
 *
 * Projects in board order; archived ones with `include_archived=true`.
 */
export const projectsListProjects = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectsListProjectsData, ThrowOnError>,
): RequestResult<
  ProjectsListProjectsResponses,
  ProjectsListProjectsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ProjectsListProjectsResponses,
    ProjectsListProjectsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsListProjectsResponse.parseAsync(data),
    url: "/v1/projects",
    ...options,
  });

/**
 * Create Project
 */
export const projectsCreateProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsCreateProjectData, ThrowOnError>,
): RequestResult<
  ProjectsCreateProjectResponses,
  ProjectsCreateProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectsCreateProjectResponses,
    ProjectsCreateProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsCreateProjectResponse.parseAsync(data),
    url: "/v1/projects",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Project
 */
export const projectsGetProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsGetProjectData, ThrowOnError>,
): RequestResult<
  ProjectsGetProjectResponses,
  ProjectsGetProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectsGetProjectResponses,
    ProjectsGetProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsGetProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}",
    ...options,
  });

/**
 * Update Project
 */
export const projectsUpdateProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsUpdateProjectData, ThrowOnError>,
): RequestResult<
  ProjectsUpdateProjectResponses,
  ProjectsUpdateProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    ProjectsUpdateProjectResponses,
    ProjectsUpdateProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsUpdateProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Archive Project
 */
export const projectsArchiveProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsArchiveProjectData, ThrowOnError>,
): RequestResult<
  ProjectsArchiveProjectResponses,
  ProjectsArchiveProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectsArchiveProjectResponses,
    ProjectsArchiveProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsArchiveProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/archive",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Board
 *
 * The kanban: columns, cards and each card's checklist (FR-3.4).
 */
export const tasksGetBoard = <ThrowOnError extends boolean = false>(
  options: Options<TasksGetBoardData, ThrowOnError>,
): RequestResult<TasksGetBoardResponses, TasksGetBoardErrors, ThrowOnError> =>
  (options.client ?? client).get<
    TasksGetBoardResponses,
    TasksGetBoardErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksGetBoardResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/board",
    ...options,
  });

/**
 * Get Brief
 *
 * The project's pinned brief (a text entry); 404 until the project's subscriber ran.
 */
export const knowledgeGetBrief = <ThrowOnError extends boolean = false>(
  options: Options<KnowledgeGetBriefData, ThrowOnError>,
): RequestResult<
  KnowledgeGetBriefResponses,
  KnowledgeGetBriefErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    KnowledgeGetBriefResponses,
    KnowledgeGetBriefErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zKnowledgeGetBriefResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/brief",
    ...options,
  });

/**
 * Get Columns
 */
export const tasksGetColumns = <ThrowOnError extends boolean = false>(
  options: Options<TasksGetColumnsData, ThrowOnError>,
): RequestResult<
  TasksGetColumnsResponses,
  TasksGetColumnsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    TasksGetColumnsResponses,
    TasksGetColumnsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksGetColumnsResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/columns",
    ...options,
  });

/**
 * Put Columns
 *
 * Renames, reorders, adds and removes columns in one request; every status keeps at
 * least one column (422 `status_without_column`).
 */
export const tasksPutColumns = <ThrowOnError extends boolean = false>(
  options: Options<TasksPutColumnsData, ThrowOnError>,
): RequestResult<
  TasksPutColumnsResponses,
  TasksPutColumnsErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    TasksPutColumnsResponses,
    TasksPutColumnsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksPutColumnsResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/columns",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Project Context
 *
 * The project as an agent starts work in it (brief, code location, policy); the
 * `get_project_context` tool's twin (P2-01).
 */
export const projectsGetProjectContext = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsGetProjectContextData, ThrowOnError>,
): RequestResult<
  ProjectsGetProjectContextResponses,
  ProjectsGetProjectContextErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectsGetProjectContextResponses,
    ProjectsGetProjectContextErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsGetProjectContextResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/context",
    ...options,
  });

/**
 * Reorder Project
 *
 * Moves the project between two neighbours (either may be null: an open end).
 */
export const projectsReorderProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsReorderProjectData, ThrowOnError>,
): RequestResult<
  ProjectsReorderProjectResponses,
  ProjectsReorderProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectsReorderProjectResponses,
    ProjectsReorderProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsReorderProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/reorder",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Unarchive Project
 */
export const projectsUnarchiveProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsUnarchiveProjectData, ThrowOnError>,
): RequestResult<
  ProjectsUnarchiveProjectResponses,
  ProjectsUnarchiveProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectsUnarchiveProjectResponses,
    ProjectsUnarchiveProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsUnarchiveProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/unarchive",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Purge
 */
export const purgesPurge = <ThrowOnError extends boolean = false>(
  options: Options<PurgesPurgeData, ThrowOnError>,
): RequestResult<PurgesPurgeResponses, PurgesPurgeErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PurgesPurgeResponses,
    PurgesPurgeErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zPurgesPurgeResponse.parseAsync(data),
    url: "/v1/purges",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Recurrence
 *
 * Recurrence rules, optionally of one project (the Schedule rail).
 */
export const tasksListRecurrence = <ThrowOnError extends boolean = false>(
  options?: Options<TasksListRecurrenceData, ThrowOnError>,
): RequestResult<
  TasksListRecurrenceResponses,
  TasksListRecurrenceErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    TasksListRecurrenceResponses,
    TasksListRecurrenceErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksListRecurrenceResponse.parseAsync(data),
    url: "/v1/recurrence",
    ...options,
  });

/**
 * List Review
 *
 * The review queue (FR-6.1): open, unsnoozed items by blocking impact (downstream
 * tasks and human minutes, times Jev's factor when it applied), then age; `kind` keeps
 * one registered kind.
 */
export const tasksListReview = <ThrowOnError extends boolean = false>(
  options?: Options<TasksListReviewData, ThrowOnError>,
): RequestResult<
  TasksListReviewResponses,
  TasksListReviewErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    TasksListReviewResponses,
    TasksListReviewErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksListReviewResponse.parseAsync(data),
    url: "/v1/review",
    ...options,
  });

/**
 * Get Review Count
 *
 * The badge: review items waiting now (not decided, trashed or snoozed).
 */
export const tasksGetReviewCount = <ThrowOnError extends boolean = false>(
  options?: Options<TasksGetReviewCountData, ThrowOnError>,
): RequestResult<
  TasksGetReviewCountResponses,
  TasksGetReviewCountErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    TasksGetReviewCountResponses,
    TasksGetReviewCountErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksGetReviewCountResponse.parseAsync(data),
    url: "/v1/review/count",
    ...options,
  });

/**
 * List Review Kinds
 *
 * The registered review kinds and their actions (R-03, R-05).
 */
export const tasksListReviewKinds = <ThrowOnError extends boolean = false>(
  options?: Options<TasksListReviewKindsData, ThrowOnError>,
): RequestResult<
  TasksListReviewKindsResponses,
  TasksListReviewKindsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    TasksListReviewKindsResponses,
    TasksListReviewKindsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksListReviewKindsResponse.parseAsync(data),
    url: "/v1/review/kinds",
    ...options,
  });

/**
 * Decide Review
 *
 * Decides one item (R-04): 422 `action_not_allowed` for an action its kind lacks,
 * `invalid_review_payload` or `invalid_snooze`; 409 `already_decided` or
 * `stale_version`. Emits `human.decided`; the owning module applies the effect.
 */
export const tasksDecideReview = <ThrowOnError extends boolean = false>(
  options: Options<TasksDecideReviewData, ThrowOnError>,
): RequestResult<
  TasksDecideReviewResponses,
  TasksDecideReviewErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TasksDecideReviewResponses,
    TasksDecideReviewErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksDecideReviewResponse.parseAsync(data),
    url: "/v1/review/{id}/decide",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Runners
 *
 * Runners by name, with their status judged from the last heartbeat (online after a
 * beat in the last 45 s, offline after that, never_seen before the first register).
 */
export const agentsListRunners = <ThrowOnError extends boolean = false>(
  options?: Options<AgentsListRunnersData, ThrowOnError>,
): RequestResult<
  AgentsListRunnersResponses,
  AgentsListRunnersErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AgentsListRunnersResponses,
    AgentsListRunnersErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsListRunnersResponse.parseAsync(data),
    url: "/v1/runners",
    ...options,
  });

/**
 * Create Runner
 *
 * A runner and its device token, shown once. 409 `runner_exists`.
 */
export const agentsCreateRunner = <ThrowOnError extends boolean = false>(
  options: Options<AgentsCreateRunnerData, ThrowOnError>,
): RequestResult<
  AgentsCreateRunnerResponses,
  AgentsCreateRunnerErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AgentsCreateRunnerResponses,
    AgentsCreateRunnerErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsCreateRunnerResponse.parseAsync(data),
    url: "/v1/runners",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Rotate Runner Token
 *
 * A new device token, shown once; the old one stops and the runner's socket closes.
 */
export const agentsRotateRunnerToken = <ThrowOnError extends boolean = false>(
  options: Options<AgentsRotateRunnerTokenData, ThrowOnError>,
): RequestResult<
  AgentsRotateRunnerTokenResponses,
  AgentsRotateRunnerTokenErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AgentsRotateRunnerTokenResponses,
    AgentsRotateRunnerTokenErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsRotateRunnerTokenResponse.parseAsync(data),
    url: "/v1/runners/{id}/rotate-token",
    ...options,
  });

/**
 * Get Run
 *
 * The run: its status, stop reason and times (the run view's header).
 */
export const agentsGetRun = <ThrowOnError extends boolean = false>(
  options: Options<AgentsGetRunData, ThrowOnError>,
): RequestResult<AgentsGetRunResponses, AgentsGetRunErrors, ThrowOnError> =>
  (options.client ?? client).get<
    AgentsGetRunResponses,
    AgentsGetRunErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsGetRunResponse.parseAsync(data),
    url: "/v1/runs/{run_id}",
    ...options,
  });

/**
 * Cancel Run
 *
 * Stop (FR-5.5): a queued run ends at once; a running one is stopped by its workflow
 * through the agent's adapter (the api never calls out). An ended run is left as it is.
 */
export const agentsCancelRun = <ThrowOnError extends boolean = false>(
  options: Options<AgentsCancelRunData, ThrowOnError>,
): RequestResult<
  AgentsCancelRunResponses,
  AgentsCancelRunErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AgentsCancelRunResponses,
    AgentsCancelRunErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsCancelRunResponse.parseAsync(data),
    url: "/v1/runs/{run_id}/cancel",
    ...options,
  });

/**
 * List Run Events
 *
 * The run's log and events after `after_seq`, in the order they were stored (FR-5.5);
 * the next page asks `after_seq=next_after_seq`.
 */
export const agentsListRunEvents = <ThrowOnError extends boolean = false>(
  options: Options<AgentsListRunEventsData, ThrowOnError>,
): RequestResult<
  AgentsListRunEventsResponses,
  AgentsListRunEventsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    AgentsListRunEventsResponses,
    AgentsListRunEventsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsListRunEventsResponse.parseAsync(data),
    url: "/v1/runs/{run_id}/events",
    ...options,
  });

/**
 * Post Result
 *
 * The run's result, posted with its task token; the `post_result` tool's twin. 403
 * `run_mismatch` for another run's token; 409 `run_not_active` once the run ended. A
 * second post answers the first result.
 */
export const agentsPostResult = <ThrowOnError extends boolean = false>(
  options: Options<AgentsPostResultData, ThrowOnError>,
): RequestResult<
  AgentsPostResultResponses,
  AgentsPostResultErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AgentsPostResultResponses,
    AgentsPostResultErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsPostResultResponse.parseAsync(data),
    url: "/v1/runs/{run_id}/result",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search
 *
 * Tasks and projects matching `q`, best first: text match, recency, project match.
 * The `search` tool's twin (P2-01).
 */
export const searchSearch = <ThrowOnError extends boolean = false>(
  options?: Options<SearchSearchData, ThrowOnError>,
): RequestResult<SearchSearchResponses, SearchSearchErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    SearchSearchResponses,
    SearchSearchErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSearchSearchResponse.parseAsync(data),
    url: "/v1/search",
    ...options,
  });

/**
 * List Modules
 *
 * Every module, whether it is on for this workspace, and whether it can be off.
 */
export const settingsListModules = <ThrowOnError extends boolean = false>(
  options?: Options<SettingsListModulesData, ThrowOnError>,
): RequestResult<
  SettingsListModulesResponses,
  SettingsListModulesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    SettingsListModulesResponses,
    SettingsListModulesErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsListModulesResponse.parseAsync(data),
    url: "/v1/settings/modules",
    ...options,
  });

/**
 * Set Module
 *
 * Switches the module on or off for this workspace. 422 `module_required`.
 */
export const settingsSetModule = <ThrowOnError extends boolean = false>(
  options: Options<SettingsSetModuleData, ThrowOnError>,
): RequestResult<
  SettingsSetModuleResponses,
  SettingsSetModuleErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    SettingsSetModuleResponses,
    SettingsSetModuleErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsSetModuleResponse.parseAsync(data),
    url: "/v1/settings/modules",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Working Hours
 */
export const settingsGetWorkingHours = <ThrowOnError extends boolean = false>(
  options?: Options<SettingsGetWorkingHoursData, ThrowOnError>,
): RequestResult<
  SettingsGetWorkingHoursResponses,
  SettingsGetWorkingHoursErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    SettingsGetWorkingHoursResponses,
    SettingsGetWorkingHoursErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsGetWorkingHoursResponse.parseAsync(data),
    url: "/v1/settings/working-hours",
    ...options,
  });

/**
 * Put Working Hours
 */
export const settingsPutWorkingHours = <ThrowOnError extends boolean = false>(
  options: Options<SettingsPutWorkingHoursData, ThrowOnError>,
): RequestResult<
  SettingsPutWorkingHoursResponses,
  SettingsPutWorkingHoursErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    SettingsPutWorkingHoursResponses,
    SettingsPutWorkingHoursErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsPutWorkingHoursResponse.parseAsync(data),
    url: "/v1/settings/working-hours",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Workspace Settings
 */
export const settingsGetWorkspaceSettings = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SettingsGetWorkspaceSettingsData, ThrowOnError>,
): RequestResult<
  SettingsGetWorkspaceSettingsResponses,
  SettingsGetWorkspaceSettingsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    SettingsGetWorkspaceSettingsResponses,
    SettingsGetWorkspaceSettingsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsGetWorkspaceSettingsResponse.parseAsync(data),
    url: "/v1/settings/workspace",
    ...options,
  });

/**
 * Put Workspace Settings
 */
export const settingsPutWorkspaceSettings = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SettingsPutWorkspaceSettingsData, ThrowOnError>,
): RequestResult<
  SettingsPutWorkspaceSettingsResponses,
  SettingsPutWorkspaceSettingsErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    SettingsPutWorkspaceSettingsResponses,
    SettingsPutWorkspaceSettingsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsPutWorkspaceSettingsResponse.parseAsync(data),
    url: "/v1/settings/workspace",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Section
 *
 * The section's values without its secrets; 404 `not_found` for an unknown section.
 */
export const settingsGetSection = <ThrowOnError extends boolean = false>(
  options: Options<SettingsGetSectionData, ThrowOnError>,
): RequestResult<
  SettingsGetSectionResponses,
  SettingsGetSectionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    SettingsGetSectionResponses,
    SettingsGetSectionErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsGetSectionResponse.parseAsync(data),
    url: "/v1/settings/{section}",
    ...options,
  });

/**
 * Put Section
 *
 * Merges `values` into the section at `version`; 409 `stale_version`, 422
 * `validation_error`, 404 `not_found`.
 */
export const settingsPutSection = <ThrowOnError extends boolean = false>(
  options: Options<SettingsPutSectionData, ThrowOnError>,
): RequestResult<
  SettingsPutSectionResponses,
  SettingsPutSectionErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    SettingsPutSectionResponses,
    SettingsPutSectionErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsPutSectionResponse.parseAsync(data),
    url: "/v1/settings/{section}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Setup
 *
 * First run: creates the workspace and its owner and shows the TOTP secret once.
 * 409 `already_set_up`; 403 `signup_disabled` in hosted mode.
 */
export const authSetup = <ThrowOnError extends boolean = false>(
  options: Options<AuthSetupData, ThrowOnError>,
): RequestResult<AuthSetupResponses, AuthSetupErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthSetupResponses,
    AuthSetupErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthSetupResponse.parseAsync(data),
    url: "/v1/setup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Setup Totp
 *
 * Confirms the first code; completes setup and signs the owner in.
 */
export const authSetupTotp = <ThrowOnError extends boolean = false>(
  options: Options<AuthSetupTotpData, ThrowOnError>,
): RequestResult<AuthSetupTotpResponses, AuthSetupTotpErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthSetupTotpResponses,
    AuthSetupTotpErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthSetupTotpResponse.parseAsync(data),
    url: "/v1/setup/totp",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Tasks
 *
 * Tasks, optionally of one project, status, label or parent, and how many match
 * (`total`). `order=created` (default) is creation order; `order=today` is the Today
 * order (priority, then due date, then created time; P0-23). The `list_tasks` tool's
 * twin (P2-01).
 */
export const tasksListTasks = <ThrowOnError extends boolean = false>(
  options?: Options<TasksListTasksData, ThrowOnError>,
): RequestResult<TasksListTasksResponses, TasksListTasksErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    TasksListTasksResponses,
    TasksListTasksErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksListTasksResponse.parseAsync(data),
    url: "/v1/tasks",
    ...options,
  });

/**
 * Create Task
 *
 * A task or subtask; the `create_task` tool's twin (P2-01).
 */
export const tasksCreateTask = <ThrowOnError extends boolean = false>(
  options: Options<TasksCreateTaskData, ThrowOnError>,
): RequestResult<
  TasksCreateTaskResponses,
  TasksCreateTaskErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TasksCreateTaskResponses,
    TasksCreateTaskErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksCreateTaskResponse.parseAsync(data),
    url: "/v1/tasks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Trash Task
 *
 * Moves the task to the trash (UX 9); `POST /undo` with the answered `change_id`
 * brings it back.
 */
export const tasksTrashTask = <ThrowOnError extends boolean = false>(
  options: Options<TasksTrashTaskData, ThrowOnError>,
): RequestResult<TasksTrashTaskResponses, TasksTrashTaskErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    TasksTrashTaskResponses,
    TasksTrashTaskErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksTrashTaskResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Task
 */
export const tasksGetTask = <ThrowOnError extends boolean = false>(
  options: Options<TasksGetTaskData, ThrowOnError>,
): RequestResult<TasksGetTaskResponses, TasksGetTaskErrors, ThrowOnError> =>
  (options.client ?? client).get<
    TasksGetTaskResponses,
    TasksGetTaskErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksGetTaskResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}",
    ...options,
  });

/**
 * Update Task
 */
export const tasksUpdateTask = <ThrowOnError extends boolean = false>(
  options: Options<TasksUpdateTaskData, ThrowOnError>,
): RequestResult<
  TasksUpdateTaskResponses,
  TasksUpdateTaskErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    TasksUpdateTaskResponses,
    TasksUpdateTaskErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksUpdateTaskResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Comments
 *
 * The task's comments, oldest first.
 */
export const tasksListComments = <ThrowOnError extends boolean = false>(
  options: Options<TasksListCommentsData, ThrowOnError>,
): RequestResult<
  TasksListCommentsResponses,
  TasksListCommentsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    TasksListCommentsResponses,
    TasksListCommentsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksListCommentsResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/comments",
    ...options,
  });

/**
 * Add Comment
 */
export const tasksAddComment = <ThrowOnError extends boolean = false>(
  options: Options<TasksAddCommentData, ThrowOnError>,
): RequestResult<
  TasksAddCommentResponses,
  TasksAddCommentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TasksAddCommentResponses,
    TasksAddCommentErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksAddCommentResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/comments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Link Context Item
 *
 * Links outside content by ContextItem id (FR-14.2); linking again keeps one link.
 */
export const tasksLinkContextItem = <ThrowOnError extends boolean = false>(
  options: Options<TasksLinkContextItemData, ThrowOnError>,
): RequestResult<
  TasksLinkContextItemResponses,
  TasksLinkContextItemErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TasksLinkContextItemResponses,
    TasksLinkContextItemErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksLinkContextItemResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/context-items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update Estimate
 *
 * Re-estimates a Human or Hybrid task with a reason (422 `estimate_not_applicable`
 * otherwise); the `update_estimate` tool's twin (P2-01).
 */
export const tasksUpdateEstimate = <ThrowOnError extends boolean = false>(
  options: Options<TasksUpdateEstimateData, ThrowOnError>,
): RequestResult<
  TasksUpdateEstimateResponses,
  TasksUpdateEstimateErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TasksUpdateEstimateResponses,
    TasksUpdateEstimateErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksUpdateEstimateResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/estimate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Move Task
 *
 * One board drag: column, rank and version in one request (R-20).
 */
export const tasksMoveTask = <ThrowOnError extends boolean = false>(
  options: Options<TasksMoveTaskData, ThrowOnError>,
): RequestResult<TasksMoveTaskResponses, TasksMoveTaskErrors, ThrowOnError> =>
  (options.client ?? client).post<
    TasksMoveTaskResponses,
    TasksMoveTaskErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksMoveTaskResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/move",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Task Packet
 *
 * The task's packet as a run would get it, with no token; the `get_task_packet`
 * tool's twin. 404 for a task the caller cannot see.
 */
export const agentsGetTaskPacket = <ThrowOnError extends boolean = false>(
  options: Options<AgentsGetTaskPacketData, ThrowOnError>,
): RequestResult<
  AgentsGetTaskPacketResponses,
  AgentsGetTaskPacketErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    AgentsGetTaskPacketResponses,
    AgentsGetTaskPacketErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsGetTaskPacketResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/packet",
    ...options,
  });

/**
 * List Pull Requests
 *
 * The task's pull requests with their stored status. Opening the task asks for a fresh
 * read: the worker's answer arrives over `/ws` as a change of the task (FR-12.1).
 */
export const tasksListPullRequests = <ThrowOnError extends boolean = false>(
  options: Options<TasksListPullRequestsData, ThrowOnError>,
): RequestResult<
  TasksListPullRequestsResponses,
  TasksListPullRequestsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    TasksListPullRequestsResponses,
    TasksListPullRequestsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksListPullRequestsResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/pull-requests",
    ...options,
  });

/**
 * Link Pull Request
 *
 * Links a github.com pull request (422 `not_a_pull_request`, 422 `repo_not_allowed`
 * outside Settings > GitHub's allow-list); linking again keeps one link (FR-12.1).
 */
export const tasksLinkPullRequest = <ThrowOnError extends boolean = false>(
  options: Options<TasksLinkPullRequestData, ThrowOnError>,
): RequestResult<
  TasksLinkPullRequestResponses,
  TasksLinkPullRequestErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TasksLinkPullRequestResponses,
    TasksLinkPullRequestErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksLinkPullRequestResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/pull-requests",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Recurrence
 *
 * Stops the recurrence at the task's version; the instances made so far stay.
 */
export const tasksDeleteRecurrence = <ThrowOnError extends boolean = false>(
  options: Options<TasksDeleteRecurrenceData, ThrowOnError>,
): RequestResult<
  TasksDeleteRecurrenceResponses,
  TasksDeleteRecurrenceErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    TasksDeleteRecurrenceResponses,
    TasksDeleteRecurrenceErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksDeleteRecurrenceResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/recurrence",
    ...options,
  });

/**
 * Get Recurrence
 *
 * The task's recurrence rule; 404 when it has none.
 */
export const tasksGetRecurrence = <ThrowOnError extends boolean = false>(
  options: Options<TasksGetRecurrenceData, ThrowOnError>,
): RequestResult<
  TasksGetRecurrenceResponses,
  TasksGetRecurrenceErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    TasksGetRecurrenceResponses,
    TasksGetRecurrenceErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksGetRecurrenceResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/recurrence",
    ...options,
  });

/**
 * Put Recurrence
 *
 * Sets or changes the recurrence at the task's version (a preset or a cron, 422
 * `invalid_recurrence`); the task becomes the first instance.
 */
export const tasksPutRecurrence = <ThrowOnError extends boolean = false>(
  options: Options<TasksPutRecurrenceData, ThrowOnError>,
): RequestResult<
  TasksPutRecurrenceResponses,
  TasksPutRecurrenceErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    TasksPutRecurrenceResponses,
    TasksPutRecurrenceErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksPutRecurrenceResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/recurrence",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Request Run
 *
 * Run the task's agent (the Run button): the run is queued and its `dispatch_run`
 * starts as soon as the project has a free slot (two at a time per project). 409
 * `run_already_active`, `status_not_runnable`, `no_ready_profile`; 422
 * `label_not_runnable`.
 */
export const agentsRequestRun = <ThrowOnError extends boolean = false>(
  options: Options<AgentsRequestRunData, ThrowOnError>,
): RequestResult<
  AgentsRequestRunResponses,
  AgentsRequestRunErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AgentsRequestRunResponses,
    AgentsRequestRunErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAgentsRequestRunResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/run",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Change Status
 *
 * Moves the task through the state machine (FR-3.2); the `update_task_status` tool's
 * twin (P2-01).
 */
export const tasksChangeStatus = <ThrowOnError extends boolean = false>(
  options: Options<TasksChangeStatusData, ThrowOnError>,
): RequestResult<
  TasksChangeStatusResponses,
  TasksChangeStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TasksChangeStatusResponses,
    TasksChangeStatusErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksChangeStatusResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/status",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Undo Task
 *
 * Puts back what one change did (R-09, UX 9): 409 `already_undone`, or
 * `stale_version` when the task changed since.
 */
export const tasksUndoTask = <ThrowOnError extends boolean = false>(
  options: Options<TasksUndoTaskData, ThrowOnError>,
): RequestResult<TasksUndoTaskResponses, TasksUndoTaskErrors, ThrowOnError> =>
  (options.client ?? client).post<
    TasksUndoTaskResponses,
    TasksUndoTaskErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksUndoTaskResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/undo",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Typeahead Projects
 *
 * Live projects matching `q` (archived ones drop out), best first.
 */
export const searchTypeaheadProjects = <ThrowOnError extends boolean = false>(
  options?: Options<SearchTypeaheadProjectsData, ThrowOnError>,
): RequestResult<
  SearchTypeaheadProjectsResponses,
  SearchTypeaheadProjectsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    SearchTypeaheadProjectsResponses,
    SearchTypeaheadProjectsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSearchTypeaheadProjectsResponse.parseAsync(data),
    url: "/v1/typeahead/projects",
    ...options,
  });

/**
 * Typeahead Tasks
 *
 * Live tasks matching `q`, best first; the given project's tasks lead.
 */
export const searchTypeaheadTasks = <ThrowOnError extends boolean = false>(
  options?: Options<SearchTypeaheadTasksData, ThrowOnError>,
): RequestResult<
  SearchTypeaheadTasksResponses,
  SearchTypeaheadTasksErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    SearchTypeaheadTasksResponses,
    SearchTypeaheadTasksErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSearchTypeaheadTasksResponse.parseAsync(data),
    url: "/v1/typeahead/tasks",
    ...options,
  });

/**
 * Get Usage
 */
export const usageGetUsage = <ThrowOnError extends boolean = false>(
  options: Options<UsageGetUsageData, ThrowOnError>,
): RequestResult<UsageGetUsageResponses, UsageGetUsageErrors, ThrowOnError> =>
  (options.client ?? client).get<
    UsageGetUsageResponses,
    UsageGetUsageErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zUsageGetUsageResponse.parseAsync(data),
    url: "/v1/usage",
    ...options,
  });
