// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AuditExportAuditCsvData,
  AuditExportAuditCsvErrors,
  AuditExportAuditCsvResponses,
  AuditListAuditData,
  AuditListAuditErrors,
  AuditListAuditResponses,
  AuthConfirmTotpEnrolmentData,
  AuthConfirmTotpEnrolmentErrors,
  AuthConfirmTotpEnrolmentResponses,
  AuthCreateKeyData,
  AuthCreateKeyErrors,
  AuthCreateKeyResponses,
  AuthGetAccountData,
  AuthGetAccountErrors,
  AuthGetAccountResponses,
  AuthListKeysData,
  AuthListKeysErrors,
  AuthListKeysResponses,
  AuthListSessionsData,
  AuthListSessionsErrors,
  AuthListSessionsResponses,
  AuthLoginData,
  AuthLoginErrors,
  AuthLoginResponses,
  AuthLogoutData,
  AuthLogoutErrors,
  AuthLogoutResponses,
  AuthRevokeKeyData,
  AuthRevokeKeyErrors,
  AuthRevokeKeyResponses,
  AuthRevokeSessionData,
  AuthRevokeSessionErrors,
  AuthRevokeSessionResponses,
  AuthRotateKeyData,
  AuthRotateKeyErrors,
  AuthRotateKeyResponses,
  AuthSetupData,
  AuthSetupErrors,
  AuthSetupResponses,
  AuthSetupTotpData,
  AuthSetupTotpErrors,
  AuthSetupTotpResponses,
  AuthSignOutOtherDevicesData,
  AuthSignOutOtherDevicesErrors,
  AuthSignOutOtherDevicesResponses,
  AuthStartTotpEnrolmentData,
  AuthStartTotpEnrolmentErrors,
  AuthStartTotpEnrolmentResponses,
  AuthTotpData,
  AuthTotpErrors,
  AuthTotpResponses,
  CalendarListAccountsData,
  CalendarListAccountsErrors,
  CalendarListAccountsResponses,
  CalendarOauthCallbackData,
  CalendarOauthCallbackErrors,
  CalendarOauthStartData,
  CalendarOauthStartErrors,
  CalendarOauthStartResponses,
  CalendarSelectCalendarsData,
  CalendarSelectCalendarsErrors,
  CalendarSelectCalendarsResponses,
  CalendarSyncNowData,
  CalendarSyncNowErrors,
  CalendarSyncNowResponses,
  DeadLettersGetDeadLettersData,
  DeadLettersGetDeadLettersErrors,
  DeadLettersGetDeadLettersResponses,
  DeadLettersPostDiscardData,
  DeadLettersPostDiscardErrors,
  DeadLettersPostDiscardResponses,
  DeadLettersPostRetryData,
  DeadLettersPostRetryErrors,
  DeadLettersPostRetryResponses,
  HealthLiveData,
  HealthLiveResponses,
  HealthReadyData,
  HealthReadyErrors,
  HealthReadyResponses,
  ProjectsArchiveProjectData,
  ProjectsArchiveProjectErrors,
  ProjectsArchiveProjectResponses,
  ProjectsCreateProjectData,
  ProjectsCreateProjectErrors,
  ProjectsCreateProjectResponses,
  ProjectsGetProjectData,
  ProjectsGetProjectErrors,
  ProjectsGetProjectResponses,
  ProjectsListProjectsData,
  ProjectsListProjectsErrors,
  ProjectsListProjectsResponses,
  ProjectsReorderProjectData,
  ProjectsReorderProjectErrors,
  ProjectsReorderProjectResponses,
  ProjectsUnarchiveProjectData,
  ProjectsUnarchiveProjectErrors,
  ProjectsUnarchiveProjectResponses,
  ProjectsUpdateProjectData,
  ProjectsUpdateProjectErrors,
  ProjectsUpdateProjectResponses,
  SearchSearchData,
  SearchSearchErrors,
  SearchSearchResponses,
  SearchTypeaheadProjectsData,
  SearchTypeaheadProjectsErrors,
  SearchTypeaheadProjectsResponses,
  SearchTypeaheadTasksData,
  SearchTypeaheadTasksErrors,
  SearchTypeaheadTasksResponses,
  SettingsGetSectionData,
  SettingsGetSectionErrors,
  SettingsGetSectionResponses,
  SettingsGetWorkspaceSettingsData,
  SettingsGetWorkspaceSettingsErrors,
  SettingsGetWorkspaceSettingsResponses,
  SettingsListModulesData,
  SettingsListModulesErrors,
  SettingsListModulesResponses,
  SettingsPutSectionData,
  SettingsPutSectionErrors,
  SettingsPutSectionResponses,
  SettingsPutWorkspaceSettingsData,
  SettingsPutWorkspaceSettingsErrors,
  SettingsPutWorkspaceSettingsResponses,
  SettingsSetModuleData,
  SettingsSetModuleErrors,
  SettingsSetModuleResponses,
  TasksAddCommentData,
  TasksAddCommentErrors,
  TasksAddCommentResponses,
  TasksChangeStatusData,
  TasksChangeStatusErrors,
  TasksChangeStatusResponses,
  TasksCreateTaskData,
  TasksCreateTaskErrors,
  TasksCreateTaskResponses,
  TasksGetBoardData,
  TasksGetBoardErrors,
  TasksGetBoardResponses,
  TasksGetColumnsData,
  TasksGetColumnsErrors,
  TasksGetColumnsResponses,
  TasksGetReviewCountData,
  TasksGetReviewCountErrors,
  TasksGetReviewCountResponses,
  TasksGetTaskData,
  TasksGetTaskErrors,
  TasksGetTaskResponses,
  TasksLinkContextItemData,
  TasksLinkContextItemErrors,
  TasksLinkContextItemResponses,
  TasksListReviewKindsData,
  TasksListReviewKindsErrors,
  TasksListReviewKindsResponses,
  TasksListTasksData,
  TasksListTasksErrors,
  TasksListTasksResponses,
  TasksMoveTaskData,
  TasksMoveTaskErrors,
  TasksMoveTaskResponses,
  TasksPutColumnsData,
  TasksPutColumnsErrors,
  TasksPutColumnsResponses,
  TasksUpdateTaskData,
  TasksUpdateTaskErrors,
  TasksUpdateTaskResponses,
  UsageGetUsageData,
  UsageGetUsageErrors,
  UsageGetUsageResponses,
} from "./types.gen";
import {
  zAuditListAuditResponse,
  zAuthConfirmTotpEnrolmentResponse,
  zAuthCreateKeyResponse,
  zAuthGetAccountResponse,
  zAuthListKeysResponse,
  zAuthListSessionsResponse,
  zAuthLoginResponse,
  zAuthLogoutResponse,
  zAuthRevokeKeyResponse,
  zAuthRevokeSessionResponse,
  zAuthRotateKeyResponse,
  zAuthSetupResponse,
  zAuthSetupTotpResponse,
  zAuthSignOutOtherDevicesResponse,
  zAuthStartTotpEnrolmentResponse,
  zAuthTotpResponse,
  zCalendarListAccountsResponse,
  zCalendarOauthStartResponse,
  zCalendarSelectCalendarsResponse,
  zCalendarSyncNowResponse,
  zDeadLettersGetDeadLettersResponse,
  zDeadLettersPostDiscardResponse,
  zDeadLettersPostRetryResponse,
  zHealthLiveResponse,
  zProjectsArchiveProjectResponse,
  zProjectsCreateProjectResponse,
  zProjectsGetProjectResponse,
  zProjectsListProjectsResponse,
  zProjectsReorderProjectResponse,
  zProjectsUnarchiveProjectResponse,
  zProjectsUpdateProjectResponse,
  zSearchSearchResponse,
  zSearchTypeaheadProjectsResponse,
  zSearchTypeaheadTasksResponse,
  zSettingsGetSectionResponse,
  zSettingsGetWorkspaceSettingsResponse,
  zSettingsListModulesResponse,
  zSettingsPutSectionResponse,
  zSettingsPutWorkspaceSettingsResponse,
  zSettingsSetModuleResponse,
  zTasksAddCommentResponse,
  zTasksChangeStatusResponse,
  zTasksCreateTaskResponse,
  zTasksGetBoardResponse,
  zTasksGetColumnsResponse,
  zTasksGetReviewCountResponse,
  zTasksGetTaskResponse,
  zTasksLinkContextItemResponse,
  zTasksListReviewKindsResponse,
  zTasksListTasksResponse,
  zTasksMoveTaskResponse,
  zTasksPutColumnsResponse,
  zTasksUpdateTaskResponse,
  zUsageGetUsageResponse,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Live
 */
export const healthLive = <ThrowOnError extends boolean = false>(
  options?: Options<HealthLiveData, ThrowOnError>,
): RequestResult<HealthLiveResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<HealthLiveResponses, unknown, ThrowOnError>({
    responseValidator: async (data) =>
      await zHealthLiveResponse.parseAsync(data),
    url: "/health/live",
    ...options,
  });

/**
 * Ready
 */
export const healthReady = <ThrowOnError extends boolean = false>(
  options?: Options<HealthReadyData, ThrowOnError>,
): RequestResult<HealthReadyResponses, HealthReadyErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    HealthReadyResponses,
    HealthReadyErrors,
    ThrowOnError
  >({ url: "/health/ready", ...options });

/**
 * List Audit
 *
 * The workspace's audit log, newest first.
 */
export const auditListAudit = <ThrowOnError extends boolean = false>(
  options?: Options<AuditListAuditData, ThrowOnError>,
): RequestResult<AuditListAuditResponses, AuditListAuditErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    AuditListAuditResponses,
    AuditListAuditErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuditListAuditResponse.parseAsync(data),
    url: "/v1/audit",
    ...options,
  });

/**
 * Export Audit Csv
 *
 * The workspace's audit log as CSV, newest first; the export is audited.
 */
export const auditExportAuditCsv = <ThrowOnError extends boolean = false>(
  options?: Options<AuditExportAuditCsvData, ThrowOnError>,
): RequestResult<
  AuditExportAuditCsvResponses,
  AuditExportAuditCsvErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AuditExportAuditCsvResponses,
    AuditExportAuditCsvErrors,
    ThrowOnError
  >({ url: "/v1/audit.csv", ...options });

/**
 * Get Account
 *
 * The signed-in user's email and second factor.
 */
export const authGetAccount = <ThrowOnError extends boolean = false>(
  options?: Options<AuthGetAccountData, ThrowOnError>,
): RequestResult<AuthGetAccountResponses, AuthGetAccountErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    AuthGetAccountResponses,
    AuthGetAccountErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthGetAccountResponse.parseAsync(data),
    url: "/v1/auth/account",
    ...options,
  });

/**
 * Login
 *
 * The password step: answers `{"step": "totp", "preauth": ...}` and sets no cookie.
 */
export const authLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthLoginData, ThrowOnError>,
): RequestResult<AuthLoginResponses, AuthLoginErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthLoginResponses,
    AuthLoginErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthLoginResponse.parseAsync(data),
    url: "/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Logout
 *
 * Ends this session and clears its cookies.
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthLogoutData, ThrowOnError>,
): RequestResult<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    AuthLogoutResponses,
    AuthLogoutErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthLogoutResponse.parseAsync(data),
    url: "/v1/auth/logout",
    ...options,
  });

/**
 * Sign Out Other Devices
 *
 * Revokes every session of this user but the calling one (R-21).
 */
export const authSignOutOtherDevices = <ThrowOnError extends boolean = false>(
  options?: Options<AuthSignOutOtherDevicesData, ThrowOnError>,
): RequestResult<
  AuthSignOutOtherDevicesResponses,
  AuthSignOutOtherDevicesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    AuthSignOutOtherDevicesResponses,
    AuthSignOutOtherDevicesErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthSignOutOtherDevicesResponse.parseAsync(data),
    url: "/v1/auth/sessions",
    ...options,
  });

/**
 * List Sessions
 *
 * This user's signed-in devices, newest first, the calling one `current`.
 */
export const authListSessions = <ThrowOnError extends boolean = false>(
  options?: Options<AuthListSessionsData, ThrowOnError>,
): RequestResult<
  AuthListSessionsResponses,
  AuthListSessionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AuthListSessionsResponses,
    AuthListSessionsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthListSessionsResponse.parseAsync(data),
    url: "/v1/auth/sessions",
    ...options,
  });

/**
 * Revoke Session
 *
 * Revokes one of this user's sessions.
 */
export const authRevokeSession = <ThrowOnError extends boolean = false>(
  options: Options<AuthRevokeSessionData, ThrowOnError>,
): RequestResult<
  AuthRevokeSessionResponses,
  AuthRevokeSessionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    AuthRevokeSessionResponses,
    AuthRevokeSessionErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthRevokeSessionResponse.parseAsync(data),
    url: "/v1/auth/sessions/{session_id}",
    ...options,
  });

/**
 * Totp
 *
 * The TOTP step: sets the session and CSRF cookies.
 */
export const authTotp = <ThrowOnError extends boolean = false>(
  options: Options<AuthTotpData, ThrowOnError>,
): RequestResult<AuthTotpResponses, AuthTotpErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthTotpResponses,
    AuthTotpErrors,
    ThrowOnError
  >({
    responseValidator: async (data) => await zAuthTotpResponse.parseAsync(data),
    url: "/v1/auth/totp",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Start Totp Enrolment
 *
 * With the password: a new TOTP secret (shown once) and its enrolment token. 401
 * `invalid_credentials`, 429 `locked_out`.
 */
export const authStartTotpEnrolment = <ThrowOnError extends boolean = false>(
  options: Options<AuthStartTotpEnrolmentData, ThrowOnError>,
): RequestResult<
  AuthStartTotpEnrolmentResponses,
  AuthStartTotpEnrolmentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthStartTotpEnrolmentResponses,
    AuthStartTotpEnrolmentErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthStartTotpEnrolmentResponse.parseAsync(data),
    url: "/v1/auth/totp/enrol",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Confirm Totp Enrolment
 *
 * A code from the new secret replaces the old one. 401 `invalid_code`,
 * `invalid_enrol_token`.
 */
export const authConfirmTotpEnrolment = <ThrowOnError extends boolean = false>(
  options: Options<AuthConfirmTotpEnrolmentData, ThrowOnError>,
): RequestResult<
  AuthConfirmTotpEnrolmentResponses,
  AuthConfirmTotpEnrolmentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthConfirmTotpEnrolmentResponses,
    AuthConfirmTotpEnrolmentErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthConfirmTotpEnrolmentResponse.parseAsync(data),
    url: "/v1/auth/totp/enrol/confirm",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Accounts
 */
export const calendarListAccounts = <ThrowOnError extends boolean = false>(
  options?: Options<CalendarListAccountsData, ThrowOnError>,
): RequestResult<
  CalendarListAccountsResponses,
  CalendarListAccountsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    CalendarListAccountsResponses,
    CalendarListAccountsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zCalendarListAccountsResponse.parseAsync(data),
    url: "/v1/calendar/accounts",
    ...options,
  });

/**
 * Select Calendars
 */
export const calendarSelectCalendars = <ThrowOnError extends boolean = false>(
  options: Options<CalendarSelectCalendarsData, ThrowOnError>,
): RequestResult<
  CalendarSelectCalendarsResponses,
  CalendarSelectCalendarsErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    CalendarSelectCalendarsResponses,
    CalendarSelectCalendarsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zCalendarSelectCalendarsResponse.parseAsync(data),
    url: "/v1/calendar/accounts/{calendar_account_id}/calendars",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Sync Now
 */
export const calendarSyncNow = <ThrowOnError extends boolean = false>(
  options: Options<CalendarSyncNowData, ThrowOnError>,
): RequestResult<
  CalendarSyncNowResponses,
  CalendarSyncNowErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CalendarSyncNowResponses,
    CalendarSyncNowErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zCalendarSyncNowResponse.parseAsync(data),
    url: "/v1/calendar/accounts/{calendar_account_id}/sync",
    ...options,
  });

/**
 * Oauth Callback
 */
export const calendarOauthCallback = <ThrowOnError extends boolean = false>(
  options: Options<CalendarOauthCallbackData, ThrowOnError>,
): RequestResult<unknown, CalendarOauthCallbackErrors, ThrowOnError> =>
  (options.client ?? client).get<
    unknown,
    CalendarOauthCallbackErrors,
    ThrowOnError
  >({ url: "/v1/calendar/oauth/callback", ...options });

/**
 * Oauth Start
 */
export const calendarOauthStart = <ThrowOnError extends boolean = false>(
  options?: Options<CalendarOauthStartData, ThrowOnError>,
): RequestResult<
  CalendarOauthStartResponses,
  CalendarOauthStartErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    CalendarOauthStartResponses,
    CalendarOauthStartErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zCalendarOauthStartResponse.parseAsync(data),
    url: "/v1/calendar/oauth/start",
    ...options,
  });

/**
 * Get Dead Letters
 */
export const deadLettersGetDeadLetters = <ThrowOnError extends boolean = false>(
  options?: Options<DeadLettersGetDeadLettersData, ThrowOnError>,
): RequestResult<
  DeadLettersGetDeadLettersResponses,
  DeadLettersGetDeadLettersErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    DeadLettersGetDeadLettersResponses,
    DeadLettersGetDeadLettersErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zDeadLettersGetDeadLettersResponse.parseAsync(data),
    url: "/v1/dead-letters",
    ...options,
  });

/**
 * Post Discard
 */
export const deadLettersPostDiscard = <ThrowOnError extends boolean = false>(
  options: Options<DeadLettersPostDiscardData, ThrowOnError>,
): RequestResult<
  DeadLettersPostDiscardResponses,
  DeadLettersPostDiscardErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    DeadLettersPostDiscardResponses,
    DeadLettersPostDiscardErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zDeadLettersPostDiscardResponse.parseAsync(data),
    url: "/v1/dead-letters/{dead_letter_id}/discard",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Post Retry
 */
export const deadLettersPostRetry = <ThrowOnError extends boolean = false>(
  options: Options<DeadLettersPostRetryData, ThrowOnError>,
): RequestResult<
  DeadLettersPostRetryResponses,
  DeadLettersPostRetryErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    DeadLettersPostRetryResponses,
    DeadLettersPostRetryErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zDeadLettersPostRetryResponse.parseAsync(data),
    url: "/v1/dead-letters/{dead_letter_id}/retry",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Keys
 *
 * The workspace's API keys: name, prefix, scopes, projects, created, expires, last
 * used, revoked; never the secret.
 */
export const authListKeys = <ThrowOnError extends boolean = false>(
  options?: Options<AuthListKeysData, ThrowOnError>,
): RequestResult<AuthListKeysResponses, AuthListKeysErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    AuthListKeysResponses,
    AuthListKeysErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthListKeysResponse.parseAsync(data),
    url: "/v1/keys",
    ...options,
  });

/**
 * Create Key
 *
 * A new key; the response shows `key` once. 422 `unknown_scope`.
 */
export const authCreateKey = <ThrowOnError extends boolean = false>(
  options: Options<AuthCreateKeyData, ThrowOnError>,
): RequestResult<AuthCreateKeyResponses, AuthCreateKeyErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthCreateKeyResponses,
    AuthCreateKeyErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthCreateKeyResponse.parseAsync(data),
    url: "/v1/keys",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Revoke Key
 *
 * Revokes the key: every process refuses it within a second.
 */
export const authRevokeKey = <ThrowOnError extends boolean = false>(
  options: Options<AuthRevokeKeyData, ThrowOnError>,
): RequestResult<AuthRevokeKeyResponses, AuthRevokeKeyErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    AuthRevokeKeyResponses,
    AuthRevokeKeyErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthRevokeKeyResponse.parseAsync(data),
    url: "/v1/keys/{id}",
    ...options,
  });

/**
 * Rotate Key
 *
 * A new secret on the same key, shown once; the old one stops at once or after
 * `grace_minutes` (0 to 1,440). 409 `key_revoked`.
 */
export const authRotateKey = <ThrowOnError extends boolean = false>(
  options: Options<AuthRotateKeyData, ThrowOnError>,
): RequestResult<AuthRotateKeyResponses, AuthRotateKeyErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthRotateKeyResponses,
    AuthRotateKeyErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthRotateKeyResponse.parseAsync(data),
    url: "/v1/keys/{id}/rotate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Projects
 *
 * Projects in board order; archived ones with `include_archived=true`.
 */
export const projectsListProjects = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectsListProjectsData, ThrowOnError>,
): RequestResult<
  ProjectsListProjectsResponses,
  ProjectsListProjectsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ProjectsListProjectsResponses,
    ProjectsListProjectsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsListProjectsResponse.parseAsync(data),
    url: "/v1/projects",
    ...options,
  });

/**
 * Create Project
 */
export const projectsCreateProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsCreateProjectData, ThrowOnError>,
): RequestResult<
  ProjectsCreateProjectResponses,
  ProjectsCreateProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectsCreateProjectResponses,
    ProjectsCreateProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsCreateProjectResponse.parseAsync(data),
    url: "/v1/projects",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Project
 */
export const projectsGetProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsGetProjectData, ThrowOnError>,
): RequestResult<
  ProjectsGetProjectResponses,
  ProjectsGetProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectsGetProjectResponses,
    ProjectsGetProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsGetProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}",
    ...options,
  });

/**
 * Update Project
 */
export const projectsUpdateProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsUpdateProjectData, ThrowOnError>,
): RequestResult<
  ProjectsUpdateProjectResponses,
  ProjectsUpdateProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    ProjectsUpdateProjectResponses,
    ProjectsUpdateProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsUpdateProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Archive Project
 */
export const projectsArchiveProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsArchiveProjectData, ThrowOnError>,
): RequestResult<
  ProjectsArchiveProjectResponses,
  ProjectsArchiveProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectsArchiveProjectResponses,
    ProjectsArchiveProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsArchiveProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/archive",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Board
 *
 * The kanban: columns, cards and each card's checklist (FR-3.4).
 */
export const tasksGetBoard = <ThrowOnError extends boolean = false>(
  options: Options<TasksGetBoardData, ThrowOnError>,
): RequestResult<TasksGetBoardResponses, TasksGetBoardErrors, ThrowOnError> =>
  (options.client ?? client).get<
    TasksGetBoardResponses,
    TasksGetBoardErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksGetBoardResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/board",
    ...options,
  });

/**
 * Get Columns
 */
export const tasksGetColumns = <ThrowOnError extends boolean = false>(
  options: Options<TasksGetColumnsData, ThrowOnError>,
): RequestResult<
  TasksGetColumnsResponses,
  TasksGetColumnsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    TasksGetColumnsResponses,
    TasksGetColumnsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksGetColumnsResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/columns",
    ...options,
  });

/**
 * Put Columns
 *
 * Renames, reorders, adds and removes columns in one request; every status keeps at
 * least one column (422 `status_without_column`).
 */
export const tasksPutColumns = <ThrowOnError extends boolean = false>(
  options: Options<TasksPutColumnsData, ThrowOnError>,
): RequestResult<
  TasksPutColumnsResponses,
  TasksPutColumnsErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    TasksPutColumnsResponses,
    TasksPutColumnsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksPutColumnsResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/columns",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reorder Project
 *
 * Moves the project between two neighbours (either may be null: an open end).
 */
export const projectsReorderProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsReorderProjectData, ThrowOnError>,
): RequestResult<
  ProjectsReorderProjectResponses,
  ProjectsReorderProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectsReorderProjectResponses,
    ProjectsReorderProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsReorderProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/reorder",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Unarchive Project
 */
export const projectsUnarchiveProject = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsUnarchiveProjectData, ThrowOnError>,
): RequestResult<
  ProjectsUnarchiveProjectResponses,
  ProjectsUnarchiveProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProjectsUnarchiveProjectResponses,
    ProjectsUnarchiveProjectErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zProjectsUnarchiveProjectResponse.parseAsync(data),
    url: "/v1/projects/{project_id}/unarchive",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Review Count
 *
 * The badge: review items waiting now (not decided, trashed or snoozed).
 */
export const tasksGetReviewCount = <ThrowOnError extends boolean = false>(
  options?: Options<TasksGetReviewCountData, ThrowOnError>,
): RequestResult<
  TasksGetReviewCountResponses,
  TasksGetReviewCountErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    TasksGetReviewCountResponses,
    TasksGetReviewCountErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksGetReviewCountResponse.parseAsync(data),
    url: "/v1/review/count",
    ...options,
  });

/**
 * List Review Kinds
 *
 * The registered review kinds and their actions (R-03, R-05).
 */
export const tasksListReviewKinds = <ThrowOnError extends boolean = false>(
  options?: Options<TasksListReviewKindsData, ThrowOnError>,
): RequestResult<
  TasksListReviewKindsResponses,
  TasksListReviewKindsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    TasksListReviewKindsResponses,
    TasksListReviewKindsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksListReviewKindsResponse.parseAsync(data),
    url: "/v1/review/kinds",
    ...options,
  });

/**
 * Search
 *
 * Tasks and projects matching `q`, best first: text match, recency, project match.
 */
export const searchSearch = <ThrowOnError extends boolean = false>(
  options?: Options<SearchSearchData, ThrowOnError>,
): RequestResult<SearchSearchResponses, SearchSearchErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    SearchSearchResponses,
    SearchSearchErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSearchSearchResponse.parseAsync(data),
    url: "/v1/search",
    ...options,
  });

/**
 * List Modules
 *
 * Every module, whether it is on for this workspace, and whether it can be off.
 */
export const settingsListModules = <ThrowOnError extends boolean = false>(
  options?: Options<SettingsListModulesData, ThrowOnError>,
): RequestResult<
  SettingsListModulesResponses,
  SettingsListModulesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    SettingsListModulesResponses,
    SettingsListModulesErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsListModulesResponse.parseAsync(data),
    url: "/v1/settings/modules",
    ...options,
  });

/**
 * Set Module
 *
 * Switches the module on or off for this workspace. 422 `module_required`.
 */
export const settingsSetModule = <ThrowOnError extends boolean = false>(
  options: Options<SettingsSetModuleData, ThrowOnError>,
): RequestResult<
  SettingsSetModuleResponses,
  SettingsSetModuleErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    SettingsSetModuleResponses,
    SettingsSetModuleErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsSetModuleResponse.parseAsync(data),
    url: "/v1/settings/modules",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Workspace Settings
 */
export const settingsGetWorkspaceSettings = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SettingsGetWorkspaceSettingsData, ThrowOnError>,
): RequestResult<
  SettingsGetWorkspaceSettingsResponses,
  SettingsGetWorkspaceSettingsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    SettingsGetWorkspaceSettingsResponses,
    SettingsGetWorkspaceSettingsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsGetWorkspaceSettingsResponse.parseAsync(data),
    url: "/v1/settings/workspace",
    ...options,
  });

/**
 * Put Workspace Settings
 */
export const settingsPutWorkspaceSettings = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SettingsPutWorkspaceSettingsData, ThrowOnError>,
): RequestResult<
  SettingsPutWorkspaceSettingsResponses,
  SettingsPutWorkspaceSettingsErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    SettingsPutWorkspaceSettingsResponses,
    SettingsPutWorkspaceSettingsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsPutWorkspaceSettingsResponse.parseAsync(data),
    url: "/v1/settings/workspace",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Section
 *
 * The section's values without its secrets; 404 `not_found` for an unknown section.
 */
export const settingsGetSection = <ThrowOnError extends boolean = false>(
  options: Options<SettingsGetSectionData, ThrowOnError>,
): RequestResult<
  SettingsGetSectionResponses,
  SettingsGetSectionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    SettingsGetSectionResponses,
    SettingsGetSectionErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsGetSectionResponse.parseAsync(data),
    url: "/v1/settings/{section}",
    ...options,
  });

/**
 * Put Section
 *
 * Merges `values` into the section at `version`; 409 `stale_version`, 422
 * `validation_error`, 404 `not_found`.
 */
export const settingsPutSection = <ThrowOnError extends boolean = false>(
  options: Options<SettingsPutSectionData, ThrowOnError>,
): RequestResult<
  SettingsPutSectionResponses,
  SettingsPutSectionErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    SettingsPutSectionResponses,
    SettingsPutSectionErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSettingsPutSectionResponse.parseAsync(data),
    url: "/v1/settings/{section}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Setup
 *
 * First run: creates the workspace and its owner and shows the TOTP secret once.
 * 409 `already_set_up`; 403 `signup_disabled` in hosted mode.
 */
export const authSetup = <ThrowOnError extends boolean = false>(
  options: Options<AuthSetupData, ThrowOnError>,
): RequestResult<AuthSetupResponses, AuthSetupErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthSetupResponses,
    AuthSetupErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthSetupResponse.parseAsync(data),
    url: "/v1/setup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Setup Totp
 *
 * Confirms the first code; completes setup and signs the owner in.
 */
export const authSetupTotp = <ThrowOnError extends boolean = false>(
  options: Options<AuthSetupTotpData, ThrowOnError>,
): RequestResult<AuthSetupTotpResponses, AuthSetupTotpErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthSetupTotpResponses,
    AuthSetupTotpErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAuthSetupTotpResponse.parseAsync(data),
    url: "/v1/setup/totp",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Tasks
 *
 * Tasks, optionally of one project and one status, and how many match (`total`).
 * `order=created` (default) is creation order; `order=today` is the Today order
 * (priority, then due date, then created time; P0-23).
 */
export const tasksListTasks = <ThrowOnError extends boolean = false>(
  options?: Options<TasksListTasksData, ThrowOnError>,
): RequestResult<TasksListTasksResponses, TasksListTasksErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    TasksListTasksResponses,
    TasksListTasksErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksListTasksResponse.parseAsync(data),
    url: "/v1/tasks",
    ...options,
  });

/**
 * Create Task
 */
export const tasksCreateTask = <ThrowOnError extends boolean = false>(
  options: Options<TasksCreateTaskData, ThrowOnError>,
): RequestResult<
  TasksCreateTaskResponses,
  TasksCreateTaskErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TasksCreateTaskResponses,
    TasksCreateTaskErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksCreateTaskResponse.parseAsync(data),
    url: "/v1/tasks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Task
 */
export const tasksGetTask = <ThrowOnError extends boolean = false>(
  options: Options<TasksGetTaskData, ThrowOnError>,
): RequestResult<TasksGetTaskResponses, TasksGetTaskErrors, ThrowOnError> =>
  (options.client ?? client).get<
    TasksGetTaskResponses,
    TasksGetTaskErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksGetTaskResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}",
    ...options,
  });

/**
 * Update Task
 */
export const tasksUpdateTask = <ThrowOnError extends boolean = false>(
  options: Options<TasksUpdateTaskData, ThrowOnError>,
): RequestResult<
  TasksUpdateTaskResponses,
  TasksUpdateTaskErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    TasksUpdateTaskResponses,
    TasksUpdateTaskErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksUpdateTaskResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Add Comment
 */
export const tasksAddComment = <ThrowOnError extends boolean = false>(
  options: Options<TasksAddCommentData, ThrowOnError>,
): RequestResult<
  TasksAddCommentResponses,
  TasksAddCommentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TasksAddCommentResponses,
    TasksAddCommentErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksAddCommentResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/comments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Link Context Item
 *
 * Links outside content by ContextItem id (FR-14.2); linking again keeps one link.
 */
export const tasksLinkContextItem = <ThrowOnError extends boolean = false>(
  options: Options<TasksLinkContextItemData, ThrowOnError>,
): RequestResult<
  TasksLinkContextItemResponses,
  TasksLinkContextItemErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TasksLinkContextItemResponses,
    TasksLinkContextItemErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksLinkContextItemResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/context-items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Move Task
 *
 * One board drag: column, rank and version in one request (R-20).
 */
export const tasksMoveTask = <ThrowOnError extends boolean = false>(
  options: Options<TasksMoveTaskData, ThrowOnError>,
): RequestResult<TasksMoveTaskResponses, TasksMoveTaskErrors, ThrowOnError> =>
  (options.client ?? client).post<
    TasksMoveTaskResponses,
    TasksMoveTaskErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksMoveTaskResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/move",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Change Status
 *
 * Moves the task through the state machine (FR-3.2).
 */
export const tasksChangeStatus = <ThrowOnError extends boolean = false>(
  options: Options<TasksChangeStatusData, ThrowOnError>,
): RequestResult<
  TasksChangeStatusResponses,
  TasksChangeStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TasksChangeStatusResponses,
    TasksChangeStatusErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zTasksChangeStatusResponse.parseAsync(data),
    url: "/v1/tasks/{task_id}/status",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Typeahead Projects
 *
 * Live projects matching `q` (archived ones drop out), best first.
 */
export const searchTypeaheadProjects = <ThrowOnError extends boolean = false>(
  options?: Options<SearchTypeaheadProjectsData, ThrowOnError>,
): RequestResult<
  SearchTypeaheadProjectsResponses,
  SearchTypeaheadProjectsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    SearchTypeaheadProjectsResponses,
    SearchTypeaheadProjectsErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSearchTypeaheadProjectsResponse.parseAsync(data),
    url: "/v1/typeahead/projects",
    ...options,
  });

/**
 * Typeahead Tasks
 *
 * Live tasks matching `q`, best first; the given project's tasks lead.
 */
export const searchTypeaheadTasks = <ThrowOnError extends boolean = false>(
  options?: Options<SearchTypeaheadTasksData, ThrowOnError>,
): RequestResult<
  SearchTypeaheadTasksResponses,
  SearchTypeaheadTasksErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    SearchTypeaheadTasksResponses,
    SearchTypeaheadTasksErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zSearchTypeaheadTasksResponse.parseAsync(data),
    url: "/v1/typeahead/tasks",
    ...options,
  });

/**
 * Get Usage
 */
export const usageGetUsage = <ThrowOnError extends boolean = false>(
  options: Options<UsageGetUsageData, ThrowOnError>,
): RequestResult<UsageGetUsageResponses, UsageGetUsageErrors, ThrowOnError> =>
  (options.client ?? client).get<
    UsageGetUsageResponses,
    UsageGetUsageErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zUsageGetUsageResponse.parseAsync(data),
    url: "/v1/usage",
    ...options,
  });
