// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountOut
 */
export type AccountOut = {
  /**
   * Email
   */
  email: string;
  /**
   * Second Factor
   */
  second_factor: "totp";
  /**
   * Totp Confirmed At
   */
  totp_confirmed_at: string | null;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * AuditEntry
 */
export type AuditEntry = {
  /**
   * Action
   */
  action: string;
  /**
   * Actor Id
   */
  actor_id: string | null;
  /**
   * Actor Type
   */
  actor_type: string;
  /**
   * Correlation Id
   */
  correlation_id: string | null;
  /**
   * Details
   */
  details: {
    [key: string]: unknown;
  };
  /**
   * Id
   */
  id: string;
  /**
   * Occurred At
   */
  occurred_at: string;
  /**
   * Reason
   */
  reason: string | null;
  /**
   * Seq
   */
  seq: number;
  /**
   * Source Ip
   */
  source_ip: string | null;
  /**
   * Target Id
   */
  target_id: string | null;
  /**
   * Target Type
   */
  target_type: string | null;
  /**
   * User Agent
   */
  user_agent: string | null;
};

/**
 * BoardColumnOut
 */
export type BoardColumnOut = {
  /**
   * Cards
   */
  cards: Array<CardOut>;
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  status: Status;
};

/**
 * BoardOut
 */
export type BoardOut = {
  /**
   * Columns
   */
  columns: Array<BoardColumnOut>;
  /**
   * Project Id
   */
  project_id: string;
  /**
   * Threshold Min
   */
  threshold_min: number;
};

/**
 * CardOut
 */
export type CardOut = {
  /**
   * Checklist
   */
  checklist: Array<TaskOut>;
  task: TaskOut;
};

/**
 * ColumnIn
 */
export type ColumnIn = {
  /**
   * Id
   */
  id?: string | null;
  /**
   * Name
   */
  name: string;
  status: Status;
};

/**
 * ColumnOut
 */
export type ColumnOut = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Sort Key
   */
  sort_key: string;
  status: Status;
  /**
   * Version
   */
  version: number;
};

/**
 * ColumnsIn
 */
export type ColumnsIn = {
  /**
   * Columns
   */
  columns: Array<ColumnIn>;
};

/**
 * ColumnsOut
 */
export type ColumnsOut = {
  /**
   * Items
   */
  items: Array<ColumnOut>;
  /**
   * Project Id
   */
  project_id: string;
};

/**
 * CommentIn
 */
export type CommentIn = {
  /**
   * Body Md
   */
  body_md: string;
};

/**
 * CommentOut
 */
export type CommentOut = {
  /**
   * Body Md
   */
  body_md: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Created By
   */
  created_by: string;
  /**
   * Id
   */
  id: string;
  /**
   * Task Id
   */
  task_id: string;
  /**
   * Version
   */
  version: number;
};

/**
 * ContextItemIn
 */
export type ContextItemIn = {
  /**
   * Context Item Id
   */
  context_item_id: string;
};

/**
 * DeadLetterOut
 */
export type DeadLetterOut = {
  /**
   * Attempts
   */
  attempts: number;
  /**
   * Error
   */
  error: string;
  /**
   * Event Id
   */
  event_id: string;
  /**
   * Event Name
   */
  event_name: string;
  /**
   * Id
   */
  id: string;
  /**
   * Last At
   */
  last_at: string;
  /**
   * Retries
   */
  retries: number;
  /**
   * Status
   */
  status: string;
  /**
   * Subscriber
   */
  subscriber: string;
  /**
   * Version
   */
  version: number;
};

/**
 * Health
 */
export type Health = "blocked" | "at_risk" | "on_track";

/**
 * KeyCreated
 */
export type KeyCreated = {
  /**
   * Created At
   */
  created_at: string;
  /**
   * Expires At
   */
  expires_at: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Key
   */
  key: string;
  /**
   * Last Used At
   */
  last_used_at: string | null;
  /**
   * Name
   */
  name: string;
  /**
   * Prefix
   */
  prefix: string;
  /**
   * Project Ids
   */
  project_ids: Array<string> | null;
  /**
   * Revoked At
   */
  revoked_at: string | null;
  /**
   * Scopes
   */
  scopes: Array<string>;
};

/**
 * KeyIn
 */
export type KeyIn = {
  /**
   * Expires At
   */
  expires_at?: string | null;
  /**
   * Name
   */
  name: string;
  /**
   * Project Ids
   */
  project_ids?: Array<string> | null;
  /**
   * Scopes
   */
  scopes: Array<string>;
};

/**
 * KeyOut
 */
export type KeyOut = {
  /**
   * Created At
   */
  created_at: string;
  /**
   * Expires At
   */
  expires_at: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Last Used At
   */
  last_used_at: string | null;
  /**
   * Name
   */
  name: string;
  /**
   * Prefix
   */
  prefix: string;
  /**
   * Project Ids
   */
  project_ids: Array<string> | null;
  /**
   * Revoked At
   */
  revoked_at: string | null;
  /**
   * Scopes
   */
  scopes: Array<string>;
};

/**
 * Label
 */
export type Label = "human" | "ai" | "hybrid";

/**
 * LoginIn
 *
 * `provider` picks the sign-in provider; the other string fields are its credentials
 * (`email` and `password` for `local_password`).
 */
export type LoginIn = {
  /**
   * Email
   */
  email?: string | null;
  /**
   * Password
   */
  password?: string | null;
  /**
   * Provider
   */
  provider?: string;
  [key: string]: unknown;
};

/**
 * LoginOut
 */
export type LoginOut = {
  /**
   * Preauth
   */
  preauth: string;
  /**
   * Step
   */
  step?: "totp";
};

/**
 * ModuleFlagIn
 */
export type ModuleFlagIn = {
  /**
   * Enabled
   */
  enabled: boolean;
  /**
   * Module
   */
  module: string;
};

/**
 * ModuleFlagOut
 */
export type ModuleFlagOut = {
  /**
   * Enabled
   */
  enabled: boolean;
  /**
   * Module
   */
  module: string;
  /**
   * Required
   */
  required: boolean;
};

/**
 * ModuleFlagsOut
 */
export type ModuleFlagsOut = {
  /**
   * Items
   */
  items: Array<ModuleFlagOut>;
};

/**
 * MoveIn
 *
 * One board drag (R-20): the target column, the rank between the new neighbours'
 * ranks (core/rank.py) and the version read.
 */
export type MoveIn = {
  /**
   * Board Rank
   */
  board_rank: string;
  /**
   * Column Id
   */
  column_id: string;
  /**
   * Version
   */
  version: number;
};

/**
 * Page[AuditEntry]
 */
export type PageAuditEntry = {
  /**
   * Items
   */
  items: Array<AuditEntry>;
  /**
   * Next Cursor
   */
  next_cursor: string | null;
};

/**
 * Page[DeadLetterOut]
 */
export type PageDeadLetterOut = {
  /**
   * Items
   */
  items: Array<DeadLetterOut>;
  /**
   * Next Cursor
   */
  next_cursor: string | null;
};

/**
 * Page[KeyOut]
 */
export type PageKeyOut = {
  /**
   * Items
   */
  items: Array<KeyOut>;
  /**
   * Next Cursor
   */
  next_cursor: string | null;
};

/**
 * Page[ProjectOut]
 */
export type PageProjectOut = {
  /**
   * Items
   */
  items: Array<ProjectOut>;
  /**
   * Next Cursor
   */
  next_cursor: string | null;
};

/**
 * Page[RecurrenceOut]
 */
export type PageRecurrenceOut = {
  /**
   * Items
   */
  items: Array<RecurrenceOut>;
  /**
   * Next Cursor
   */
  next_cursor: string | null;
};

/**
 * Page[SessionOut]
 */
export type PageSessionOut = {
  /**
   * Items
   */
  items: Array<SessionOut>;
  /**
   * Next Cursor
   */
  next_cursor: string | null;
};

/**
 * Preset
 */
export type Preset = "daily" | "weekdays" | "weekly" | "monthly";

/**
 * Problem
 */
export type Problem = {
  /**
   * Code
   */
  code: string;
  /**
   * Current
   */
  current?: {
    [key: string]: unknown;
  } | null;
  /**
   * Detail
   */
  detail?: string | null;
  /**
   * Schema Version
   */
  schema_version?: 1;
  /**
   * Status
   */
  status: number;
  /**
   * Title
   */
  title: string;
  /**
   * Type
   */
  type: string;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
  /**
   * Brief Md
   */
  brief_md?: string;
  /**
   * Client
   */
  client?: string | null;
  /**
   * Code Path
   */
  code_path?: string | null;
  /**
   * Deadline
   */
  deadline?: string | null;
  /**
   * Goal
   */
  goal?: string | null;
  /**
   * Links
   */
  links?: Array<ProjectLinkIn>;
  /**
   * Name
   */
  name: string;
  /**
   * Profile Name
   */
  profile_name?: string | null;
  /**
   * Repo Url
   */
  repo_url?: string | null;
  /**
   * Schema Version
   */
  schema_version?: 1;
  /**
   * Status
   */
  status?: "active" | "on_hold" | "completed";
};

/**
 * ProjectLinkIn
 */
export type ProjectLinkIn = {
  /**
   * Kind
   */
  kind: "person" | "domain" | "repo" | "coolify_app";
  /**
   * Value
   */
  value: string;
};

/**
 * ProjectOut
 */
export type ProjectOut = {
  /**
   * Archived At
   */
  archived_at: string | null;
  /**
   * Brief Md
   */
  brief_md?: string;
  /**
   * Client
   */
  client?: string | null;
  /**
   * Code Path
   */
  code_path?: string | null;
  /**
   * Deadline
   */
  deadline?: string | null;
  /**
   * Goal
   */
  goal?: string | null;
  health: Health;
  /**
   * Id
   */
  id: string;
  /**
   * Last Agent Activity At
   */
  last_agent_activity_at?: string | null;
  /**
   * Links
   */
  links?: Array<ProjectLinkIn>;
  /**
   * Name
   */
  name: string;
  /**
   * Next Milestone
   */
  next_milestone: string | null;
  /**
   * Open Count
   */
  open_count: number;
  /**
   * Profile Name
   */
  profile_name?: string | null;
  /**
   * Repo Url
   */
  repo_url?: string | null;
  /**
   * Schema Version
   */
  schema_version?: 1;
  /**
   * Sort Key
   */
  sort_key: string;
  /**
   * Status
   */
  status?: "active" | "on_hold" | "completed";
  /**
   * Subtask Threshold Min
   */
  subtask_threshold_min?: number | null;
  /**
   * Version
   */
  version: number;
};

/**
 * ProjectPatch
 *
 * Fields to change (absent: unchanged; null clears a nullable one) and the version
 * read.
 */
export type ProjectPatch = {
  /**
   * Client
   */
  client?: string | null;
  /**
   * Code Path
   */
  code_path?: string | null;
  /**
   * Deadline
   */
  deadline?: string | null;
  /**
   * Goal
   */
  goal?: string | null;
  /**
   * Links
   */
  links?: Array<ProjectLinkIn> | null;
  /**
   * Name
   */
  name?: string | null;
  /**
   * Profile Name
   */
  profile_name?: string | null;
  /**
   * Repo Url
   */
  repo_url?: string | null;
  /**
   * Status
   */
  status?: "active" | "on_hold" | "completed" | null;
  /**
   * Subtask Threshold Min
   */
  subtask_threshold_min?: number | null;
  /**
   * Version
   */
  version: number;
};

/**
 * RecurrenceIn
 *
 * `PUT /v1/tasks/{id}/recurrence`: a preset or a 5-field cron (never both), the
 * preset's weekday (weekly, 0 = Monday) or month day (monthly), the local due time and the
 * task's version. The task becomes the rule's first instance.
 */
export type RecurrenceIn = {
  /**
   * Cron
   */
  cron?: string | null;
  /**
   * Due Time
   */
  due_time?: string;
  /**
   * Month Day
   */
  month_day?: number | null;
  preset?: Preset | null;
  /**
   * Version
   */
  version: number;
  /**
   * Weekday
   */
  weekday?: number | null;
};

/**
 * RecurrenceOut
 *
 * A recurrence rule: its spec, the template's title, its latest instance and the next
 * occurrence after it (UTC).
 */
export type RecurrenceOut = {
  /**
   * Cron
   */
  cron: string | null;
  /**
   * Due Time
   */
  due_time: string;
  /**
   * Id
   */
  id: string;
  /**
   * Latest Occurrence On
   */
  latest_occurrence_on: string | null;
  /**
   * Latest Task Id
   */
  latest_task_id: string | null;
  /**
   * Month Day
   */
  month_day: number | null;
  /**
   * Next Due At
   */
  next_due_at: string | null;
  preset: Preset | null;
  /**
   * Project Id
   */
  project_id: string;
  /**
   * Title
   */
  title: string;
  /**
   * Weekday
   */
  weekday: number | null;
};

/**
 * ReorderIn
 */
export type ReorderIn = {
  /**
   * After Id
   */
  after_id?: string | null;
  /**
   * Before Id
   */
  before_id?: string | null;
  /**
   * Version
   */
  version: number;
};

/**
 * ReviewCountOut
 */
export type ReviewCountOut = {
  /**
   * Count
   */
  count: number;
};

/**
 * ReviewKindOut
 */
export type ReviewKindOut = {
  /**
   * Actions
   */
  actions: Array<string>;
  /**
   * Impact Scope
   */
  impact_scope: string;
  /**
   * Kind
   */
  kind: string;
  /**
   * Owner Module
   */
  owner_module: string;
  /**
   * Payload Schema
   */
  payload_schema: {
    [key: string]: unknown;
  };
};

/**
 * ReviewKindsOut
 */
export type ReviewKindsOut = {
  /**
   * Items
   */
  items: Array<ReviewKindOut>;
};

/**
 * RotateIn
 */
export type RotateIn = {
  /**
   * Grace Minutes
   */
  grace_minutes?: number;
};

/**
 * SessionOut
 */
export type SessionOut = {
  /**
   * Created At
   */
  created_at: string;
  /**
   * Current
   */
  current: boolean;
  /**
   * Device Label
   */
  device_label: string | null;
  /**
   * Expires At
   */
  expires_at: string;
  /**
   * Id
   */
  id: string;
  /**
   * Last Seen At
   */
  last_seen_at: string;
  /**
   * Source Ip
   */
  source_ip: string | null;
  /**
   * User Agent
   */
  user_agent: string | null;
};

/**
 * SettingSectionIn
 */
export type SettingSectionIn = {
  /**
   * Values
   */
  values: {
    [key: string]: unknown;
  };
  /**
   * Version
   */
  version?: number | null;
};

/**
 * SettingSectionOut
 */
export type SettingSectionOut = {
  /**
   * Secrets Set
   */
  secrets_set: Array<string>;
  /**
   * Section
   */
  section: string;
  /**
   * Values
   */
  values: {
    [key: string]: unknown;
  };
  /**
   * Version
   */
  version: number | null;
};

/**
 * SetupIn
 */
export type SetupIn = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Timezone
   */
  timezone?: string;
  /**
   * Workspace Name
   */
  workspace_name?: string;
};

/**
 * SetupOut
 */
export type SetupOut = {
  /**
   * Otpauth Uri
   */
  otpauth_uri: string;
  /**
   * Setup Token
   */
  setup_token: string;
};

/**
 * SetupTotpIn
 */
export type SetupTotpIn = {
  /**
   * Code
   */
  code: string;
  /**
   * Setup Token
   */
  setup_token: string;
};

/**
 * SignedInOut
 */
export type SignedInOut = {
  /**
   * User Id
   */
  user_id: string;
  /**
   * Workspace Id
   */
  workspace_id: string;
};

/**
 * Status
 */
export type Status =
  | "backlog"
  | "today"
  | "in_progress"
  | "waiting_on_human"
  | "in_review"
  | "done";

/**
 * StatusIn
 */
export type StatusIn = {
  to: Status;
  /**
   * Version
   */
  version: number;
};

/**
 * TaskContextItemOut
 *
 * A task's link to outside content: the ContextItem and what it points at.
 */
export type TaskContextItemOut = {
  /**
   * Context Item Id
   */
  context_item_id: string;
  /**
   * Id
   */
  id: string;
  /**
   * Tainted
   */
  tainted: boolean;
  /**
   * Target Id
   */
  target_id: string | null;
  /**
   * Target Type
   */
  target_type: string;
  /**
   * Target Url
   */
  target_url: string | null;
  /**
   * Task Id
   */
  task_id: string;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
  /**
   * Acceptance Criteria
   */
  acceptance_criteria?: string | null;
  /**
   * Due On
   */
  due_on?: string | null;
  /**
   * Estimate Minutes
   */
  estimate_minutes?: number | null;
  /**
   * First Action
   */
  first_action?: string | null;
  label?: Label | null;
  /**
   * Parent Id
   */
  parent_id?: string | null;
  /**
   * Priority
   */
  priority?: "low" | "normal" | "high" | "urgent";
  /**
   * Project Id
   */
  project_id: string;
  /**
   * Schema Version
   */
  schema_version?: 1;
  /**
   * Status
   */
  status?: "backlog" | "today";
  /**
   * Title
   */
  title: string;
};

/**
 * TaskOut
 */
export type TaskOut = {
  /**
   * Acceptance Criteria
   */
  acceptance_criteria: string | null;
  /**
   * Actual Minutes
   */
  actual_minutes: number | null;
  /**
   * Assigned Agent Id
   */
  assigned_agent_id: string | null;
  /**
   * Board Rank
   */
  board_rank: string;
  /**
   * Column Id
   */
  column_id: string | null;
  /**
   * Completed At
   */
  completed_at: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Due On
   */
  due_on: string | null;
  /**
   * Estimate Minutes
   */
  estimate_minutes: number | null;
  /**
   * First Action
   */
  first_action: string | null;
  /**
   * Id
   */
  id: string;
  label: Label | null;
  /**
   * Label Source
   */
  label_source: "user" | "jev" | "agent" | "fallback" | null;
  /**
   * Parent Id
   */
  parent_id: string | null;
  /**
   * Priority
   */
  priority: "low" | "normal" | "high" | "urgent";
  /**
   * Project Id
   */
  project_id: string;
  /**
   * Rollover Count
   */
  rollover_count: number;
  /**
   * Schema Version
   */
  schema_version?: 1;
  /**
   * Source
   */
  source: string;
  /**
   * Started At
   */
  started_at: string | null;
  status: Status;
  /**
   * Tainted
   */
  tainted: boolean;
  /**
   * Title
   */
  title: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Version
   */
  version: number;
};

/**
 * TaskPage
 *
 * A page of tasks and how many match the filter across every page (P0-23): the Today
 * panel shows five and says "+N more".
 */
export type TaskPage = {
  /**
   * Items
   */
  items: Array<TaskOut>;
  /**
   * Next Cursor
   */
  next_cursor: string | null;
  /**
   * Total
   */
  total: number;
};

/**
 * TaskPatch
 *
 * Fields to change (absent: unchanged; null clears a nullable one) and the version
 * read. Status changes go through `POST /status` or `/move`.
 */
export type TaskPatch = {
  /**
   * Acceptance Criteria
   */
  acceptance_criteria?: string | null;
  /**
   * Due On
   */
  due_on?: string | null;
  /**
   * Estimate Minutes
   */
  estimate_minutes?: number | null;
  /**
   * First Action
   */
  first_action?: string | null;
  label?: Label | null;
  /**
   * Priority
   */
  priority?: "low" | "normal" | "high" | "urgent" | null;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Version
   */
  version: number;
};

/**
 * TaskRecurrenceOut
 *
 * The rule as seen from one of its tasks; `version` is the task's (send it back).
 */
export type TaskRecurrenceOut = {
  /**
   * Cron
   */
  cron: string | null;
  /**
   * Due Time
   */
  due_time: string;
  /**
   * Id
   */
  id: string;
  /**
   * Latest Occurrence On
   */
  latest_occurrence_on: string | null;
  /**
   * Latest Task Id
   */
  latest_task_id: string | null;
  /**
   * Month Day
   */
  month_day: number | null;
  /**
   * Next Due At
   */
  next_due_at: string | null;
  preset: Preset | null;
  /**
   * Project Id
   */
  project_id: string;
  /**
   * Task Id
   */
  task_id: string;
  /**
   * Title
   */
  title: string;
  /**
   * Version
   */
  version: number;
  /**
   * Weekday
   */
  weekday: number | null;
};

/**
 * TotpEnrolConfirmIn
 */
export type TotpEnrolConfirmIn = {
  /**
   * Code
   */
  code: string;
  /**
   * Enrol Token
   */
  enrol_token: string;
};

/**
 * TotpEnrolIn
 */
export type TotpEnrolIn = {
  /**
   * Password
   */
  password: string;
};

/**
 * TotpEnrolOut
 */
export type TotpEnrolOut = {
  /**
   * Enrol Token
   */
  enrol_token: string;
  /**
   * Otpauth Uri
   */
  otpauth_uri: string;
};

/**
 * TotpIn
 */
export type TotpIn = {
  /**
   * Code
   */
  code: string;
  /**
   * Preauth
   */
  preauth: string;
};

/**
 * UsageRow
 */
export type UsageRow = {
  /**
   * Counter
   */
  counter: string;
  /**
   * Day
   */
  day: string;
  /**
   * Value
   */
  value: number;
};

/**
 * WorkspaceSettingsIn
 */
export type WorkspaceSettingsIn = {
  /**
   * Subtask Threshold Min
   */
  subtask_threshold_min?: number | null;
  /**
   * Timezone
   */
  timezone?: string | null;
  /**
   * Version
   */
  version: number;
};

/**
 * WorkspaceSettingsOut
 */
export type WorkspaceSettingsOut = {
  /**
   * Subtask Threshold Min
   */
  subtask_threshold_min: number;
  /**
   * Timezone
   */
  timezone: string;
  /**
   * Version
   */
  version: number;
};

/**
 * VersionIn
 */
export type TumnisCoreDeadletterVersionIn = {
  /**
   * Version
   */
  version: number;
};

/**
 * VersionIn
 */
export type TumnisModulesProjectsRouterVersionIn = {
  /**
   * Version
   */
  version: number;
};

export type HealthLiveData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health/live";
};

export type HealthLiveResponses = {
  /**
   * Response Health Live
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthLiveResponse = HealthLiveResponses[keyof HealthLiveResponses];

export type HealthReadyData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health/ready";
};

export type HealthReadyErrors = {
  /**
   * Down: a critical check failed
   */
  503: unknown;
};

export type HealthReadyResponses = {
  /**
   * Ready (`ok`) or `degraded`: a non-critical check failed
   */
  200: unknown;
};

export type AuditListAuditData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Action
     */
    action?: string | null;
    /**
     * Actor Type
     */
    actor_type?: "user" | "api_key" | "task_token" | "device" | "system" | null;
    /**
     * From
     */
    from?: string | null;
    /**
     * To
     */
    to?: string | null;
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/v1/audit";
};

export type AuditListAuditErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuditListAuditError =
  AuditListAuditErrors[keyof AuditListAuditErrors];

export type AuditListAuditResponses = {
  /**
   * Successful Response
   */
  200: PageAuditEntry;
};

export type AuditListAuditResponse =
  AuditListAuditResponses[keyof AuditListAuditResponses];

export type AuditExportAuditCsvData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Action
     */
    action?: string | null;
    /**
     * Actor Type
     */
    actor_type?: "user" | "api_key" | "task_token" | "device" | "system" | null;
    /**
     * From
     */
    from?: string | null;
    /**
     * To
     */
    to?: string | null;
  };
  url: "/v1/audit.csv";
};

export type AuditExportAuditCsvErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuditExportAuditCsvError =
  AuditExportAuditCsvErrors[keyof AuditExportAuditCsvErrors];

export type AuditExportAuditCsvResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthGetAccountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/auth/account";
};

export type AuthGetAccountErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthGetAccountError =
  AuthGetAccountErrors[keyof AuthGetAccountErrors];

export type AuthGetAccountResponses = {
  /**
   * Successful Response
   */
  200: AccountOut;
};

export type AuthGetAccountResponse =
  AuthGetAccountResponses[keyof AuthGetAccountResponses];

export type AuthLoginData = {
  body: LoginIn;
  path?: never;
  query?: never;
  url: "/v1/auth/login";
};

export type AuthLoginErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
  /**
   * Successful Response
   */
  200: LoginOut;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/auth/logout";
};

export type AuthLogoutErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthLogoutError = AuthLogoutErrors[keyof AuthLogoutErrors];

export type AuthLogoutResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthSignOutOtherDevicesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/auth/sessions";
};

export type AuthSignOutOtherDevicesErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthSignOutOtherDevicesError =
  AuthSignOutOtherDevicesErrors[keyof AuthSignOutOtherDevicesErrors];

export type AuthSignOutOtherDevicesResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type AuthSignOutOtherDevicesResponse =
  AuthSignOutOtherDevicesResponses[keyof AuthSignOutOtherDevicesResponses];

export type AuthListSessionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/v1/auth/sessions";
};

export type AuthListSessionsErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthListSessionsError =
  AuthListSessionsErrors[keyof AuthListSessionsErrors];

export type AuthListSessionsResponses = {
  /**
   * Successful Response
   */
  200: PageSessionOut;
};

export type AuthListSessionsResponse =
  AuthListSessionsResponses[keyof AuthListSessionsResponses];

export type AuthRevokeSessionData = {
  body?: never;
  path: {
    /**
     * Session Id
     */
    session_id: string;
  };
  query?: never;
  url: "/v1/auth/sessions/{session_id}";
};

export type AuthRevokeSessionErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthRevokeSessionError =
  AuthRevokeSessionErrors[keyof AuthRevokeSessionErrors];

export type AuthRevokeSessionResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type AuthRevokeSessionResponse =
  AuthRevokeSessionResponses[keyof AuthRevokeSessionResponses];

export type AuthTotpData = {
  body: TotpIn;
  path?: never;
  query?: never;
  url: "/v1/auth/totp";
};

export type AuthTotpErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthTotpError = AuthTotpErrors[keyof AuthTotpErrors];

export type AuthTotpResponses = {
  /**
   * Successful Response
   */
  200: SignedInOut;
};

export type AuthTotpResponse = AuthTotpResponses[keyof AuthTotpResponses];

export type AuthStartTotpEnrolmentData = {
  body: TotpEnrolIn;
  path?: never;
  query?: never;
  url: "/v1/auth/totp/enrol";
};

export type AuthStartTotpEnrolmentErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthStartTotpEnrolmentError =
  AuthStartTotpEnrolmentErrors[keyof AuthStartTotpEnrolmentErrors];

export type AuthStartTotpEnrolmentResponses = {
  /**
   * Successful Response
   */
  200: TotpEnrolOut;
};

export type AuthStartTotpEnrolmentResponse =
  AuthStartTotpEnrolmentResponses[keyof AuthStartTotpEnrolmentResponses];

export type AuthConfirmTotpEnrolmentData = {
  body: TotpEnrolConfirmIn;
  path?: never;
  query?: never;
  url: "/v1/auth/totp/enrol/confirm";
};

export type AuthConfirmTotpEnrolmentErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthConfirmTotpEnrolmentError =
  AuthConfirmTotpEnrolmentErrors[keyof AuthConfirmTotpEnrolmentErrors];

export type AuthConfirmTotpEnrolmentResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type AuthConfirmTotpEnrolmentResponse =
  AuthConfirmTotpEnrolmentResponses[keyof AuthConfirmTotpEnrolmentResponses];

export type DeadLettersGetDeadLettersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status
     */
    status?: string;
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/v1/dead-letters";
};

export type DeadLettersGetDeadLettersErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type DeadLettersGetDeadLettersError =
  DeadLettersGetDeadLettersErrors[keyof DeadLettersGetDeadLettersErrors];

export type DeadLettersGetDeadLettersResponses = {
  /**
   * Successful Response
   */
  200: PageDeadLetterOut;
};

export type DeadLettersGetDeadLettersResponse =
  DeadLettersGetDeadLettersResponses[keyof DeadLettersGetDeadLettersResponses];

export type DeadLettersPostDiscardData = {
  body: TumnisCoreDeadletterVersionIn;
  path: {
    /**
     * Dead Letter Id
     */
    dead_letter_id: string;
  };
  query?: never;
  url: "/v1/dead-letters/{dead_letter_id}/discard";
};

export type DeadLettersPostDiscardErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type DeadLettersPostDiscardError =
  DeadLettersPostDiscardErrors[keyof DeadLettersPostDiscardErrors];

export type DeadLettersPostDiscardResponses = {
  /**
   * Successful Response
   */
  200: DeadLetterOut;
};

export type DeadLettersPostDiscardResponse =
  DeadLettersPostDiscardResponses[keyof DeadLettersPostDiscardResponses];

export type DeadLettersPostRetryData = {
  body: TumnisCoreDeadletterVersionIn;
  path: {
    /**
     * Dead Letter Id
     */
    dead_letter_id: string;
  };
  query?: never;
  url: "/v1/dead-letters/{dead_letter_id}/retry";
};

export type DeadLettersPostRetryErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type DeadLettersPostRetryError =
  DeadLettersPostRetryErrors[keyof DeadLettersPostRetryErrors];

export type DeadLettersPostRetryResponses = {
  /**
   * Successful Response
   */
  200: DeadLetterOut;
};

export type DeadLettersPostRetryResponse =
  DeadLettersPostRetryResponses[keyof DeadLettersPostRetryResponses];

export type AuthListKeysData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/v1/keys";
};

export type AuthListKeysErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthListKeysError = AuthListKeysErrors[keyof AuthListKeysErrors];

export type AuthListKeysResponses = {
  /**
   * Successful Response
   */
  200: PageKeyOut;
};

export type AuthListKeysResponse =
  AuthListKeysResponses[keyof AuthListKeysResponses];

export type AuthCreateKeyData = {
  body: KeyIn;
  path?: never;
  query?: never;
  url: "/v1/keys";
};

export type AuthCreateKeyErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthCreateKeyError = AuthCreateKeyErrors[keyof AuthCreateKeyErrors];

export type AuthCreateKeyResponses = {
  /**
   * Successful Response
   */
  201: KeyCreated;
};

export type AuthCreateKeyResponse =
  AuthCreateKeyResponses[keyof AuthCreateKeyResponses];

export type AuthRevokeKeyData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/v1/keys/{id}";
};

export type AuthRevokeKeyErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthRevokeKeyError = AuthRevokeKeyErrors[keyof AuthRevokeKeyErrors];

export type AuthRevokeKeyResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type AuthRevokeKeyResponse =
  AuthRevokeKeyResponses[keyof AuthRevokeKeyResponses];

export type AuthRotateKeyData = {
  body?: RotateIn;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/v1/keys/{id}/rotate";
};

export type AuthRotateKeyErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthRotateKeyError = AuthRotateKeyErrors[keyof AuthRotateKeyErrors];

export type AuthRotateKeyResponses = {
  /**
   * Successful Response
   */
  200: KeyCreated;
};

export type AuthRotateKeyResponse =
  AuthRotateKeyResponses[keyof AuthRotateKeyResponses];

export type ProjectsListProjectsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Include Archived
     */
    include_archived?: boolean;
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/v1/projects";
};

export type ProjectsListProjectsErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type ProjectsListProjectsError =
  ProjectsListProjectsErrors[keyof ProjectsListProjectsErrors];

export type ProjectsListProjectsResponses = {
  /**
   * Successful Response
   */
  200: PageProjectOut;
};

export type ProjectsListProjectsResponse =
  ProjectsListProjectsResponses[keyof ProjectsListProjectsResponses];

export type ProjectsCreateProjectData = {
  body: ProjectCreate;
  path?: never;
  query?: never;
  url: "/v1/projects";
};

export type ProjectsCreateProjectErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type ProjectsCreateProjectError =
  ProjectsCreateProjectErrors[keyof ProjectsCreateProjectErrors];

export type ProjectsCreateProjectResponses = {
  /**
   * Successful Response
   */
  201: ProjectOut;
};

export type ProjectsCreateProjectResponse =
  ProjectsCreateProjectResponses[keyof ProjectsCreateProjectResponses];

export type ProjectsGetProjectData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/v1/projects/{project_id}";
};

export type ProjectsGetProjectErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type ProjectsGetProjectError =
  ProjectsGetProjectErrors[keyof ProjectsGetProjectErrors];

export type ProjectsGetProjectResponses = {
  /**
   * Successful Response
   */
  200: ProjectOut;
};

export type ProjectsGetProjectResponse =
  ProjectsGetProjectResponses[keyof ProjectsGetProjectResponses];

export type ProjectsUpdateProjectData = {
  body: ProjectPatch;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/v1/projects/{project_id}";
};

export type ProjectsUpdateProjectErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type ProjectsUpdateProjectError =
  ProjectsUpdateProjectErrors[keyof ProjectsUpdateProjectErrors];

export type ProjectsUpdateProjectResponses = {
  /**
   * Successful Response
   */
  200: ProjectOut;
};

export type ProjectsUpdateProjectResponse =
  ProjectsUpdateProjectResponses[keyof ProjectsUpdateProjectResponses];

export type ProjectsArchiveProjectData = {
  body: TumnisModulesProjectsRouterVersionIn;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/v1/projects/{project_id}/archive";
};

export type ProjectsArchiveProjectErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type ProjectsArchiveProjectError =
  ProjectsArchiveProjectErrors[keyof ProjectsArchiveProjectErrors];

export type ProjectsArchiveProjectResponses = {
  /**
   * Successful Response
   */
  200: ProjectOut;
};

export type ProjectsArchiveProjectResponse =
  ProjectsArchiveProjectResponses[keyof ProjectsArchiveProjectResponses];

export type TasksGetBoardData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/v1/projects/{project_id}/board";
};

export type TasksGetBoardErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksGetBoardError = TasksGetBoardErrors[keyof TasksGetBoardErrors];

export type TasksGetBoardResponses = {
  /**
   * Successful Response
   */
  200: BoardOut;
};

export type TasksGetBoardResponse =
  TasksGetBoardResponses[keyof TasksGetBoardResponses];

export type TasksGetColumnsData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/v1/projects/{project_id}/columns";
};

export type TasksGetColumnsErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksGetColumnsError =
  TasksGetColumnsErrors[keyof TasksGetColumnsErrors];

export type TasksGetColumnsResponses = {
  /**
   * Successful Response
   */
  200: ColumnsOut;
};

export type TasksGetColumnsResponse =
  TasksGetColumnsResponses[keyof TasksGetColumnsResponses];

export type TasksPutColumnsData = {
  body: ColumnsIn;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/v1/projects/{project_id}/columns";
};

export type TasksPutColumnsErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksPutColumnsError =
  TasksPutColumnsErrors[keyof TasksPutColumnsErrors];

export type TasksPutColumnsResponses = {
  /**
   * Successful Response
   */
  200: ColumnsOut;
};

export type TasksPutColumnsResponse =
  TasksPutColumnsResponses[keyof TasksPutColumnsResponses];

export type ProjectsReorderProjectData = {
  body: ReorderIn;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/v1/projects/{project_id}/reorder";
};

export type ProjectsReorderProjectErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type ProjectsReorderProjectError =
  ProjectsReorderProjectErrors[keyof ProjectsReorderProjectErrors];

export type ProjectsReorderProjectResponses = {
  /**
   * Successful Response
   */
  200: ProjectOut;
};

export type ProjectsReorderProjectResponse =
  ProjectsReorderProjectResponses[keyof ProjectsReorderProjectResponses];

export type ProjectsUnarchiveProjectData = {
  body: TumnisModulesProjectsRouterVersionIn;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/v1/projects/{project_id}/unarchive";
};

export type ProjectsUnarchiveProjectErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type ProjectsUnarchiveProjectError =
  ProjectsUnarchiveProjectErrors[keyof ProjectsUnarchiveProjectErrors];

export type ProjectsUnarchiveProjectResponses = {
  /**
   * Successful Response
   */
  200: ProjectOut;
};

export type ProjectsUnarchiveProjectResponse =
  ProjectsUnarchiveProjectResponses[keyof ProjectsUnarchiveProjectResponses];

export type TasksListRecurrenceData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Project Id
     */
    project_id?: string | null;
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/v1/recurrence";
};

export type TasksListRecurrenceErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksListRecurrenceError =
  TasksListRecurrenceErrors[keyof TasksListRecurrenceErrors];

export type TasksListRecurrenceResponses = {
  /**
   * Successful Response
   */
  200: PageRecurrenceOut;
};

export type TasksListRecurrenceResponse =
  TasksListRecurrenceResponses[keyof TasksListRecurrenceResponses];

export type TasksGetReviewCountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/review/count";
};

export type TasksGetReviewCountErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksGetReviewCountError =
  TasksGetReviewCountErrors[keyof TasksGetReviewCountErrors];

export type TasksGetReviewCountResponses = {
  /**
   * Successful Response
   */
  200: ReviewCountOut;
};

export type TasksGetReviewCountResponse =
  TasksGetReviewCountResponses[keyof TasksGetReviewCountResponses];

export type TasksListReviewKindsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/review/kinds";
};

export type TasksListReviewKindsErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksListReviewKindsError =
  TasksListReviewKindsErrors[keyof TasksListReviewKindsErrors];

export type TasksListReviewKindsResponses = {
  /**
   * Successful Response
   */
  200: ReviewKindsOut;
};

export type TasksListReviewKindsResponse =
  TasksListReviewKindsResponses[keyof TasksListReviewKindsResponses];

export type SettingsListModulesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/settings/modules";
};

export type SettingsListModulesErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type SettingsListModulesError =
  SettingsListModulesErrors[keyof SettingsListModulesErrors];

export type SettingsListModulesResponses = {
  /**
   * Successful Response
   */
  200: ModuleFlagsOut;
};

export type SettingsListModulesResponse =
  SettingsListModulesResponses[keyof SettingsListModulesResponses];

export type SettingsSetModuleData = {
  body: ModuleFlagIn;
  path?: never;
  query?: never;
  url: "/v1/settings/modules";
};

export type SettingsSetModuleErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type SettingsSetModuleError =
  SettingsSetModuleErrors[keyof SettingsSetModuleErrors];

export type SettingsSetModuleResponses = {
  /**
   * Successful Response
   */
  200: ModuleFlagOut;
};

export type SettingsSetModuleResponse =
  SettingsSetModuleResponses[keyof SettingsSetModuleResponses];

export type SettingsGetWorkspaceSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/settings/workspace";
};

export type SettingsGetWorkspaceSettingsErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type SettingsGetWorkspaceSettingsError =
  SettingsGetWorkspaceSettingsErrors[keyof SettingsGetWorkspaceSettingsErrors];

export type SettingsGetWorkspaceSettingsResponses = {
  /**
   * Successful Response
   */
  200: WorkspaceSettingsOut;
};

export type SettingsGetWorkspaceSettingsResponse =
  SettingsGetWorkspaceSettingsResponses[keyof SettingsGetWorkspaceSettingsResponses];

export type SettingsPutWorkspaceSettingsData = {
  body: WorkspaceSettingsIn;
  path?: never;
  query?: never;
  url: "/v1/settings/workspace";
};

export type SettingsPutWorkspaceSettingsErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type SettingsPutWorkspaceSettingsError =
  SettingsPutWorkspaceSettingsErrors[keyof SettingsPutWorkspaceSettingsErrors];

export type SettingsPutWorkspaceSettingsResponses = {
  /**
   * Successful Response
   */
  200: WorkspaceSettingsOut;
};

export type SettingsPutWorkspaceSettingsResponse =
  SettingsPutWorkspaceSettingsResponses[keyof SettingsPutWorkspaceSettingsResponses];

export type SettingsGetSectionData = {
  body?: never;
  path: {
    /**
     * Section
     */
    section: string;
  };
  query?: never;
  url: "/v1/settings/{section}";
};

export type SettingsGetSectionErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type SettingsGetSectionError =
  SettingsGetSectionErrors[keyof SettingsGetSectionErrors];

export type SettingsGetSectionResponses = {
  /**
   * Successful Response
   */
  200: SettingSectionOut;
};

export type SettingsGetSectionResponse =
  SettingsGetSectionResponses[keyof SettingsGetSectionResponses];

export type SettingsPutSectionData = {
  body: SettingSectionIn;
  path: {
    /**
     * Section
     */
    section: string;
  };
  query?: never;
  url: "/v1/settings/{section}";
};

export type SettingsPutSectionErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type SettingsPutSectionError =
  SettingsPutSectionErrors[keyof SettingsPutSectionErrors];

export type SettingsPutSectionResponses = {
  /**
   * Successful Response
   */
  200: SettingSectionOut;
};

export type SettingsPutSectionResponse =
  SettingsPutSectionResponses[keyof SettingsPutSectionResponses];

export type AuthSetupData = {
  body: SetupIn;
  path?: never;
  query?: never;
  url: "/v1/setup";
};

export type AuthSetupErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthSetupError = AuthSetupErrors[keyof AuthSetupErrors];

export type AuthSetupResponses = {
  /**
   * Successful Response
   */
  201: SetupOut;
};

export type AuthSetupResponse = AuthSetupResponses[keyof AuthSetupResponses];

export type AuthSetupTotpData = {
  body: SetupTotpIn;
  path?: never;
  query?: never;
  url: "/v1/setup/totp";
};

export type AuthSetupTotpErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuthSetupTotpError = AuthSetupTotpErrors[keyof AuthSetupTotpErrors];

export type AuthSetupTotpResponses = {
  /**
   * Successful Response
   */
  200: SignedInOut;
};

export type AuthSetupTotpResponse =
  AuthSetupTotpResponses[keyof AuthSetupTotpResponses];

export type TasksListTasksData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Project Id
     */
    project_id?: string | null;
    /**
     * Status
     */
    status?: Status | null;
    /**
     * Order
     */
    order?: "created" | "today";
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/v1/tasks";
};

export type TasksListTasksErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksListTasksError =
  TasksListTasksErrors[keyof TasksListTasksErrors];

export type TasksListTasksResponses = {
  /**
   * Successful Response
   */
  200: TaskPage;
};

export type TasksListTasksResponse =
  TasksListTasksResponses[keyof TasksListTasksResponses];

export type TasksCreateTaskData = {
  body: TaskCreate;
  path?: never;
  query?: never;
  url: "/v1/tasks";
};

export type TasksCreateTaskErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksCreateTaskError =
  TasksCreateTaskErrors[keyof TasksCreateTaskErrors];

export type TasksCreateTaskResponses = {
  /**
   * Successful Response
   */
  201: TaskOut;
};

export type TasksCreateTaskResponse =
  TasksCreateTaskResponses[keyof TasksCreateTaskResponses];

export type TasksGetTaskData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}";
};

export type TasksGetTaskErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksGetTaskError = TasksGetTaskErrors[keyof TasksGetTaskErrors];

export type TasksGetTaskResponses = {
  /**
   * Successful Response
   */
  200: TaskOut;
};

export type TasksGetTaskResponse =
  TasksGetTaskResponses[keyof TasksGetTaskResponses];

export type TasksUpdateTaskData = {
  body: TaskPatch;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}";
};

export type TasksUpdateTaskErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksUpdateTaskError =
  TasksUpdateTaskErrors[keyof TasksUpdateTaskErrors];

export type TasksUpdateTaskResponses = {
  /**
   * Successful Response
   */
  200: TaskOut;
};

export type TasksUpdateTaskResponse =
  TasksUpdateTaskResponses[keyof TasksUpdateTaskResponses];

export type TasksAddCommentData = {
  body: CommentIn;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}/comments";
};

export type TasksAddCommentErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksAddCommentError =
  TasksAddCommentErrors[keyof TasksAddCommentErrors];

export type TasksAddCommentResponses = {
  /**
   * Successful Response
   */
  201: CommentOut;
};

export type TasksAddCommentResponse =
  TasksAddCommentResponses[keyof TasksAddCommentResponses];

export type TasksLinkContextItemData = {
  body: ContextItemIn;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}/context-items";
};

export type TasksLinkContextItemErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksLinkContextItemError =
  TasksLinkContextItemErrors[keyof TasksLinkContextItemErrors];

export type TasksLinkContextItemResponses = {
  /**
   * Successful Response
   */
  201: TaskContextItemOut;
};

export type TasksLinkContextItemResponse =
  TasksLinkContextItemResponses[keyof TasksLinkContextItemResponses];

export type TasksMoveTaskData = {
  body: MoveIn;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}/move";
};

export type TasksMoveTaskErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksMoveTaskError = TasksMoveTaskErrors[keyof TasksMoveTaskErrors];

export type TasksMoveTaskResponses = {
  /**
   * Successful Response
   */
  200: TaskOut;
};

export type TasksMoveTaskResponse =
  TasksMoveTaskResponses[keyof TasksMoveTaskResponses];

export type TasksDeleteRecurrenceData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query: {
    /**
     * Version
     */
    version: number;
  };
  url: "/v1/tasks/{task_id}/recurrence";
};

export type TasksDeleteRecurrenceErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksDeleteRecurrenceError =
  TasksDeleteRecurrenceErrors[keyof TasksDeleteRecurrenceErrors];

export type TasksDeleteRecurrenceResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type TasksDeleteRecurrenceResponse =
  TasksDeleteRecurrenceResponses[keyof TasksDeleteRecurrenceResponses];

export type TasksGetRecurrenceData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}/recurrence";
};

export type TasksGetRecurrenceErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksGetRecurrenceError =
  TasksGetRecurrenceErrors[keyof TasksGetRecurrenceErrors];

export type TasksGetRecurrenceResponses = {
  /**
   * Successful Response
   */
  200: TaskRecurrenceOut;
};

export type TasksGetRecurrenceResponse =
  TasksGetRecurrenceResponses[keyof TasksGetRecurrenceResponses];

export type TasksPutRecurrenceData = {
  body: RecurrenceIn;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}/recurrence";
};

export type TasksPutRecurrenceErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksPutRecurrenceError =
  TasksPutRecurrenceErrors[keyof TasksPutRecurrenceErrors];

export type TasksPutRecurrenceResponses = {
  /**
   * Successful Response
   */
  200: TaskRecurrenceOut;
};

export type TasksPutRecurrenceResponse =
  TasksPutRecurrenceResponses[keyof TasksPutRecurrenceResponses];

export type TasksChangeStatusData = {
  body: StatusIn;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}/status";
};

export type TasksChangeStatusErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type TasksChangeStatusError =
  TasksChangeStatusErrors[keyof TasksChangeStatusErrors];

export type TasksChangeStatusResponses = {
  /**
   * Successful Response
   */
  200: TaskOut;
};

export type TasksChangeStatusResponse =
  TasksChangeStatusResponses[keyof TasksChangeStatusResponses];

export type UsageGetUsageData = {
  body?: never;
  path?: never;
  query: {
    /**
     * From
     */
    from: string;
    /**
     * To
     */
    to: string;
  };
  url: "/v1/usage";
};

export type UsageGetUsageErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated (`unauthenticated`, `session_expired`)
   */
  401: Problem;
  /**
   * Forbidden (`csrf_failed`, `bad_origin`, `session_required`, `insufficient_scope`, ...)
   */
  403: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type UsageGetUsageError = UsageGetUsageErrors[keyof UsageGetUsageErrors];

export type UsageGetUsageResponses = {
  /**
   * Response Usage Get Usage
   *
   * Successful Response
   */
  200: Array<UsageRow>;
};

export type UsageGetUsageResponse =
  UsageGetUsageResponses[keyof UsageGetUsageResponses];
