// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AuditEntry
 */
export type AuditEntry = {
  /**
   * Action
   */
  action: string;
  /**
   * Actor Id
   */
  actor_id: string | null;
  /**
   * Actor Type
   */
  actor_type: string;
  /**
   * Correlation Id
   */
  correlation_id: string | null;
  /**
   * Details
   */
  details: {
    [key: string]: unknown;
  };
  /**
   * Id
   */
  id: string;
  /**
   * Occurred At
   */
  occurred_at: string;
  /**
   * Reason
   */
  reason: string | null;
  /**
   * Seq
   */
  seq: number;
  /**
   * Source Ip
   */
  source_ip: string | null;
  /**
   * Target Id
   */
  target_id: string | null;
  /**
   * Target Type
   */
  target_type: string | null;
  /**
   * User Agent
   */
  user_agent: string | null;
};

/**
 * DeadLetterOut
 */
export type DeadLetterOut = {
  /**
   * Attempts
   */
  attempts: number;
  /**
   * Error
   */
  error: string;
  /**
   * Event Id
   */
  event_id: string;
  /**
   * Event Name
   */
  event_name: string;
  /**
   * Id
   */
  id: string;
  /**
   * Last At
   */
  last_at: string;
  /**
   * Retries
   */
  retries: number;
  /**
   * Status
   */
  status: string;
  /**
   * Subscriber
   */
  subscriber: string;
  /**
   * Version
   */
  version: number;
};

/**
 * Page[AuditEntry]
 */
export type PageAuditEntry = {
  /**
   * Items
   */
  items: Array<AuditEntry>;
  /**
   * Next Cursor
   */
  next_cursor: string | null;
};

/**
 * Page[DeadLetterOut]
 */
export type PageDeadLetterOut = {
  /**
   * Items
   */
  items: Array<DeadLetterOut>;
  /**
   * Next Cursor
   */
  next_cursor: string | null;
};

/**
 * Problem
 */
export type Problem = {
  /**
   * Code
   */
  code: string;
  /**
   * Current
   */
  current?: {
    [key: string]: unknown;
  } | null;
  /**
   * Detail
   */
  detail?: string | null;
  /**
   * Schema Version
   */
  schema_version?: 1;
  /**
   * Status
   */
  status: number;
  /**
   * Title
   */
  title: string;
  /**
   * Type
   */
  type: string;
};

/**
 * UsageRow
 */
export type UsageRow = {
  /**
   * Counter
   */
  counter: string;
  /**
   * Day
   */
  day: string;
  /**
   * Value
   */
  value: number;
};

/**
 * VersionIn
 */
export type VersionIn = {
  /**
   * Version
   */
  version: number;
};

/**
 * WorkspaceSettingsIn
 */
export type WorkspaceSettingsIn = {
  /**
   * Subtask Threshold Min
   */
  subtask_threshold_min?: number | null;
  /**
   * Timezone
   */
  timezone?: string | null;
  /**
   * Version
   */
  version: number;
};

/**
 * WorkspaceSettingsOut
 */
export type WorkspaceSettingsOut = {
  /**
   * Subtask Threshold Min
   */
  subtask_threshold_min: number;
  /**
   * Timezone
   */
  timezone: string;
  /**
   * Version
   */
  version: number;
};

export type HealthLiveData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health/live";
};

export type HealthLiveResponses = {
  /**
   * Response Health Live
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthLiveResponse = HealthLiveResponses[keyof HealthLiveResponses];

export type HealthReadyData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health/ready";
};

export type HealthReadyResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuditListAuditData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Action
     */
    action?: string | null;
    /**
     * Actor Type
     */
    actor_type?: "user" | "api_key" | "task_token" | "device" | "system" | null;
    /**
     * From
     */
    from?: string | null;
    /**
     * To
     */
    to?: string | null;
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/v1/audit";
};

export type AuditListAuditErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated
   */
  401: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuditListAuditError =
  AuditListAuditErrors[keyof AuditListAuditErrors];

export type AuditListAuditResponses = {
  /**
   * Successful Response
   */
  200: PageAuditEntry;
};

export type AuditListAuditResponse =
  AuditListAuditResponses[keyof AuditListAuditResponses];

export type AuditExportAuditCsvData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Action
     */
    action?: string | null;
    /**
     * Actor Type
     */
    actor_type?: "user" | "api_key" | "task_token" | "device" | "system" | null;
    /**
     * From
     */
    from?: string | null;
    /**
     * To
     */
    to?: string | null;
  };
  url: "/v1/audit.csv";
};

export type AuditExportAuditCsvErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated
   */
  401: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type AuditExportAuditCsvError =
  AuditExportAuditCsvErrors[keyof AuditExportAuditCsvErrors];

export type AuditExportAuditCsvResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeadLettersGetDeadLettersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status
     */
    status?: string;
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/v1/dead-letters";
};

export type DeadLettersGetDeadLettersErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated
   */
  401: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type DeadLettersGetDeadLettersError =
  DeadLettersGetDeadLettersErrors[keyof DeadLettersGetDeadLettersErrors];

export type DeadLettersGetDeadLettersResponses = {
  /**
   * Successful Response
   */
  200: PageDeadLetterOut;
};

export type DeadLettersGetDeadLettersResponse =
  DeadLettersGetDeadLettersResponses[keyof DeadLettersGetDeadLettersResponses];

export type DeadLettersPostDiscardData = {
  body: VersionIn;
  path: {
    /**
     * Dead Letter Id
     */
    dead_letter_id: string;
  };
  query?: never;
  url: "/v1/dead-letters/{dead_letter_id}/discard";
};

export type DeadLettersPostDiscardErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated
   */
  401: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type DeadLettersPostDiscardError =
  DeadLettersPostDiscardErrors[keyof DeadLettersPostDiscardErrors];

export type DeadLettersPostDiscardResponses = {
  /**
   * Successful Response
   */
  200: DeadLetterOut;
};

export type DeadLettersPostDiscardResponse =
  DeadLettersPostDiscardResponses[keyof DeadLettersPostDiscardResponses];

export type DeadLettersPostRetryData = {
  body: VersionIn;
  path: {
    /**
     * Dead Letter Id
     */
    dead_letter_id: string;
  };
  query?: never;
  url: "/v1/dead-letters/{dead_letter_id}/retry";
};

export type DeadLettersPostRetryErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated
   */
  401: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type DeadLettersPostRetryError =
  DeadLettersPostRetryErrors[keyof DeadLettersPostRetryErrors];

export type DeadLettersPostRetryResponses = {
  /**
   * Successful Response
   */
  200: DeadLetterOut;
};

export type DeadLettersPostRetryResponse =
  DeadLettersPostRetryResponses[keyof DeadLettersPostRetryResponses];

export type SettingsGetWorkspaceSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/settings/workspace";
};

export type SettingsGetWorkspaceSettingsErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated
   */
  401: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type SettingsGetWorkspaceSettingsError =
  SettingsGetWorkspaceSettingsErrors[keyof SettingsGetWorkspaceSettingsErrors];

export type SettingsGetWorkspaceSettingsResponses = {
  /**
   * Successful Response
   */
  200: WorkspaceSettingsOut;
};

export type SettingsGetWorkspaceSettingsResponse =
  SettingsGetWorkspaceSettingsResponses[keyof SettingsGetWorkspaceSettingsResponses];

export type SettingsPutWorkspaceSettingsData = {
  body: WorkspaceSettingsIn;
  path?: never;
  query?: never;
  url: "/v1/settings/workspace";
};

export type SettingsPutWorkspaceSettingsErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated
   */
  401: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type SettingsPutWorkspaceSettingsError =
  SettingsPutWorkspaceSettingsErrors[keyof SettingsPutWorkspaceSettingsErrors];

export type SettingsPutWorkspaceSettingsResponses = {
  /**
   * Successful Response
   */
  200: WorkspaceSettingsOut;
};

export type SettingsPutWorkspaceSettingsResponse =
  SettingsPutWorkspaceSettingsResponses[keyof SettingsPutWorkspaceSettingsResponses];

export type UsageGetUsageData = {
  body?: never;
  path?: never;
  query: {
    /**
     * From
     */
    from: string;
    /**
     * To
     */
    to: string;
  };
  url: "/v1/usage";
};

export type UsageGetUsageErrors = {
  /**
   * Bad request (`idempotency_key_required`, `invalid_cursor`, ...)
   */
  400: Problem;
  /**
   * Unauthenticated
   */
  401: Problem;
  /**
   * Not found
   */
  404: Problem;
  /**
   * Conflict (`stale_version` with `current`)
   */
  409: Problem;
  /**
   * Body too large
   */
  413: Problem;
  /**
   * Validation error or `idempotency_mismatch`
   */
  422: Problem;
  /**
   * Rate limited (`Retry-After`)
   */
  429: Problem;
};

export type UsageGetUsageError = UsageGetUsageErrors[keyof UsageGetUsageErrors];

export type UsageGetUsageResponses = {
  /**
   * Response Usage Get Usage
   *
   * Successful Response
   */
  200: Array<UsageRow>;
};

export type UsageGetUsageResponse =
  UsageGetUsageResponses[keyof UsageGetUsageResponses];
