// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * AuditEntry
 */
export const zAuditEntry = z.object({
  action: z.string(),
  actor_id: z.uuid().nullable(),
  actor_type: z.string(),
  correlation_id: z.string().nullable(),
  details: z.record(z.string(), z.unknown()),
  id: z.uuid(),
  occurred_at: z.iso.datetime(),
  reason: z.string().nullable(),
  seq: z.int(),
  source_ip: z.string().nullable(),
  target_id: z.uuid().nullable(),
  target_type: z.string().nullable(),
  user_agent: z.string().nullable(),
});

/**
 * DeadLetterOut
 */
export const zDeadLetterOut = z.object({
  attempts: z.int(),
  error: z.string(),
  event_id: z.uuid(),
  event_name: z.string(),
  id: z.uuid(),
  last_at: z.iso.datetime(),
  retries: z.int(),
  status: z.string(),
  subscriber: z.string(),
  version: z.int(),
});

/**
 * Health
 */
export const zHealth = z.enum(["blocked", "at_risk", "on_track"]);

/**
 * KeyCreated
 */
export const zKeyCreated = z.object({
  created_at: z.iso.datetime(),
  expires_at: z.iso.datetime().nullable(),
  id: z.uuid(),
  key: z.string(),
  last_used_at: z.iso.datetime().nullable(),
  name: z.string(),
  prefix: z.string(),
  project_ids: z.array(z.uuid()).nullable(),
  revoked_at: z.iso.datetime().nullable(),
  scopes: z.array(z.string()),
});

/**
 * KeyIn
 */
export const zKeyIn = z.object({
  expires_at: z.iso.datetime().nullish(),
  name: z.string().min(1).max(200),
  project_ids: z.array(z.uuid()).max(200).nullish(),
  scopes: z.array(z.string()).max(32),
});

/**
 * KeyOut
 */
export const zKeyOut = z.object({
  created_at: z.iso.datetime(),
  expires_at: z.iso.datetime().nullable(),
  id: z.uuid(),
  last_used_at: z.iso.datetime().nullable(),
  name: z.string(),
  prefix: z.string(),
  project_ids: z.array(z.uuid()).nullable(),
  revoked_at: z.iso.datetime().nullable(),
  scopes: z.array(z.string()),
});

/**
 * LoginIn
 *
 * `provider` picks the sign-in provider; the other string fields are its credentials
 * (`email` and `password` for `local_password`).
 */
export const zLoginIn = z.object({
  email: z.string().max(254).nullish(),
  password: z.string().max(1024).nullish(),
  provider: z.string().optional().default("local_password"),
});

/**
 * LoginOut
 */
export const zLoginOut = z.object({
  preauth: z.string(),
  step: z.literal("totp").optional().default("totp"),
});

/**
 * Page[AuditEntry]
 */
export const zPageAuditEntry = z.object({
  items: z.array(zAuditEntry),
  next_cursor: z.string().nullable(),
});

/**
 * Page[DeadLetterOut]
 */
export const zPageDeadLetterOut = z.object({
  items: z.array(zDeadLetterOut),
  next_cursor: z.string().nullable(),
});

/**
 * Page[KeyOut]
 */
export const zPageKeyOut = z.object({
  items: z.array(zKeyOut),
  next_cursor: z.string().nullable(),
});

/**
 * Problem
 */
export const zProblem = z.object({
  code: z.string(),
  current: z.record(z.string(), z.unknown()).nullish(),
  detail: z.string().nullish(),
  schema_version: z.literal(1).optional().default(1),
  status: z.int(),
  title: z.string(),
  type: z.string(),
});

/**
 * ProjectLinkIn
 */
export const zProjectLinkIn = z.object({
  kind: z.enum(["person", "domain", "repo", "coolify_app"]),
  value: z.string().min(1).max(320),
});

/**
 * ProjectCreate
 */
export const zProjectCreate = z.object({
  brief_md: z.string().max(65536).optional().default(""),
  client: z.string().nullish(),
  code_path: z.string().nullish(),
  deadline: z.iso.date().nullish(),
  goal: z.string().max(280).nullish(),
  links: z.array(zProjectLinkIn).optional().default([]),
  name: z.string().min(1).max(120),
  profile_name: z.string().nullish(),
  repo_url: z.string().nullish(),
  schema_version: z.literal(1).optional().default(1),
  status: z
    .enum(["active", "on_hold", "completed"])
    .optional()
    .default("active"),
});

/**
 * ProjectOut
 */
export const zProjectOut = z.object({
  archived_at: z.iso.datetime().nullable(),
  brief_md: z.string().max(65536).optional().default(""),
  client: z.string().nullish(),
  code_path: z.string().nullish(),
  deadline: z.iso.date().nullish(),
  goal: z.string().max(280).nullish(),
  health: zHealth,
  id: z.uuid(),
  last_agent_activity_at: z.iso.datetime().nullish(),
  links: z.array(zProjectLinkIn).optional().default([]),
  name: z.string().min(1).max(120),
  next_milestone: z.iso.date().nullable(),
  open_count: z.int(),
  profile_name: z.string().nullish(),
  repo_url: z.string().nullish(),
  schema_version: z.literal(1).optional().default(1),
  sort_key: z.string(),
  status: z
    .enum(["active", "on_hold", "completed"])
    .optional()
    .default("active"),
  version: z.int(),
});

/**
 * Page[ProjectOut]
 */
export const zPageProjectOut = z.object({
  items: z.array(zProjectOut),
  next_cursor: z.string().nullable(),
});

/**
 * ProjectPatch
 *
 * Fields to change (absent: unchanged; null clears a nullable one) and the version
 * read.
 */
export const zProjectPatch = z.object({
  client: z.string().nullish(),
  code_path: z.string().nullish(),
  deadline: z.iso.date().nullish(),
  goal: z.string().max(280).nullish(),
  links: z.array(zProjectLinkIn).nullish(),
  name: z.string().min(1).max(120).nullish(),
  profile_name: z.string().nullish(),
  repo_url: z.string().nullish(),
  status: z.enum(["active", "on_hold", "completed"]).nullish(),
  version: z.int().gte(0).lte(2147483647),
});

/**
 * ReorderIn
 */
export const zReorderIn = z.object({
  after_id: z.uuid().nullish(),
  before_id: z.uuid().nullish(),
  version: z.int().gte(0).lte(2147483647),
});

/**
 * RotateIn
 */
export const zRotateIn = z.object({
  grace_minutes: z.int().gte(0).lte(1440).optional().default(0),
});

/**
 * SessionOut
 */
export const zSessionOut = z.object({
  created_at: z.iso.datetime(),
  current: z.boolean(),
  device_label: z.string().nullable(),
  expires_at: z.iso.datetime(),
  id: z.uuid(),
  last_seen_at: z.iso.datetime(),
  source_ip: z.string().nullable(),
  user_agent: z.string().nullable(),
});

/**
 * Page[SessionOut]
 */
export const zPageSessionOut = z.object({
  items: z.array(zSessionOut),
  next_cursor: z.string().nullable(),
});

/**
 * SetupIn
 */
export const zSetupIn = z.object({
  email: z.string().min(3).max(254),
  password: z.string().max(1024),
  timezone: z.string().optional().default("UTC"),
  workspace_name: z.string().min(1).max(200).optional().default("My workspace"),
});

/**
 * SetupOut
 */
export const zSetupOut = z.object({
  otpauth_uri: z.string(),
  setup_token: z.string(),
});

/**
 * SetupTotpIn
 */
export const zSetupTotpIn = z.object({
  code: z.string().max(16),
  setup_token: z.string().max(2048),
});

/**
 * SignedInOut
 */
export const zSignedInOut = z.object({
  user_id: z.uuid(),
  workspace_id: z.uuid(),
});

/**
 * TotpIn
 */
export const zTotpIn = z.object({
  code: z.string().max(16),
  preauth: z.string().max(2048),
});

/**
 * UsageRow
 */
export const zUsageRow = z.object({
  counter: z.string(),
  day: z.iso.date(),
  value: z.int(),
});

/**
 * WorkspaceSettingsIn
 */
export const zWorkspaceSettingsIn = z.object({
  subtask_threshold_min: z.int().nullish(),
  timezone: z.string().nullish(),
  version: z.int().gte(0).lte(2147483647),
});

/**
 * WorkspaceSettingsOut
 */
export const zWorkspaceSettingsOut = z.object({
  subtask_threshold_min: z.int(),
  timezone: z.string(),
  version: z.int(),
});

/**
 * VersionIn
 */
export const zTumnisCoreDeadletterVersionIn = z.object({
  version: z.int().gte(0).lte(2147483647),
});

/**
 * VersionIn
 */
export const zTumnisModulesProjectsRouterVersionIn = z.object({
  version: z.int().gte(0).lte(2147483647),
});

/**
 * Response Health Live
 *
 * Successful Response
 */
export const zHealthLiveResponse = z.record(z.string(), z.string());

export const zAuditListAuditQuery = z.object({
  action: z.string().max(200).nullish(),
  actor_type: z
    .enum(["user", "api_key", "task_token", "device", "system"])
    .nullish(),
  from: z.iso.datetime().nullish(),
  to: z.iso.datetime().nullish(),
  cursor: z.string().max(2048).nullish(),
  limit: z.int().gte(1).lte(200).optional().default(50),
});

/**
 * Successful Response
 */
export const zAuditListAuditResponse = zPageAuditEntry;

export const zAuditExportAuditCsvQuery = z.object({
  action: z.string().max(200).nullish(),
  actor_type: z
    .enum(["user", "api_key", "task_token", "device", "system"])
    .nullish(),
  from: z.iso.datetime().nullish(),
  to: z.iso.datetime().nullish(),
});

export const zAuthLoginBody = zLoginIn;

/**
 * Successful Response
 */
export const zAuthLoginResponse = zLoginOut;

/**
 * Successful Response
 */
export const zAuthLogoutResponse = z.void();

/**
 * Successful Response
 */
export const zAuthSignOutOtherDevicesResponse = z.void();

export const zAuthListSessionsQuery = z.object({
  cursor: z.string().nullish(),
  limit: z.int().gte(1).lte(200).optional().default(50),
});

/**
 * Successful Response
 */
export const zAuthListSessionsResponse = zPageSessionOut;

export const zAuthRevokeSessionPath = z.object({
  session_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zAuthRevokeSessionResponse = z.void();

export const zAuthTotpBody = zTotpIn;

/**
 * Successful Response
 */
export const zAuthTotpResponse = zSignedInOut;

export const zDeadLettersGetDeadLettersQuery = z.object({
  status: z
    .string()
    .regex(/^(open|retrying|resolved|discarded)$/)
    .optional()
    .default("open"),
  cursor: z.string().max(2048).nullish(),
  limit: z.int().gte(1).lte(200).optional().default(50),
});

/**
 * Successful Response
 */
export const zDeadLettersGetDeadLettersResponse = zPageDeadLetterOut;

export const zDeadLettersPostDiscardBody = zTumnisCoreDeadletterVersionIn;

export const zDeadLettersPostDiscardPath = z.object({
  dead_letter_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zDeadLettersPostDiscardResponse = zDeadLetterOut;

export const zDeadLettersPostRetryBody = zTumnisCoreDeadletterVersionIn;

export const zDeadLettersPostRetryPath = z.object({
  dead_letter_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zDeadLettersPostRetryResponse = zDeadLetterOut;

export const zAuthListKeysQuery = z.object({
  cursor: z.string().max(2048).nullish(),
  limit: z.int().gte(1).lte(200).optional().default(50),
});

/**
 * Successful Response
 */
export const zAuthListKeysResponse = zPageKeyOut;

export const zAuthCreateKeyBody = zKeyIn;

/**
 * Successful Response
 */
export const zAuthCreateKeyResponse = zKeyCreated;

export const zAuthRevokeKeyPath = z.object({
  id: z.uuid(),
});

/**
 * Successful Response
 */
export const zAuthRevokeKeyResponse = z.void();

export const zAuthRotateKeyBody = zRotateIn.default({ grace_minutes: 0 });

export const zAuthRotateKeyPath = z.object({
  id: z.uuid(),
});

/**
 * Successful Response
 */
export const zAuthRotateKeyResponse = zKeyCreated;

export const zProjectsListProjectsQuery = z.object({
  include_archived: z.boolean().optional().default(false),
  cursor: z.string().max(2048).nullish(),
  limit: z.int().gte(1).lte(200).optional().default(50),
});

/**
 * Successful Response
 */
export const zProjectsListProjectsResponse = zPageProjectOut;

export const zProjectsCreateProjectBody = zProjectCreate;

/**
 * Successful Response
 */
export const zProjectsCreateProjectResponse = zProjectOut;

export const zProjectsGetProjectPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zProjectsGetProjectResponse = zProjectOut;

export const zProjectsUpdateProjectBody = zProjectPatch;

export const zProjectsUpdateProjectPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zProjectsUpdateProjectResponse = zProjectOut;

export const zProjectsArchiveProjectBody =
  zTumnisModulesProjectsRouterVersionIn;

export const zProjectsArchiveProjectPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zProjectsArchiveProjectResponse = zProjectOut;

export const zProjectsReorderProjectBody = zReorderIn;

export const zProjectsReorderProjectPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zProjectsReorderProjectResponse = zProjectOut;

export const zProjectsUnarchiveProjectBody =
  zTumnisModulesProjectsRouterVersionIn;

export const zProjectsUnarchiveProjectPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zProjectsUnarchiveProjectResponse = zProjectOut;

/**
 * Successful Response
 */
export const zSettingsGetWorkspaceSettingsResponse = zWorkspaceSettingsOut;

export const zSettingsPutWorkspaceSettingsBody = zWorkspaceSettingsIn;

/**
 * Successful Response
 */
export const zSettingsPutWorkspaceSettingsResponse = zWorkspaceSettingsOut;

export const zAuthSetupBody = zSetupIn;

/**
 * Successful Response
 */
export const zAuthSetupResponse = zSetupOut;

export const zAuthSetupTotpBody = zSetupTotpIn;

/**
 * Successful Response
 */
export const zAuthSetupTotpResponse = zSignedInOut;

export const zUsageGetUsageQuery = z.object({
  from: z.iso.date(),
  to: z.iso.date(),
});

/**
 * Response Usage Get Usage
 *
 * Successful Response
 */
export const zUsageGetUsageResponse = z.array(zUsageRow);
