// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * AccountOut
 */
export const zAccountOut = z.object({
  email: z.string(),
  second_factor: z.literal("totp"),
  totp_confirmed_at: z.iso.datetime().nullable(),
  user_id: z.uuid(),
});

/**
 * AuditEntry
 */
export const zAuditEntry = z.object({
  action: z.string(),
  actor_id: z.uuid().nullable(),
  actor_type: z.string(),
  correlation_id: z.string().nullable(),
  details: z.record(z.string(), z.unknown()),
  id: z.uuid(),
  occurred_at: z.iso.datetime(),
  reason: z.string().nullable(),
  seq: z.int(),
  source_ip: z.string().nullable(),
  target_id: z.uuid().nullable(),
  target_type: z.string().nullable(),
  user_agent: z.string().nullable(),
});

/**
 * CommentIn
 */
export const zCommentIn = z.object({
  body_md: z.string().min(1).max(20000),
});

/**
 * CommentOut
 */
export const zCommentOut = z.object({
  body_md: z.string(),
  created_at: z.iso.datetime(),
  created_by: z.string(),
  id: z.uuid(),
  task_id: z.uuid(),
  version: z.int(),
});

/**
 * ContextItemIn
 */
export const zContextItemIn = z.object({
  context_item_id: z.uuid(),
});

/**
 * DeadLetterOut
 */
export const zDeadLetterOut = z.object({
  attempts: z.int(),
  error: z.string(),
  event_id: z.uuid(),
  event_name: z.string(),
  id: z.uuid(),
  last_at: z.iso.datetime(),
  retries: z.int(),
  status: z.string(),
  subscriber: z.string(),
  version: z.int(),
});

/**
 * DefaultIn
 */
export const zDefaultIn = z.object({
  version: z.int().gte(0).lte(2147483647),
});

/**
 * FolderIn
 */
export const zFolderIn = z.object({
  location_id: z.uuid(),
});

/**
 * Health
 */
export const zHealth = z.enum(["blocked", "at_risk", "on_track"]);

/**
 * KeyCreated
 */
export const zKeyCreated = z.object({
  created_at: z.iso.datetime(),
  expires_at: z.iso.datetime().nullable(),
  id: z.uuid(),
  key: z.string(),
  last_used_at: z.iso.datetime().nullable(),
  name: z.string(),
  prefix: z.string(),
  project_ids: z.array(z.uuid()).nullable(),
  revoked_at: z.iso.datetime().nullable(),
  scopes: z.array(z.string()),
});

/**
 * KeyIn
 */
export const zKeyIn = z.object({
  expires_at: z.iso.datetime().nullish(),
  name: z.string().min(1).max(200),
  project_ids: z.array(z.uuid()).max(200).nullish(),
  scopes: z.array(z.string()).max(32),
});

/**
 * KeyOut
 */
export const zKeyOut = z.object({
  created_at: z.iso.datetime(),
  expires_at: z.iso.datetime().nullable(),
  id: z.uuid(),
  last_used_at: z.iso.datetime().nullable(),
  name: z.string(),
  prefix: z.string(),
  project_ids: z.array(z.uuid()).nullable(),
  revoked_at: z.iso.datetime().nullable(),
  scopes: z.array(z.string()),
});

/**
 * Label
 */
export const zLabel = z.enum(["human", "ai", "hybrid"]);

/**
 * LocationOut
 */
export const zLocationOut = z.object({
  capabilities: z.record(z.string(), z.boolean()),
  endpoint: z.string().nullable(),
  id: z.uuid(),
  is_default: z.boolean(),
  kind: z.string(),
  name: z.string(),
  root: z.string(),
  status: z.enum(["online", "offline"]),
  status_reason: z.string().nullable(),
  version: z.int(),
});

/**
 * LoginIn
 *
 * `provider` picks the sign-in provider; the other string fields are its credentials
 * (`email` and `password` for `local_password`).
 */
export const zLoginIn = z.object({
  email: z.string().max(254).nullish(),
  password: z.string().max(1024).nullish(),
  provider: z.string().optional().default("local_password"),
});

/**
 * LoginOut
 */
export const zLoginOut = z.object({
  preauth: z.string(),
  step: z.literal("totp").optional().default("totp"),
});

/**
 * ModuleFlagIn
 */
export const zModuleFlagIn = z.object({
  enabled: z.boolean(),
  module: z.string().max(64),
});

/**
 * ModuleFlagOut
 */
export const zModuleFlagOut = z.object({
  enabled: z.boolean(),
  module: z.string(),
  required: z.boolean(),
});

/**
 * ModuleFlagsOut
 */
export const zModuleFlagsOut = z.object({
  items: z.array(zModuleFlagOut),
});

/**
 * MoveIn
 *
 * One board drag (R-20): the target column, the rank between the new neighbours'
 * ranks (core/rank.py) and the version read.
 */
export const zMoveIn = z.object({
  board_rank: z.string().min(1).max(48),
  column_id: z.uuid(),
  version: z.int().gte(0).lte(2147483647),
});

/**
 * Page[AuditEntry]
 */
export const zPageAuditEntry = z.object({
  items: z.array(zAuditEntry),
  next_cursor: z.string().nullable(),
});

/**
 * Page[DeadLetterOut]
 */
export const zPageDeadLetterOut = z.object({
  items: z.array(zDeadLetterOut),
  next_cursor: z.string().nullable(),
});

/**
 * Page[KeyOut]
 */
export const zPageKeyOut = z.object({
  items: z.array(zKeyOut),
  next_cursor: z.string().nullable(),
});

/**
 * Problem
 */
export const zProblem = z.object({
  code: z.string(),
  current: z.record(z.string(), z.unknown()).nullish(),
  detail: z.string().nullish(),
  schema_version: z.literal(1).optional().default(1),
  status: z.int(),
  title: z.string(),
  type: z.string(),
});

/**
 * ProjectFolderOut
 */
export const zProjectFolderOut = z.object({
  location_id: z.uuid(),
  mode: z.enum(["tumnis_made", "existing"]),
  project_id: z.uuid(),
  root_path: z.string(),
  version: z.int(),
});

/**
 * ProjectLinkIn
 */
export const zProjectLinkIn = z.object({
  kind: z.enum(["person", "domain", "repo", "coolify_app"]),
  value: z.string().min(1).max(320),
});

/**
 * ProjectCreate
 */
export const zProjectCreate = z.object({
  brief_md: z.string().max(65536).optional().default(""),
  client: z.string().nullish(),
  code_path: z.string().nullish(),
  deadline: z.iso.date().nullish(),
  goal: z.string().max(280).nullish(),
  links: z.array(zProjectLinkIn).optional().default([]),
  name: z.string().min(1).max(120),
  profile_name: z.string().nullish(),
  repo_url: z.string().nullish(),
  schema_version: z.literal(1).optional().default(1),
  status: z
    .enum(["active", "on_hold", "completed"])
    .optional()
    .default("active"),
});

/**
 * ProjectOut
 */
export const zProjectOut = z.object({
  archived_at: z.iso.datetime().nullable(),
  brief_md: z.string().max(65536).optional().default(""),
  client: z.string().nullish(),
  code_path: z.string().nullish(),
  deadline: z.iso.date().nullish(),
  goal: z.string().max(280).nullish(),
  health: zHealth,
  id: z.uuid(),
  last_agent_activity_at: z.iso.datetime().nullish(),
  links: z.array(zProjectLinkIn).optional().default([]),
  name: z.string().min(1).max(120),
  next_milestone: z.iso.date().nullable(),
  open_count: z.int(),
  profile_name: z.string().nullish(),
  repo_url: z.string().nullish(),
  schema_version: z.literal(1).optional().default(1),
  sort_key: z.string(),
  status: z
    .enum(["active", "on_hold", "completed"])
    .optional()
    .default("active"),
  subtask_threshold_min: z.int().nullish(),
  version: z.int(),
});

/**
 * Page[ProjectOut]
 */
export const zPageProjectOut = z.object({
  items: z.array(zProjectOut),
  next_cursor: z.string().nullable(),
});

/**
 * ProjectPatch
 *
 * Fields to change (absent: unchanged; null clears a nullable one) and the version
 * read.
 */
export const zProjectPatch = z.object({
  client: z.string().nullish(),
  code_path: z.string().nullish(),
  deadline: z.iso.date().nullish(),
  goal: z.string().max(280).nullish(),
  links: z.array(zProjectLinkIn).nullish(),
  name: z.string().min(1).max(120).nullish(),
  profile_name: z.string().nullish(),
  repo_url: z.string().nullish(),
  status: z.enum(["active", "on_hold", "completed"]).nullish(),
  subtask_threshold_min: z.int().gte(1).lte(960).nullish(),
  version: z.int().gte(0).lte(2147483647),
});

/**
 * ReorderIn
 */
export const zReorderIn = z.object({
  after_id: z.uuid().nullish(),
  before_id: z.uuid().nullish(),
  version: z.int().gte(0).lte(2147483647),
});

/**
 * ReviewCountOut
 */
export const zReviewCountOut = z.object({
  count: z.int(),
});

/**
 * ReviewKindOut
 */
export const zReviewKindOut = z.object({
  actions: z.array(z.string()),
  impact_scope: z.string(),
  kind: z.string(),
  owner_module: z.string(),
  payload_schema: z.record(z.string(), z.unknown()),
});

/**
 * ReviewKindsOut
 */
export const zReviewKindsOut = z.object({
  items: z.array(zReviewKindOut),
});

/**
 * RotateIn
 */
export const zRotateIn = z.object({
  grace_minutes: z.int().gte(0).lte(1440).optional().default(0),
});

/**
 * S3ConfigIn
 */
export const zS3ConfigIn = z.object({
  access_key: z.string(),
  endpoint: z.string(),
  path_style: z.boolean().optional().default(true),
  region: z.string().optional().default("us-east-1"),
  secret_key: z.string(),
  sse: z.literal("AES256").nullish(),
});

/**
 * LocationIn
 */
export const zLocationIn = z.object({
  is_default: z.boolean().optional().default(false),
  kind: z.enum(["server_path", "s3"]),
  name: z.string().min(1).max(100),
  root: z.string().min(1).max(1024),
  s3: zS3ConfigIn.nullish(),
});

/**
 * SessionOut
 */
export const zSessionOut = z.object({
  created_at: z.iso.datetime(),
  current: z.boolean(),
  device_label: z.string().nullable(),
  expires_at: z.iso.datetime(),
  id: z.uuid(),
  last_seen_at: z.iso.datetime(),
  source_ip: z.string().nullable(),
  user_agent: z.string().nullable(),
});

/**
 * Page[SessionOut]
 */
export const zPageSessionOut = z.object({
  items: z.array(zSessionOut),
  next_cursor: z.string().nullable(),
});

/**
 * SettingSectionIn
 */
export const zSettingSectionIn = z.object({
  values: z.record(z.string(), z.unknown()),
  version: z.int().gte(0).lte(2147483647).nullish(),
});

/**
 * SettingSectionOut
 */
export const zSettingSectionOut = z.object({
  secrets_set: z.array(z.string()),
  section: z.string(),
  values: z.record(z.string(), z.unknown()),
  version: z.int().nullable(),
});

/**
 * SetupIn
 */
export const zSetupIn = z.object({
  email: z.string().min(3).max(254),
  password: z.string().max(1024),
  timezone: z.string().optional().default("UTC"),
  workspace_name: z.string().min(1).max(200).optional().default("My workspace"),
});

/**
 * SetupOut
 */
export const zSetupOut = z.object({
  otpauth_uri: z.string(),
  setup_token: z.string(),
});

/**
 * SetupTotpIn
 */
export const zSetupTotpIn = z.object({
  code: z.string().max(16),
  setup_token: z.string().max(2048),
});

/**
 * SignedInOut
 */
export const zSignedInOut = z.object({
  user_id: z.uuid(),
  workspace_id: z.uuid(),
});

/**
 * Status
 */
export const zStatus = z.enum([
  "backlog",
  "today",
  "in_progress",
  "waiting_on_human",
  "in_review",
  "done",
]);

/**
 * ColumnIn
 */
export const zColumnIn = z.object({
  id: z.uuid().nullish(),
  name: z.string().min(1).max(60),
  status: zStatus,
});

/**
 * ColumnOut
 */
export const zColumnOut = z.object({
  id: z.uuid(),
  name: z.string(),
  sort_key: z.string(),
  status: zStatus,
  version: z.int(),
});

/**
 * ColumnsIn
 */
export const zColumnsIn = z.object({
  columns: z.array(zColumnIn).min(1).max(30),
});

/**
 * ColumnsOut
 */
export const zColumnsOut = z.object({
  items: z.array(zColumnOut),
  project_id: z.uuid(),
});

/**
 * StatusIn
 */
export const zStatusIn = z.object({
  to: zStatus,
  version: z.int().gte(0).lte(2147483647),
});

/**
 * TaskContextItemOut
 *
 * A task's link to outside content: the ContextItem and what it points at.
 */
export const zTaskContextItemOut = z.object({
  context_item_id: z.uuid(),
  id: z.uuid(),
  tainted: z.boolean(),
  target_id: z.uuid().nullable(),
  target_type: z.string(),
  target_url: z.string().nullable(),
  task_id: z.uuid(),
});

/**
 * TaskCreate
 */
export const zTaskCreate = z.object({
  acceptance_criteria: z.string().max(8000).nullish(),
  due_on: z.iso.date().nullish(),
  estimate_minutes: z.int().gt(0).lte(960).nullish(),
  first_action: z.string().max(8000).nullish(),
  label: zLabel.nullish(),
  parent_id: z.uuid().nullish(),
  priority: z
    .enum(["low", "normal", "high", "urgent"])
    .optional()
    .default("normal"),
  project_id: z.uuid(),
  schema_version: z.literal(1).optional().default(1),
  status: z.enum(["backlog", "today"]).optional().default("backlog"),
  title: z.string().min(1).max(500),
});

/**
 * TaskOut
 */
export const zTaskOut = z.object({
  acceptance_criteria: z.string().nullable(),
  actual_minutes: z.int().nullable(),
  assigned_agent_id: z.uuid().nullable(),
  board_rank: z.string(),
  column_id: z.uuid().nullable(),
  completed_at: z.iso.datetime().nullable(),
  created_at: z.iso.datetime(),
  due_on: z.iso.date().nullable(),
  estimate_minutes: z.int().nullable(),
  first_action: z.string().nullable(),
  id: z.uuid(),
  label: zLabel.nullable(),
  label_source: z.enum(["user", "jev", "agent", "fallback"]).nullable(),
  parent_id: z.uuid().nullable(),
  priority: z.enum(["low", "normal", "high", "urgent"]),
  project_id: z.uuid(),
  rollover_count: z.int(),
  schema_version: z.literal(1).optional().default(1),
  source: z.string(),
  started_at: z.iso.datetime().nullable(),
  status: zStatus,
  tainted: z.boolean(),
  title: z.string(),
  updated_at: z.iso.datetime(),
  version: z.int(),
});

/**
 * CardOut
 */
export const zCardOut = z.object({
  checklist: z.array(zTaskOut),
  task: zTaskOut,
});

/**
 * BoardColumnOut
 */
export const zBoardColumnOut = z.object({
  cards: z.array(zCardOut),
  id: z.uuid(),
  name: z.string(),
  status: zStatus,
});

/**
 * BoardOut
 */
export const zBoardOut = z.object({
  columns: z.array(zBoardColumnOut),
  project_id: z.uuid(),
  threshold_min: z.int(),
});

/**
 * TaskPage
 *
 * A page of tasks and how many match the filter across every page (P0-23): the Today
 * panel shows five and says "+N more".
 */
export const zTaskPage = z.object({
  items: z.array(zTaskOut),
  next_cursor: z.string().nullable(),
  total: z.int(),
});

/**
 * TaskPatch
 *
 * Fields to change (absent: unchanged; null clears a nullable one) and the version
 * read. Status changes go through `POST /status` or `/move`.
 */
export const zTaskPatch = z.object({
  acceptance_criteria: z.string().max(8000).nullish(),
  due_on: z.iso.date().nullish(),
  estimate_minutes: z.int().gt(0).lte(960).nullish(),
  first_action: z.string().max(8000).nullish(),
  label: zLabel.nullish(),
  priority: z.enum(["low", "normal", "high", "urgent"]).nullish(),
  title: z.string().min(1).max(500).nullish(),
  version: z.int().gte(0).lte(2147483647),
});

/**
 * TotpEnrolConfirmIn
 */
export const zTotpEnrolConfirmIn = z.object({
  code: z.string().max(16),
  enrol_token: z.string().max(2048),
});

/**
 * TotpEnrolIn
 */
export const zTotpEnrolIn = z.object({
  password: z.string().max(1024),
});

/**
 * TotpEnrolOut
 */
export const zTotpEnrolOut = z.object({
  enrol_token: z.string(),
  otpauth_uri: z.string(),
});

/**
 * TotpIn
 */
export const zTotpIn = z.object({
  code: z.string().max(16),
  preauth: z.string().max(2048),
});

/**
 * UsageRow
 */
export const zUsageRow = z.object({
  counter: z.string(),
  day: z.iso.date(),
  value: z.int(),
});

/**
 * WorkspaceSettingsIn
 */
export const zWorkspaceSettingsIn = z.object({
  subtask_threshold_min: z.int().gte(5).lte(480).nullish(),
  timezone: z.string().nullish(),
  version: z.int().gte(0).lte(2147483647),
});

/**
 * WorkspaceSettingsOut
 */
export const zWorkspaceSettingsOut = z.object({
  subtask_threshold_min: z.int(),
  timezone: z.string(),
  version: z.int(),
});

/**
 * VersionIn
 */
export const zTumnisCoreDeadletterVersionIn = z.object({
  version: z.int().gte(0).lte(2147483647),
});

/**
 * VersionIn
 */
export const zTumnisModulesProjectsRouterVersionIn = z.object({
  version: z.int().gte(0).lte(2147483647),
});

/**
 * Response Health Live
 *
 * Successful Response
 */
export const zHealthLiveResponse = z.record(z.string(), z.string());

export const zAuditListAuditQuery = z.object({
  action: z.string().max(200).nullish(),
  actor_type: z
    .enum(["user", "api_key", "task_token", "device", "system"])
    .nullish(),
  from: z.iso.datetime().nullish(),
  to: z.iso.datetime().nullish(),
  cursor: z.string().max(2048).nullish(),
  limit: z.int().gte(1).lte(200).optional().default(50),
});

/**
 * Successful Response
 */
export const zAuditListAuditResponse = zPageAuditEntry;

export const zAuditExportAuditCsvQuery = z.object({
  action: z.string().max(200).nullish(),
  actor_type: z
    .enum(["user", "api_key", "task_token", "device", "system"])
    .nullish(),
  from: z.iso.datetime().nullish(),
  to: z.iso.datetime().nullish(),
});

/**
 * Successful Response
 */
export const zAuthGetAccountResponse = zAccountOut;

export const zAuthLoginBody = zLoginIn;

/**
 * Successful Response
 */
export const zAuthLoginResponse = zLoginOut;

/**
 * Successful Response
 */
export const zAuthLogoutResponse = z.void();

/**
 * Successful Response
 */
export const zAuthSignOutOtherDevicesResponse = z.void();

export const zAuthListSessionsQuery = z.object({
  cursor: z.string().nullish(),
  limit: z.int().gte(1).lte(200).optional().default(50),
});

/**
 * Successful Response
 */
export const zAuthListSessionsResponse = zPageSessionOut;

export const zAuthRevokeSessionPath = z.object({
  session_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zAuthRevokeSessionResponse = z.void();

export const zAuthTotpBody = zTotpIn;

/**
 * Successful Response
 */
export const zAuthTotpResponse = zSignedInOut;

export const zAuthStartTotpEnrolmentBody = zTotpEnrolIn;

/**
 * Successful Response
 */
export const zAuthStartTotpEnrolmentResponse = zTotpEnrolOut;

export const zAuthConfirmTotpEnrolmentBody = zTotpEnrolConfirmIn;

/**
 * Successful Response
 */
export const zAuthConfirmTotpEnrolmentResponse = z.void();

export const zDeadLettersGetDeadLettersQuery = z.object({
  status: z
    .string()
    .regex(/^(open|retrying|resolved|discarded)$/)
    .optional()
    .default("open"),
  cursor: z.string().max(2048).nullish(),
  limit: z.int().gte(1).lte(200).optional().default(50),
});

/**
 * Successful Response
 */
export const zDeadLettersGetDeadLettersResponse = zPageDeadLetterOut;

export const zDeadLettersPostDiscardBody = zTumnisCoreDeadletterVersionIn;

export const zDeadLettersPostDiscardPath = z.object({
  dead_letter_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zDeadLettersPostDiscardResponse = zDeadLetterOut;

export const zDeadLettersPostRetryBody = zTumnisCoreDeadletterVersionIn;

export const zDeadLettersPostRetryPath = z.object({
  dead_letter_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zDeadLettersPostRetryResponse = zDeadLetterOut;

export const zAuthListKeysQuery = z.object({
  cursor: z.string().max(2048).nullish(),
  limit: z.int().gte(1).lte(200).optional().default(50),
});

/**
 * Successful Response
 */
export const zAuthListKeysResponse = zPageKeyOut;

export const zAuthCreateKeyBody = zKeyIn;

/**
 * Successful Response
 */
export const zAuthCreateKeyResponse = zKeyCreated;

export const zAuthRevokeKeyPath = z.object({
  id: z.uuid(),
});

/**
 * Successful Response
 */
export const zAuthRevokeKeyResponse = z.void();

export const zAuthRotateKeyBody = zRotateIn.default({ grace_minutes: 0 });

export const zAuthRotateKeyPath = z.object({
  id: z.uuid(),
});

/**
 * Successful Response
 */
export const zAuthRotateKeyResponse = zKeyCreated;

/**
 * Response Knowledge List Locations
 *
 * Successful Response
 */
export const zKnowledgeListLocationsResponse = z.array(zLocationOut);

export const zKnowledgeCreateLocationBody = zLocationIn;

/**
 * Successful Response
 */
export const zKnowledgeCreateLocationResponse = zLocationOut;

export const zKnowledgeSetDefaultLocationBody = zDefaultIn;

export const zKnowledgeSetDefaultLocationPath = z.object({
  storage_location_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zKnowledgeSetDefaultLocationResponse = zLocationOut;

export const zKnowledgeTestLocationPath = z.object({
  storage_location_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zKnowledgeTestLocationResponse = zLocationOut;

export const zKnowledgeSetProjectFolderBody = zFolderIn;

export const zKnowledgeSetProjectFolderPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zKnowledgeSetProjectFolderResponse = zProjectFolderOut;

export const zProjectsListProjectsQuery = z.object({
  include_archived: z.boolean().optional().default(false),
  cursor: z.string().max(2048).nullish(),
  limit: z.int().gte(1).lte(200).optional().default(50),
});

/**
 * Successful Response
 */
export const zProjectsListProjectsResponse = zPageProjectOut;

export const zProjectsCreateProjectBody = zProjectCreate;

/**
 * Successful Response
 */
export const zProjectsCreateProjectResponse = zProjectOut;

export const zProjectsGetProjectPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zProjectsGetProjectResponse = zProjectOut;

export const zProjectsUpdateProjectBody = zProjectPatch;

export const zProjectsUpdateProjectPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zProjectsUpdateProjectResponse = zProjectOut;

export const zProjectsArchiveProjectBody =
  zTumnisModulesProjectsRouterVersionIn;

export const zProjectsArchiveProjectPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zProjectsArchiveProjectResponse = zProjectOut;

export const zTasksGetBoardPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zTasksGetBoardResponse = zBoardOut;

export const zTasksGetColumnsPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zTasksGetColumnsResponse = zColumnsOut;

export const zTasksPutColumnsBody = zColumnsIn;

export const zTasksPutColumnsPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zTasksPutColumnsResponse = zColumnsOut;

export const zProjectsReorderProjectBody = zReorderIn;

export const zProjectsReorderProjectPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zProjectsReorderProjectResponse = zProjectOut;

export const zProjectsUnarchiveProjectBody =
  zTumnisModulesProjectsRouterVersionIn;

export const zProjectsUnarchiveProjectPath = z.object({
  project_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zProjectsUnarchiveProjectResponse = zProjectOut;

/**
 * Successful Response
 */
export const zTasksGetReviewCountResponse = zReviewCountOut;

/**
 * Successful Response
 */
export const zTasksListReviewKindsResponse = zReviewKindsOut;

/**
 * Successful Response
 */
export const zSettingsListModulesResponse = zModuleFlagsOut;

export const zSettingsSetModuleBody = zModuleFlagIn;

/**
 * Successful Response
 */
export const zSettingsSetModuleResponse = zModuleFlagOut;

/**
 * Successful Response
 */
export const zSettingsGetWorkspaceSettingsResponse = zWorkspaceSettingsOut;

export const zSettingsPutWorkspaceSettingsBody = zWorkspaceSettingsIn;

/**
 * Successful Response
 */
export const zSettingsPutWorkspaceSettingsResponse = zWorkspaceSettingsOut;

export const zSettingsGetSectionPath = z.object({
  section: z.string(),
});

/**
 * Successful Response
 */
export const zSettingsGetSectionResponse = zSettingSectionOut;

export const zSettingsPutSectionBody = zSettingSectionIn;

export const zSettingsPutSectionPath = z.object({
  section: z.string(),
});

/**
 * Successful Response
 */
export const zSettingsPutSectionResponse = zSettingSectionOut;

export const zAuthSetupBody = zSetupIn;

/**
 * Successful Response
 */
export const zAuthSetupResponse = zSetupOut;

export const zAuthSetupTotpBody = zSetupTotpIn;

/**
 * Successful Response
 */
export const zAuthSetupTotpResponse = zSignedInOut;

export const zTasksListTasksQuery = z.object({
  project_id: z.uuid().nullish(),
  status: zStatus.nullish(),
  order: z.enum(["created", "today"]).optional().default("created"),
  cursor: z.string().max(2048).nullish(),
  limit: z.int().gte(1).lte(200).optional().default(50),
});

/**
 * Successful Response
 */
export const zTasksListTasksResponse = zTaskPage;

export const zTasksCreateTaskBody = zTaskCreate;

/**
 * Successful Response
 */
export const zTasksCreateTaskResponse = zTaskOut;

export const zTasksGetTaskPath = z.object({
  task_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zTasksGetTaskResponse = zTaskOut;

export const zTasksUpdateTaskBody = zTaskPatch;

export const zTasksUpdateTaskPath = z.object({
  task_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zTasksUpdateTaskResponse = zTaskOut;

export const zTasksAddCommentBody = zCommentIn;

export const zTasksAddCommentPath = z.object({
  task_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zTasksAddCommentResponse = zCommentOut;

export const zTasksLinkContextItemBody = zContextItemIn;

export const zTasksLinkContextItemPath = z.object({
  task_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zTasksLinkContextItemResponse = zTaskContextItemOut;

export const zTasksMoveTaskBody = zMoveIn;

export const zTasksMoveTaskPath = z.object({
  task_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zTasksMoveTaskResponse = zTaskOut;

export const zTasksChangeStatusBody = zStatusIn;

export const zTasksChangeStatusPath = z.object({
  task_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zTasksChangeStatusResponse = zTaskOut;

export const zUsageGetUsageQuery = z.object({
  from: z.iso.date(),
  to: z.iso.date(),
});

/**
 * Response Usage Get Usage
 *
 * Successful Response
 */
export const zUsageGetUsageResponse = z.array(zUsageRow);
