/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ReviewRouteImport } from "./routes/review";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as SetupRouteImport } from "./routes/setup";
import { Route as TasksRouteImport } from "./routes/tasks";
import { Route as ProjectsProjectIdRouteImport } from "./routes/projects.$projectId";
import { Route as SettingsSectionRouteImport } from "./routes/settings.$section";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const ReviewRoute = ReviewRouteImport.update({
  id: "/review",
  path: "/review",
  getParentRoute: () => rootRouteImport,
} as any);
const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);
const SetupRoute = SetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => rootRouteImport,
} as any);
const TasksRoute = TasksRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: "/settings/$section",
  path: "/settings/$section",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/review": typeof ReviewRoute;
  "/search": typeof SearchRoute;
  "/setup": typeof SetupRoute;
  "/tasks": typeof TasksRoute;
  "/projects/$projectId": typeof ProjectsProjectIdRoute;
  "/settings/$section": typeof SettingsSectionRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/review": typeof ReviewRoute;
  "/search": typeof SearchRoute;
  "/setup": typeof SetupRoute;
  "/tasks": typeof TasksRoute;
  "/projects/$projectId": typeof ProjectsProjectIdRoute;
  "/settings/$section": typeof SettingsSectionRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/review": typeof ReviewRoute;
  "/search": typeof SearchRoute;
  "/setup": typeof SetupRoute;
  "/tasks": typeof TasksRoute;
  "/projects/$projectId": typeof ProjectsProjectIdRoute;
  "/settings/$section": typeof SettingsSectionRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/review"
    | "/search"
    | "/setup"
    | "/tasks"
    | "/projects/$projectId"
    | "/settings/$section";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/review"
    | "/search"
    | "/setup"
    | "/tasks"
    | "/projects/$projectId"
    | "/settings/$section";
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/review"
    | "/search"
    | "/setup"
    | "/tasks"
    | "/projects/$projectId"
    | "/settings/$section";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LoginRoute: typeof LoginRoute;
  ReviewRoute: typeof ReviewRoute;
  SearchRoute: typeof SearchRoute;
  SetupRoute: typeof SetupRoute;
  TasksRoute: typeof TasksRoute;
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute;
  SettingsSectionRoute: typeof SettingsSectionRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/review": {
      id: "/review";
      path: "/review";
      fullPath: "/review";
      preLoaderRoute: typeof ReviewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/setup": {
      id: "/setup";
      path: "/setup";
      fullPath: "/setup";
      preLoaderRoute: typeof SetupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tasks": {
      id: "/tasks";
      path: "/tasks";
      fullPath: "/tasks";
      preLoaderRoute: typeof TasksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$projectId": {
      id: "/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof ProjectsProjectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/$section": {
      id: "/settings/$section";
      path: "/settings/$section";
      fullPath: "/settings/$section";
      preLoaderRoute: typeof SettingsSectionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ReviewRoute: ReviewRoute,
  SearchRoute: SearchRoute,
  SetupRoute: SetupRoute,
  TasksRoute: TasksRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  SettingsSectionRoute: SettingsSectionRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
