// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  auditExportAuditCsv,
  auditListAudit,
  authCreateKey,
  authListKeys,
  authListSessions,
  authLogin,
  authLogout,
  authRevokeKey,
  authRevokeSession,
  authRotateKey,
  authSetup,
  authSetupTotp,
  authSignOutOtherDevices,
  authTotp,
  deadLettersGetDeadLetters,
  deadLettersPostDiscard,
  deadLettersPostRetry,
  healthLive,
  healthReady,
  type Options,
  projectsArchiveProject,
  projectsCreateProject,
  projectsGetProject,
  projectsListProjects,
  projectsReorderProject,
  projectsUnarchiveProject,
  projectsUpdateProject,
  settingsGetWorkspaceSettings,
  settingsPutWorkspaceSettings,
  usageGetUsage,
} from "../sdk.gen";
import type {
  AuditExportAuditCsvData,
  AuditExportAuditCsvError,
  AuditListAuditData,
  AuditListAuditError,
  AuditListAuditResponse,
  AuthCreateKeyData,
  AuthCreateKeyError,
  AuthCreateKeyResponse,
  AuthListKeysData,
  AuthListKeysError,
  AuthListKeysResponse,
  AuthListSessionsData,
  AuthListSessionsError,
  AuthListSessionsResponse,
  AuthLoginData,
  AuthLoginError,
  AuthLoginResponse,
  AuthLogoutData,
  AuthLogoutError,
  AuthLogoutResponse,
  AuthRevokeKeyData,
  AuthRevokeKeyError,
  AuthRevokeKeyResponse,
  AuthRevokeSessionData,
  AuthRevokeSessionError,
  AuthRevokeSessionResponse,
  AuthRotateKeyData,
  AuthRotateKeyError,
  AuthRotateKeyResponse,
  AuthSetupData,
  AuthSetupError,
  AuthSetupResponse,
  AuthSetupTotpData,
  AuthSetupTotpError,
  AuthSetupTotpResponse,
  AuthSignOutOtherDevicesData,
  AuthSignOutOtherDevicesError,
  AuthSignOutOtherDevicesResponse,
  AuthTotpData,
  AuthTotpError,
  AuthTotpResponse,
  DeadLettersGetDeadLettersData,
  DeadLettersGetDeadLettersError,
  DeadLettersGetDeadLettersResponse,
  DeadLettersPostDiscardData,
  DeadLettersPostDiscardError,
  DeadLettersPostDiscardResponse,
  DeadLettersPostRetryData,
  DeadLettersPostRetryError,
  DeadLettersPostRetryResponse,
  HealthLiveData,
  HealthLiveResponse,
  HealthReadyData,
  ProjectsArchiveProjectData,
  ProjectsArchiveProjectError,
  ProjectsArchiveProjectResponse,
  ProjectsCreateProjectData,
  ProjectsCreateProjectError,
  ProjectsCreateProjectResponse,
  ProjectsGetProjectData,
  ProjectsGetProjectError,
  ProjectsGetProjectResponse,
  ProjectsListProjectsData,
  ProjectsListProjectsError,
  ProjectsListProjectsResponse,
  ProjectsReorderProjectData,
  ProjectsReorderProjectError,
  ProjectsReorderProjectResponse,
  ProjectsUnarchiveProjectData,
  ProjectsUnarchiveProjectError,
  ProjectsUnarchiveProjectResponse,
  ProjectsUpdateProjectData,
  ProjectsUpdateProjectError,
  ProjectsUpdateProjectResponse,
  SettingsGetWorkspaceSettingsData,
  SettingsGetWorkspaceSettingsError,
  SettingsGetWorkspaceSettingsResponse,
  SettingsPutWorkspaceSettingsData,
  SettingsPutWorkspaceSettingsError,
  SettingsPutWorkspaceSettingsResponse,
  UsageGetUsageData,
  UsageGetUsageError,
  UsageGetUsageResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthLiveQueryKey = (options?: Options<HealthLiveData>) =>
  createQueryKey("healthLive", options);

/**
 * Live
 */
export const healthLiveOptions = (options?: Options<HealthLiveData>) =>
  queryOptions<
    HealthLiveResponse,
    DefaultError,
    HealthLiveResponse,
    ReturnType<typeof healthLiveQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthLive({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthLiveQueryKey(options),
  });

export const healthReadyQueryKey = (options?: Options<HealthReadyData>) =>
  createQueryKey("healthReady", options);

/**
 * Ready
 */
export const healthReadyOptions = (options?: Options<HealthReadyData>) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof healthReadyQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthReady({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthReadyQueryKey(options),
  });

export const auditListAuditQueryKey = (options?: Options<AuditListAuditData>) =>
  createQueryKey("auditListAudit", options);

/**
 * List Audit
 *
 * The workspace's audit log, newest first.
 */
export const auditListAuditOptions = (options?: Options<AuditListAuditData>) =>
  queryOptions<
    AuditListAuditResponse,
    AuditListAuditError,
    AuditListAuditResponse,
    ReturnType<typeof auditListAuditQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await auditListAudit({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: auditListAuditQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const auditListAuditInfiniteQueryKey = (
  options?: Options<AuditListAuditData>,
): QueryKey<Options<AuditListAuditData>> =>
  createQueryKey("auditListAudit", options, true);

/**
 * List Audit
 *
 * The workspace's audit log, newest first.
 */
export const auditListAuditInfiniteOptions = (
  options?: Options<AuditListAuditData>,
) => {
  const opts = infiniteQueryOptions<
    AuditListAuditResponse,
    AuditListAuditError,
    InfiniteData<AuditListAuditResponse>,
    QueryKey<Options<AuditListAuditData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<AuditListAuditData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<AuditListAuditData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await auditListAudit({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: auditListAuditInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

export const auditExportAuditCsvQueryKey = (
  options?: Options<AuditExportAuditCsvData>,
) => createQueryKey("auditExportAuditCsv", options);

/**
 * Export Audit Csv
 *
 * The workspace's audit log as CSV, newest first; the export is audited.
 */
export const auditExportAuditCsvOptions = (
  options?: Options<AuditExportAuditCsvData>,
) =>
  queryOptions<
    unknown,
    AuditExportAuditCsvError,
    unknown,
    ReturnType<typeof auditExportAuditCsvQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await auditExportAuditCsv({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: auditExportAuditCsvQueryKey(options),
  });

/**
 * Login
 *
 * The password step: answers `{"step": "totp", "preauth": ...}` and sets no cookie.
 */
export const authLoginMutation = (
  options?: Partial<Options<AuthLoginData>>,
): UseMutationOptions<
  AuthLoginResponse,
  AuthLoginError,
  Options<AuthLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthLoginResponse,
    AuthLoginError,
    Options<AuthLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Logout
 *
 * Ends this session and clears its cookies.
 */
export const authLogoutMutation = (
  options?: Partial<Options<AuthLogoutData>>,
): UseMutationOptions<
  AuthLogoutResponse,
  AuthLogoutError,
  Options<AuthLogoutData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthLogoutResponse,
    AuthLogoutError,
    Options<AuthLogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authLogout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Sign Out Other Devices
 *
 * Revokes every session of this user but the calling one (R-21).
 */
export const authSignOutOtherDevicesMutation = (
  options?: Partial<Options<AuthSignOutOtherDevicesData>>,
): UseMutationOptions<
  AuthSignOutOtherDevicesResponse,
  AuthSignOutOtherDevicesError,
  Options<AuthSignOutOtherDevicesData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthSignOutOtherDevicesResponse,
    AuthSignOutOtherDevicesError,
    Options<AuthSignOutOtherDevicesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authSignOutOtherDevices({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const authListSessionsQueryKey = (
  options?: Options<AuthListSessionsData>,
) => createQueryKey("authListSessions", options);

/**
 * List Sessions
 *
 * This user's signed-in devices, newest first, the calling one `current`.
 */
export const authListSessionsOptions = (
  options?: Options<AuthListSessionsData>,
) =>
  queryOptions<
    AuthListSessionsResponse,
    AuthListSessionsError,
    AuthListSessionsResponse,
    ReturnType<typeof authListSessionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authListSessions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authListSessionsQueryKey(options),
  });

export const authListSessionsInfiniteQueryKey = (
  options?: Options<AuthListSessionsData>,
): QueryKey<Options<AuthListSessionsData>> =>
  createQueryKey("authListSessions", options, true);

/**
 * List Sessions
 *
 * This user's signed-in devices, newest first, the calling one `current`.
 */
export const authListSessionsInfiniteOptions = (
  options?: Options<AuthListSessionsData>,
) => {
  const opts = infiniteQueryOptions<
    AuthListSessionsResponse,
    AuthListSessionsError,
    InfiniteData<AuthListSessionsResponse>,
    QueryKey<Options<AuthListSessionsData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<AuthListSessionsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<AuthListSessionsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await authListSessions({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: authListSessionsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Revoke Session
 *
 * Revokes one of this user's sessions.
 */
export const authRevokeSessionMutation = (
  options?: Partial<Options<AuthRevokeSessionData>>,
): UseMutationOptions<
  AuthRevokeSessionResponse,
  AuthRevokeSessionError,
  Options<AuthRevokeSessionData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthRevokeSessionResponse,
    AuthRevokeSessionError,
    Options<AuthRevokeSessionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authRevokeSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Totp
 *
 * The TOTP step: sets the session and CSRF cookies.
 */
export const authTotpMutation = (
  options?: Partial<Options<AuthTotpData>>,
): UseMutationOptions<
  AuthTotpResponse,
  AuthTotpError,
  Options<AuthTotpData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthTotpResponse,
    AuthTotpError,
    Options<AuthTotpData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authTotp({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deadLettersGetDeadLettersQueryKey = (
  options?: Options<DeadLettersGetDeadLettersData>,
) => createQueryKey("deadLettersGetDeadLetters", options);

/**
 * Get Dead Letters
 */
export const deadLettersGetDeadLettersOptions = (
  options?: Options<DeadLettersGetDeadLettersData>,
) =>
  queryOptions<
    DeadLettersGetDeadLettersResponse,
    DeadLettersGetDeadLettersError,
    DeadLettersGetDeadLettersResponse,
    ReturnType<typeof deadLettersGetDeadLettersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await deadLettersGetDeadLetters({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: deadLettersGetDeadLettersQueryKey(options),
  });

export const deadLettersGetDeadLettersInfiniteQueryKey = (
  options?: Options<DeadLettersGetDeadLettersData>,
): QueryKey<Options<DeadLettersGetDeadLettersData>> =>
  createQueryKey("deadLettersGetDeadLetters", options, true);

/**
 * Get Dead Letters
 */
export const deadLettersGetDeadLettersInfiniteOptions = (
  options?: Options<DeadLettersGetDeadLettersData>,
) => {
  const opts = infiniteQueryOptions<
    DeadLettersGetDeadLettersResponse,
    DeadLettersGetDeadLettersError,
    InfiniteData<DeadLettersGetDeadLettersResponse>,
    QueryKey<Options<DeadLettersGetDeadLettersData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<DeadLettersGetDeadLettersData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<DeadLettersGetDeadLettersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await deadLettersGetDeadLetters({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: deadLettersGetDeadLettersInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Post Discard
 */
export const deadLettersPostDiscardMutation = (
  options?: Partial<Options<DeadLettersPostDiscardData>>,
): UseMutationOptions<
  DeadLettersPostDiscardResponse,
  DeadLettersPostDiscardError,
  Options<DeadLettersPostDiscardData>
> => {
  const mutationOptions: UseMutationOptions<
    DeadLettersPostDiscardResponse,
    DeadLettersPostDiscardError,
    Options<DeadLettersPostDiscardData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deadLettersPostDiscard({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Post Retry
 */
export const deadLettersPostRetryMutation = (
  options?: Partial<Options<DeadLettersPostRetryData>>,
): UseMutationOptions<
  DeadLettersPostRetryResponse,
  DeadLettersPostRetryError,
  Options<DeadLettersPostRetryData>
> => {
  const mutationOptions: UseMutationOptions<
    DeadLettersPostRetryResponse,
    DeadLettersPostRetryError,
    Options<DeadLettersPostRetryData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deadLettersPostRetry({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const authListKeysQueryKey = (options?: Options<AuthListKeysData>) =>
  createQueryKey("authListKeys", options);

/**
 * List Keys
 *
 * The workspace's API keys: name, prefix, scopes, projects, created, expires, last
 * used, revoked; never the secret.
 */
export const authListKeysOptions = (options?: Options<AuthListKeysData>) =>
  queryOptions<
    AuthListKeysResponse,
    AuthListKeysError,
    AuthListKeysResponse,
    ReturnType<typeof authListKeysQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authListKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authListKeysQueryKey(options),
  });

export const authListKeysInfiniteQueryKey = (
  options?: Options<AuthListKeysData>,
): QueryKey<Options<AuthListKeysData>> =>
  createQueryKey("authListKeys", options, true);

/**
 * List Keys
 *
 * The workspace's API keys: name, prefix, scopes, projects, created, expires, last
 * used, revoked; never the secret.
 */
export const authListKeysInfiniteOptions = (
  options?: Options<AuthListKeysData>,
) => {
  const opts = infiniteQueryOptions<
    AuthListKeysResponse,
    AuthListKeysError,
    InfiniteData<AuthListKeysResponse>,
    QueryKey<Options<AuthListKeysData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<AuthListKeysData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<AuthListKeysData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await authListKeys({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: authListKeysInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Create Key
 *
 * A new key; the response shows `key` once. 422 `unknown_scope`.
 */
export const authCreateKeyMutation = (
  options?: Partial<Options<AuthCreateKeyData>>,
): UseMutationOptions<
  AuthCreateKeyResponse,
  AuthCreateKeyError,
  Options<AuthCreateKeyData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthCreateKeyResponse,
    AuthCreateKeyError,
    Options<AuthCreateKeyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authCreateKey({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Revoke Key
 *
 * Revokes the key: every process refuses it within a second.
 */
export const authRevokeKeyMutation = (
  options?: Partial<Options<AuthRevokeKeyData>>,
): UseMutationOptions<
  AuthRevokeKeyResponse,
  AuthRevokeKeyError,
  Options<AuthRevokeKeyData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthRevokeKeyResponse,
    AuthRevokeKeyError,
    Options<AuthRevokeKeyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authRevokeKey({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Rotate Key
 *
 * A new secret on the same key, shown once; the old one stops at once or after
 * `grace_minutes` (0 to 1,440). 409 `key_revoked`.
 */
export const authRotateKeyMutation = (
  options?: Partial<Options<AuthRotateKeyData>>,
): UseMutationOptions<
  AuthRotateKeyResponse,
  AuthRotateKeyError,
  Options<AuthRotateKeyData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthRotateKeyResponse,
    AuthRotateKeyError,
    Options<AuthRotateKeyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authRotateKey({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const projectsListProjectsQueryKey = (
  options?: Options<ProjectsListProjectsData>,
) => createQueryKey("projectsListProjects", options);

/**
 * List Projects
 *
 * Projects in board order; archived ones with `include_archived=true`.
 */
export const projectsListProjectsOptions = (
  options?: Options<ProjectsListProjectsData>,
) =>
  queryOptions<
    ProjectsListProjectsResponse,
    ProjectsListProjectsError,
    ProjectsListProjectsResponse,
    ReturnType<typeof projectsListProjectsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await projectsListProjects({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: projectsListProjectsQueryKey(options),
  });

export const projectsListProjectsInfiniteQueryKey = (
  options?: Options<ProjectsListProjectsData>,
): QueryKey<Options<ProjectsListProjectsData>> =>
  createQueryKey("projectsListProjects", options, true);

/**
 * List Projects
 *
 * Projects in board order; archived ones with `include_archived=true`.
 */
export const projectsListProjectsInfiniteOptions = (
  options?: Options<ProjectsListProjectsData>,
) => {
  const opts = infiniteQueryOptions<
    ProjectsListProjectsResponse,
    ProjectsListProjectsError,
    InfiniteData<ProjectsListProjectsResponse>,
    QueryKey<Options<ProjectsListProjectsData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<ProjectsListProjectsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ProjectsListProjectsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await projectsListProjects({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: projectsListProjectsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Create Project
 */
export const projectsCreateProjectMutation = (
  options?: Partial<Options<ProjectsCreateProjectData>>,
): UseMutationOptions<
  ProjectsCreateProjectResponse,
  ProjectsCreateProjectError,
  Options<ProjectsCreateProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    ProjectsCreateProjectResponse,
    ProjectsCreateProjectError,
    Options<ProjectsCreateProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await projectsCreateProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const projectsGetProjectQueryKey = (
  options: Options<ProjectsGetProjectData>,
) => createQueryKey("projectsGetProject", options);

/**
 * Get Project
 */
export const projectsGetProjectOptions = (
  options: Options<ProjectsGetProjectData>,
) =>
  queryOptions<
    ProjectsGetProjectResponse,
    ProjectsGetProjectError,
    ProjectsGetProjectResponse,
    ReturnType<typeof projectsGetProjectQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await projectsGetProject({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: projectsGetProjectQueryKey(options),
  });

/**
 * Update Project
 */
export const projectsUpdateProjectMutation = (
  options?: Partial<Options<ProjectsUpdateProjectData>>,
): UseMutationOptions<
  ProjectsUpdateProjectResponse,
  ProjectsUpdateProjectError,
  Options<ProjectsUpdateProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    ProjectsUpdateProjectResponse,
    ProjectsUpdateProjectError,
    Options<ProjectsUpdateProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await projectsUpdateProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Archive Project
 */
export const projectsArchiveProjectMutation = (
  options?: Partial<Options<ProjectsArchiveProjectData>>,
): UseMutationOptions<
  ProjectsArchiveProjectResponse,
  ProjectsArchiveProjectError,
  Options<ProjectsArchiveProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    ProjectsArchiveProjectResponse,
    ProjectsArchiveProjectError,
    Options<ProjectsArchiveProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await projectsArchiveProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reorder Project
 *
 * Moves the project between two neighbours (either may be null: an open end).
 */
export const projectsReorderProjectMutation = (
  options?: Partial<Options<ProjectsReorderProjectData>>,
): UseMutationOptions<
  ProjectsReorderProjectResponse,
  ProjectsReorderProjectError,
  Options<ProjectsReorderProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    ProjectsReorderProjectResponse,
    ProjectsReorderProjectError,
    Options<ProjectsReorderProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await projectsReorderProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Unarchive Project
 */
export const projectsUnarchiveProjectMutation = (
  options?: Partial<Options<ProjectsUnarchiveProjectData>>,
): UseMutationOptions<
  ProjectsUnarchiveProjectResponse,
  ProjectsUnarchiveProjectError,
  Options<ProjectsUnarchiveProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    ProjectsUnarchiveProjectResponse,
    ProjectsUnarchiveProjectError,
    Options<ProjectsUnarchiveProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await projectsUnarchiveProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const settingsGetWorkspaceSettingsQueryKey = (
  options?: Options<SettingsGetWorkspaceSettingsData>,
) => createQueryKey("settingsGetWorkspaceSettings", options);

/**
 * Get Workspace Settings
 */
export const settingsGetWorkspaceSettingsOptions = (
  options?: Options<SettingsGetWorkspaceSettingsData>,
) =>
  queryOptions<
    SettingsGetWorkspaceSettingsResponse,
    SettingsGetWorkspaceSettingsError,
    SettingsGetWorkspaceSettingsResponse,
    ReturnType<typeof settingsGetWorkspaceSettingsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await settingsGetWorkspaceSettings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: settingsGetWorkspaceSettingsQueryKey(options),
  });

/**
 * Put Workspace Settings
 */
export const settingsPutWorkspaceSettingsMutation = (
  options?: Partial<Options<SettingsPutWorkspaceSettingsData>>,
): UseMutationOptions<
  SettingsPutWorkspaceSettingsResponse,
  SettingsPutWorkspaceSettingsError,
  Options<SettingsPutWorkspaceSettingsData>
> => {
  const mutationOptions: UseMutationOptions<
    SettingsPutWorkspaceSettingsResponse,
    SettingsPutWorkspaceSettingsError,
    Options<SettingsPutWorkspaceSettingsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await settingsPutWorkspaceSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Setup
 *
 * First run: creates the workspace and its owner and shows the TOTP secret once.
 * 409 `already_set_up`; 403 `signup_disabled` in hosted mode.
 */
export const authSetupMutation = (
  options?: Partial<Options<AuthSetupData>>,
): UseMutationOptions<
  AuthSetupResponse,
  AuthSetupError,
  Options<AuthSetupData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthSetupResponse,
    AuthSetupError,
    Options<AuthSetupData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authSetup({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Setup Totp
 *
 * Confirms the first code; completes setup and signs the owner in.
 */
export const authSetupTotpMutation = (
  options?: Partial<Options<AuthSetupTotpData>>,
): UseMutationOptions<
  AuthSetupTotpResponse,
  AuthSetupTotpError,
  Options<AuthSetupTotpData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthSetupTotpResponse,
    AuthSetupTotpError,
    Options<AuthSetupTotpData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authSetupTotp({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usageGetUsageQueryKey = (options: Options<UsageGetUsageData>) =>
  createQueryKey("usageGetUsage", options);

/**
 * Get Usage
 */
export const usageGetUsageOptions = (options: Options<UsageGetUsageData>) =>
  queryOptions<
    UsageGetUsageResponse,
    UsageGetUsageError,
    UsageGetUsageResponse,
    ReturnType<typeof usageGetUsageQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usageGetUsage({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usageGetUsageQueryKey(options),
  });
