// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  agentsCheckProfileHealth,
  agentsCreateRunner,
  agentsListProfiles,
  agentsListRunners,
  agentsRegisterProfile,
  agentsRotateRunnerToken,
  agentsUpdateProfile,
  auditExportAuditCsv,
  auditListAudit,
  authConfirmTotpEnrolment,
  authCreateKey,
  authGetAccount,
  authListKeys,
  authListSessions,
  authLogin,
  authLogout,
  authRevokeKey,
  authRevokeSession,
  authRotateKey,
  authSetup,
  authSetupTotp,
  authSignOutOtherDevices,
  authStartTotpEnrolment,
  authTotp,
  deadLettersGetDeadLetters,
  deadLettersPostDiscard,
  deadLettersPostRetry,
  healthLive,
  healthReady,
  type Options,
  projectsArchiveProject,
  projectsCreateProject,
  projectsGetProject,
  projectsListProjects,
  projectsReorderProject,
  projectsUnarchiveProject,
  projectsUpdateProject,
  settingsGetSection,
  settingsGetWorkspaceSettings,
  settingsListModules,
  settingsPutSection,
  settingsPutWorkspaceSettings,
  settingsSetModule,
  tasksAddComment,
  tasksChangeStatus,
  tasksCreateTask,
  tasksGetBoard,
  tasksGetColumns,
  tasksGetReviewCount,
  tasksGetTask,
  tasksLinkContextItem,
  tasksListReviewKinds,
  tasksListTasks,
  tasksMoveTask,
  tasksPutColumns,
  tasksUpdateTask,
  usageGetUsage,
} from "../sdk.gen";
import type {
  AgentsCheckProfileHealthData,
  AgentsCheckProfileHealthError,
  AgentsCheckProfileHealthResponse,
  AgentsCreateRunnerData,
  AgentsCreateRunnerError,
  AgentsCreateRunnerResponse,
  AgentsListProfilesData,
  AgentsListProfilesError,
  AgentsListProfilesResponse,
  AgentsListRunnersData,
  AgentsListRunnersError,
  AgentsListRunnersResponse,
  AgentsRegisterProfileData,
  AgentsRegisterProfileError,
  AgentsRegisterProfileResponse,
  AgentsRotateRunnerTokenData,
  AgentsRotateRunnerTokenError,
  AgentsRotateRunnerTokenResponse,
  AgentsUpdateProfileData,
  AgentsUpdateProfileError,
  AgentsUpdateProfileResponse,
  AuditExportAuditCsvData,
  AuditExportAuditCsvError,
  AuditListAuditData,
  AuditListAuditError,
  AuditListAuditResponse,
  AuthConfirmTotpEnrolmentData,
  AuthConfirmTotpEnrolmentError,
  AuthConfirmTotpEnrolmentResponse,
  AuthCreateKeyData,
  AuthCreateKeyError,
  AuthCreateKeyResponse,
  AuthGetAccountData,
  AuthGetAccountError,
  AuthGetAccountResponse,
  AuthListKeysData,
  AuthListKeysError,
  AuthListKeysResponse,
  AuthListSessionsData,
  AuthListSessionsError,
  AuthListSessionsResponse,
  AuthLoginData,
  AuthLoginError,
  AuthLoginResponse,
  AuthLogoutData,
  AuthLogoutError,
  AuthLogoutResponse,
  AuthRevokeKeyData,
  AuthRevokeKeyError,
  AuthRevokeKeyResponse,
  AuthRevokeSessionData,
  AuthRevokeSessionError,
  AuthRevokeSessionResponse,
  AuthRotateKeyData,
  AuthRotateKeyError,
  AuthRotateKeyResponse,
  AuthSetupData,
  AuthSetupError,
  AuthSetupResponse,
  AuthSetupTotpData,
  AuthSetupTotpError,
  AuthSetupTotpResponse,
  AuthSignOutOtherDevicesData,
  AuthSignOutOtherDevicesError,
  AuthSignOutOtherDevicesResponse,
  AuthStartTotpEnrolmentData,
  AuthStartTotpEnrolmentError,
  AuthStartTotpEnrolmentResponse,
  AuthTotpData,
  AuthTotpError,
  AuthTotpResponse,
  DeadLettersGetDeadLettersData,
  DeadLettersGetDeadLettersError,
  DeadLettersGetDeadLettersResponse,
  DeadLettersPostDiscardData,
  DeadLettersPostDiscardError,
  DeadLettersPostDiscardResponse,
  DeadLettersPostRetryData,
  DeadLettersPostRetryError,
  DeadLettersPostRetryResponse,
  HealthLiveData,
  HealthLiveResponse,
  HealthReadyData,
  ProjectsArchiveProjectData,
  ProjectsArchiveProjectError,
  ProjectsArchiveProjectResponse,
  ProjectsCreateProjectData,
  ProjectsCreateProjectError,
  ProjectsCreateProjectResponse,
  ProjectsGetProjectData,
  ProjectsGetProjectError,
  ProjectsGetProjectResponse,
  ProjectsListProjectsData,
  ProjectsListProjectsError,
  ProjectsListProjectsResponse,
  ProjectsReorderProjectData,
  ProjectsReorderProjectError,
  ProjectsReorderProjectResponse,
  ProjectsUnarchiveProjectData,
  ProjectsUnarchiveProjectError,
  ProjectsUnarchiveProjectResponse,
  ProjectsUpdateProjectData,
  ProjectsUpdateProjectError,
  ProjectsUpdateProjectResponse,
  SettingsGetSectionData,
  SettingsGetSectionError,
  SettingsGetSectionResponse,
  SettingsGetWorkspaceSettingsData,
  SettingsGetWorkspaceSettingsError,
  SettingsGetWorkspaceSettingsResponse,
  SettingsListModulesData,
  SettingsListModulesError,
  SettingsListModulesResponse,
  SettingsPutSectionData,
  SettingsPutSectionError,
  SettingsPutSectionResponse,
  SettingsPutWorkspaceSettingsData,
  SettingsPutWorkspaceSettingsError,
  SettingsPutWorkspaceSettingsResponse,
  SettingsSetModuleData,
  SettingsSetModuleError,
  SettingsSetModuleResponse,
  TasksAddCommentData,
  TasksAddCommentError,
  TasksAddCommentResponse,
  TasksChangeStatusData,
  TasksChangeStatusError,
  TasksChangeStatusResponse,
  TasksCreateTaskData,
  TasksCreateTaskError,
  TasksCreateTaskResponse,
  TasksGetBoardData,
  TasksGetBoardError,
  TasksGetBoardResponse,
  TasksGetColumnsData,
  TasksGetColumnsError,
  TasksGetColumnsResponse,
  TasksGetReviewCountData,
  TasksGetReviewCountError,
  TasksGetReviewCountResponse,
  TasksGetTaskData,
  TasksGetTaskError,
  TasksGetTaskResponse,
  TasksLinkContextItemData,
  TasksLinkContextItemError,
  TasksLinkContextItemResponse,
  TasksListReviewKindsData,
  TasksListReviewKindsError,
  TasksListReviewKindsResponse,
  TasksListTasksData,
  TasksListTasksError,
  TasksListTasksResponse,
  TasksMoveTaskData,
  TasksMoveTaskError,
  TasksMoveTaskResponse,
  TasksPutColumnsData,
  TasksPutColumnsError,
  TasksPutColumnsResponse,
  TasksUpdateTaskData,
  TasksUpdateTaskError,
  TasksUpdateTaskResponse,
  UsageGetUsageData,
  UsageGetUsageError,
  UsageGetUsageResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthLiveQueryKey = (options?: Options<HealthLiveData>) =>
  createQueryKey("healthLive", options);

/**
 * Live
 */
export const healthLiveOptions = (options?: Options<HealthLiveData>) =>
  queryOptions<
    HealthLiveResponse,
    DefaultError,
    HealthLiveResponse,
    ReturnType<typeof healthLiveQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthLive({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthLiveQueryKey(options),
  });

export const healthReadyQueryKey = (options?: Options<HealthReadyData>) =>
  createQueryKey("healthReady", options);

/**
 * Ready
 */
export const healthReadyOptions = (options?: Options<HealthReadyData>) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof healthReadyQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthReady({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthReadyQueryKey(options),
  });

export const agentsListProfilesQueryKey = (
  options?: Options<AgentsListProfilesData>,
) => createQueryKey("agentsListProfiles", options);

/**
 * List Profiles
 *
 * Agent profiles by name, with their last health check.
 */
export const agentsListProfilesOptions = (
  options?: Options<AgentsListProfilesData>,
) =>
  queryOptions<
    AgentsListProfilesResponse,
    AgentsListProfilesError,
    AgentsListProfilesResponse,
    ReturnType<typeof agentsListProfilesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await agentsListProfiles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: agentsListProfilesQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const agentsListProfilesInfiniteQueryKey = (
  options?: Options<AgentsListProfilesData>,
): QueryKey<Options<AgentsListProfilesData>> =>
  createQueryKey("agentsListProfiles", options, true);

/**
 * List Profiles
 *
 * Agent profiles by name, with their last health check.
 */
export const agentsListProfilesInfiniteOptions = (
  options?: Options<AgentsListProfilesData>,
) => {
  const opts = infiniteQueryOptions<
    AgentsListProfilesResponse,
    AgentsListProfilesError,
    InfiniteData<AgentsListProfilesResponse>,
    QueryKey<Options<AgentsListProfilesData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<AgentsListProfilesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<AgentsListProfilesData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await agentsListProfiles({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: agentsListProfilesInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Register Profile
 *
 * Register a Hermes profile. 422 `invalid_profile_name`, `invalid_profile`; 404 for
 * an unknown runner or project; 409 `master_exists`, `project_agent_exists`,
 * `profile_exists`.
 */
export const agentsRegisterProfileMutation = (
  options?: Partial<Options<AgentsRegisterProfileData>>,
): UseMutationOptions<
  AgentsRegisterProfileResponse,
  AgentsRegisterProfileError,
  Options<AgentsRegisterProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    AgentsRegisterProfileResponse,
    AgentsRegisterProfileError,
    Options<AgentsRegisterProfileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await agentsRegisterProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Profile
 *
 * Move a profile to another runner or endpoint, or pause it. 409 `stale_version`.
 */
export const agentsUpdateProfileMutation = (
  options?: Partial<Options<AgentsUpdateProfileData>>,
): UseMutationOptions<
  AgentsUpdateProfileResponse,
  AgentsUpdateProfileError,
  Options<AgentsUpdateProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    AgentsUpdateProfileResponse,
    AgentsUpdateProfileError,
    Options<AgentsUpdateProfileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await agentsUpdateProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Check Profile Health
 *
 * Ask the profile's runner (or endpoint) for its health; the answer lands in the
 * profile's `health` (reachable, authenticated, version).
 */
export const agentsCheckProfileHealthMutation = (
  options?: Partial<Options<AgentsCheckProfileHealthData>>,
): UseMutationOptions<
  AgentsCheckProfileHealthResponse,
  AgentsCheckProfileHealthError,
  Options<AgentsCheckProfileHealthData>
> => {
  const mutationOptions: UseMutationOptions<
    AgentsCheckProfileHealthResponse,
    AgentsCheckProfileHealthError,
    Options<AgentsCheckProfileHealthData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await agentsCheckProfileHealth({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const auditListAuditQueryKey = (options?: Options<AuditListAuditData>) =>
  createQueryKey("auditListAudit", options);

/**
 * List Audit
 *
 * The workspace's audit log, newest first.
 */
export const auditListAuditOptions = (options?: Options<AuditListAuditData>) =>
  queryOptions<
    AuditListAuditResponse,
    AuditListAuditError,
    AuditListAuditResponse,
    ReturnType<typeof auditListAuditQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await auditListAudit({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: auditListAuditQueryKey(options),
  });

export const auditListAuditInfiniteQueryKey = (
  options?: Options<AuditListAuditData>,
): QueryKey<Options<AuditListAuditData>> =>
  createQueryKey("auditListAudit", options, true);

/**
 * List Audit
 *
 * The workspace's audit log, newest first.
 */
export const auditListAuditInfiniteOptions = (
  options?: Options<AuditListAuditData>,
) => {
  const opts = infiniteQueryOptions<
    AuditListAuditResponse,
    AuditListAuditError,
    InfiniteData<AuditListAuditResponse>,
    QueryKey<Options<AuditListAuditData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<AuditListAuditData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<AuditListAuditData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await auditListAudit({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: auditListAuditInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

export const auditExportAuditCsvQueryKey = (
  options?: Options<AuditExportAuditCsvData>,
) => createQueryKey("auditExportAuditCsv", options);

/**
 * Export Audit Csv
 *
 * The workspace's audit log as CSV, newest first; the export is audited.
 */
export const auditExportAuditCsvOptions = (
  options?: Options<AuditExportAuditCsvData>,
) =>
  queryOptions<
    unknown,
    AuditExportAuditCsvError,
    unknown,
    ReturnType<typeof auditExportAuditCsvQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await auditExportAuditCsv({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: auditExportAuditCsvQueryKey(options),
  });

export const authGetAccountQueryKey = (options?: Options<AuthGetAccountData>) =>
  createQueryKey("authGetAccount", options);

/**
 * Get Account
 *
 * The signed-in user's email and second factor.
 */
export const authGetAccountOptions = (options?: Options<AuthGetAccountData>) =>
  queryOptions<
    AuthGetAccountResponse,
    AuthGetAccountError,
    AuthGetAccountResponse,
    ReturnType<typeof authGetAccountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authGetAccount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authGetAccountQueryKey(options),
  });

/**
 * Login
 *
 * The password step: answers `{"step": "totp", "preauth": ...}` and sets no cookie.
 */
export const authLoginMutation = (
  options?: Partial<Options<AuthLoginData>>,
): UseMutationOptions<
  AuthLoginResponse,
  AuthLoginError,
  Options<AuthLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthLoginResponse,
    AuthLoginError,
    Options<AuthLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Logout
 *
 * Ends this session and clears its cookies.
 */
export const authLogoutMutation = (
  options?: Partial<Options<AuthLogoutData>>,
): UseMutationOptions<
  AuthLogoutResponse,
  AuthLogoutError,
  Options<AuthLogoutData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthLogoutResponse,
    AuthLogoutError,
    Options<AuthLogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authLogout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Sign Out Other Devices
 *
 * Revokes every session of this user but the calling one (R-21).
 */
export const authSignOutOtherDevicesMutation = (
  options?: Partial<Options<AuthSignOutOtherDevicesData>>,
): UseMutationOptions<
  AuthSignOutOtherDevicesResponse,
  AuthSignOutOtherDevicesError,
  Options<AuthSignOutOtherDevicesData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthSignOutOtherDevicesResponse,
    AuthSignOutOtherDevicesError,
    Options<AuthSignOutOtherDevicesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authSignOutOtherDevices({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const authListSessionsQueryKey = (
  options?: Options<AuthListSessionsData>,
) => createQueryKey("authListSessions", options);

/**
 * List Sessions
 *
 * This user's signed-in devices, newest first, the calling one `current`.
 */
export const authListSessionsOptions = (
  options?: Options<AuthListSessionsData>,
) =>
  queryOptions<
    AuthListSessionsResponse,
    AuthListSessionsError,
    AuthListSessionsResponse,
    ReturnType<typeof authListSessionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authListSessions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authListSessionsQueryKey(options),
  });

export const authListSessionsInfiniteQueryKey = (
  options?: Options<AuthListSessionsData>,
): QueryKey<Options<AuthListSessionsData>> =>
  createQueryKey("authListSessions", options, true);

/**
 * List Sessions
 *
 * This user's signed-in devices, newest first, the calling one `current`.
 */
export const authListSessionsInfiniteOptions = (
  options?: Options<AuthListSessionsData>,
) => {
  const opts = infiniteQueryOptions<
    AuthListSessionsResponse,
    AuthListSessionsError,
    InfiniteData<AuthListSessionsResponse>,
    QueryKey<Options<AuthListSessionsData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<AuthListSessionsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<AuthListSessionsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await authListSessions({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: authListSessionsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Revoke Session
 *
 * Revokes one of this user's sessions.
 */
export const authRevokeSessionMutation = (
  options?: Partial<Options<AuthRevokeSessionData>>,
): UseMutationOptions<
  AuthRevokeSessionResponse,
  AuthRevokeSessionError,
  Options<AuthRevokeSessionData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthRevokeSessionResponse,
    AuthRevokeSessionError,
    Options<AuthRevokeSessionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authRevokeSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Totp
 *
 * The TOTP step: sets the session and CSRF cookies.
 */
export const authTotpMutation = (
  options?: Partial<Options<AuthTotpData>>,
): UseMutationOptions<
  AuthTotpResponse,
  AuthTotpError,
  Options<AuthTotpData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthTotpResponse,
    AuthTotpError,
    Options<AuthTotpData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authTotp({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Start Totp Enrolment
 *
 * With the password: a new TOTP secret (shown once) and its enrolment token. 401
 * `invalid_credentials`, 429 `locked_out`.
 */
export const authStartTotpEnrolmentMutation = (
  options?: Partial<Options<AuthStartTotpEnrolmentData>>,
): UseMutationOptions<
  AuthStartTotpEnrolmentResponse,
  AuthStartTotpEnrolmentError,
  Options<AuthStartTotpEnrolmentData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthStartTotpEnrolmentResponse,
    AuthStartTotpEnrolmentError,
    Options<AuthStartTotpEnrolmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authStartTotpEnrolment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Confirm Totp Enrolment
 *
 * A code from the new secret replaces the old one. 401 `invalid_code`,
 * `invalid_enrol_token`.
 */
export const authConfirmTotpEnrolmentMutation = (
  options?: Partial<Options<AuthConfirmTotpEnrolmentData>>,
): UseMutationOptions<
  AuthConfirmTotpEnrolmentResponse,
  AuthConfirmTotpEnrolmentError,
  Options<AuthConfirmTotpEnrolmentData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthConfirmTotpEnrolmentResponse,
    AuthConfirmTotpEnrolmentError,
    Options<AuthConfirmTotpEnrolmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authConfirmTotpEnrolment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deadLettersGetDeadLettersQueryKey = (
  options?: Options<DeadLettersGetDeadLettersData>,
) => createQueryKey("deadLettersGetDeadLetters", options);

/**
 * Get Dead Letters
 */
export const deadLettersGetDeadLettersOptions = (
  options?: Options<DeadLettersGetDeadLettersData>,
) =>
  queryOptions<
    DeadLettersGetDeadLettersResponse,
    DeadLettersGetDeadLettersError,
    DeadLettersGetDeadLettersResponse,
    ReturnType<typeof deadLettersGetDeadLettersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await deadLettersGetDeadLetters({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: deadLettersGetDeadLettersQueryKey(options),
  });

export const deadLettersGetDeadLettersInfiniteQueryKey = (
  options?: Options<DeadLettersGetDeadLettersData>,
): QueryKey<Options<DeadLettersGetDeadLettersData>> =>
  createQueryKey("deadLettersGetDeadLetters", options, true);

/**
 * Get Dead Letters
 */
export const deadLettersGetDeadLettersInfiniteOptions = (
  options?: Options<DeadLettersGetDeadLettersData>,
) => {
  const opts = infiniteQueryOptions<
    DeadLettersGetDeadLettersResponse,
    DeadLettersGetDeadLettersError,
    InfiniteData<DeadLettersGetDeadLettersResponse>,
    QueryKey<Options<DeadLettersGetDeadLettersData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<DeadLettersGetDeadLettersData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<DeadLettersGetDeadLettersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await deadLettersGetDeadLetters({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: deadLettersGetDeadLettersInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Post Discard
 */
export const deadLettersPostDiscardMutation = (
  options?: Partial<Options<DeadLettersPostDiscardData>>,
): UseMutationOptions<
  DeadLettersPostDiscardResponse,
  DeadLettersPostDiscardError,
  Options<DeadLettersPostDiscardData>
> => {
  const mutationOptions: UseMutationOptions<
    DeadLettersPostDiscardResponse,
    DeadLettersPostDiscardError,
    Options<DeadLettersPostDiscardData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deadLettersPostDiscard({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Post Retry
 */
export const deadLettersPostRetryMutation = (
  options?: Partial<Options<DeadLettersPostRetryData>>,
): UseMutationOptions<
  DeadLettersPostRetryResponse,
  DeadLettersPostRetryError,
  Options<DeadLettersPostRetryData>
> => {
  const mutationOptions: UseMutationOptions<
    DeadLettersPostRetryResponse,
    DeadLettersPostRetryError,
    Options<DeadLettersPostRetryData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deadLettersPostRetry({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const authListKeysQueryKey = (options?: Options<AuthListKeysData>) =>
  createQueryKey("authListKeys", options);

/**
 * List Keys
 *
 * The workspace's API keys: name, prefix, scopes, projects, created, expires, last
 * used, revoked; never the secret.
 */
export const authListKeysOptions = (options?: Options<AuthListKeysData>) =>
  queryOptions<
    AuthListKeysResponse,
    AuthListKeysError,
    AuthListKeysResponse,
    ReturnType<typeof authListKeysQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authListKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authListKeysQueryKey(options),
  });

export const authListKeysInfiniteQueryKey = (
  options?: Options<AuthListKeysData>,
): QueryKey<Options<AuthListKeysData>> =>
  createQueryKey("authListKeys", options, true);

/**
 * List Keys
 *
 * The workspace's API keys: name, prefix, scopes, projects, created, expires, last
 * used, revoked; never the secret.
 */
export const authListKeysInfiniteOptions = (
  options?: Options<AuthListKeysData>,
) => {
  const opts = infiniteQueryOptions<
    AuthListKeysResponse,
    AuthListKeysError,
    InfiniteData<AuthListKeysResponse>,
    QueryKey<Options<AuthListKeysData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<AuthListKeysData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<AuthListKeysData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await authListKeys({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: authListKeysInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Create Key
 *
 * A new key; the response shows `key` once. 422 `unknown_scope`.
 */
export const authCreateKeyMutation = (
  options?: Partial<Options<AuthCreateKeyData>>,
): UseMutationOptions<
  AuthCreateKeyResponse,
  AuthCreateKeyError,
  Options<AuthCreateKeyData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthCreateKeyResponse,
    AuthCreateKeyError,
    Options<AuthCreateKeyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authCreateKey({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Revoke Key
 *
 * Revokes the key: every process refuses it within a second.
 */
export const authRevokeKeyMutation = (
  options?: Partial<Options<AuthRevokeKeyData>>,
): UseMutationOptions<
  AuthRevokeKeyResponse,
  AuthRevokeKeyError,
  Options<AuthRevokeKeyData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthRevokeKeyResponse,
    AuthRevokeKeyError,
    Options<AuthRevokeKeyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authRevokeKey({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Rotate Key
 *
 * A new secret on the same key, shown once; the old one stops at once or after
 * `grace_minutes` (0 to 1,440). 409 `key_revoked`.
 */
export const authRotateKeyMutation = (
  options?: Partial<Options<AuthRotateKeyData>>,
): UseMutationOptions<
  AuthRotateKeyResponse,
  AuthRotateKeyError,
  Options<AuthRotateKeyData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthRotateKeyResponse,
    AuthRotateKeyError,
    Options<AuthRotateKeyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authRotateKey({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const projectsListProjectsQueryKey = (
  options?: Options<ProjectsListProjectsData>,
) => createQueryKey("projectsListProjects", options);

/**
 * List Projects
 *
 * Projects in board order; archived ones with `include_archived=true`.
 */
export const projectsListProjectsOptions = (
  options?: Options<ProjectsListProjectsData>,
) =>
  queryOptions<
    ProjectsListProjectsResponse,
    ProjectsListProjectsError,
    ProjectsListProjectsResponse,
    ReturnType<typeof projectsListProjectsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await projectsListProjects({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: projectsListProjectsQueryKey(options),
  });

export const projectsListProjectsInfiniteQueryKey = (
  options?: Options<ProjectsListProjectsData>,
): QueryKey<Options<ProjectsListProjectsData>> =>
  createQueryKey("projectsListProjects", options, true);

/**
 * List Projects
 *
 * Projects in board order; archived ones with `include_archived=true`.
 */
export const projectsListProjectsInfiniteOptions = (
  options?: Options<ProjectsListProjectsData>,
) => {
  const opts = infiniteQueryOptions<
    ProjectsListProjectsResponse,
    ProjectsListProjectsError,
    InfiniteData<ProjectsListProjectsResponse>,
    QueryKey<Options<ProjectsListProjectsData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<ProjectsListProjectsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ProjectsListProjectsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await projectsListProjects({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: projectsListProjectsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Create Project
 */
export const projectsCreateProjectMutation = (
  options?: Partial<Options<ProjectsCreateProjectData>>,
): UseMutationOptions<
  ProjectsCreateProjectResponse,
  ProjectsCreateProjectError,
  Options<ProjectsCreateProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    ProjectsCreateProjectResponse,
    ProjectsCreateProjectError,
    Options<ProjectsCreateProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await projectsCreateProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const projectsGetProjectQueryKey = (
  options: Options<ProjectsGetProjectData>,
) => createQueryKey("projectsGetProject", options);

/**
 * Get Project
 */
export const projectsGetProjectOptions = (
  options: Options<ProjectsGetProjectData>,
) =>
  queryOptions<
    ProjectsGetProjectResponse,
    ProjectsGetProjectError,
    ProjectsGetProjectResponse,
    ReturnType<typeof projectsGetProjectQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await projectsGetProject({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: projectsGetProjectQueryKey(options),
  });

/**
 * Update Project
 */
export const projectsUpdateProjectMutation = (
  options?: Partial<Options<ProjectsUpdateProjectData>>,
): UseMutationOptions<
  ProjectsUpdateProjectResponse,
  ProjectsUpdateProjectError,
  Options<ProjectsUpdateProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    ProjectsUpdateProjectResponse,
    ProjectsUpdateProjectError,
    Options<ProjectsUpdateProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await projectsUpdateProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Archive Project
 */
export const projectsArchiveProjectMutation = (
  options?: Partial<Options<ProjectsArchiveProjectData>>,
): UseMutationOptions<
  ProjectsArchiveProjectResponse,
  ProjectsArchiveProjectError,
  Options<ProjectsArchiveProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    ProjectsArchiveProjectResponse,
    ProjectsArchiveProjectError,
    Options<ProjectsArchiveProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await projectsArchiveProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const tasksGetBoardQueryKey = (options: Options<TasksGetBoardData>) =>
  createQueryKey("tasksGetBoard", options);

/**
 * Get Board
 *
 * The kanban: columns, cards and each card's checklist (FR-3.4).
 */
export const tasksGetBoardOptions = (options: Options<TasksGetBoardData>) =>
  queryOptions<
    TasksGetBoardResponse,
    TasksGetBoardError,
    TasksGetBoardResponse,
    ReturnType<typeof tasksGetBoardQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await tasksGetBoard({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: tasksGetBoardQueryKey(options),
  });

export const tasksGetColumnsQueryKey = (
  options: Options<TasksGetColumnsData>,
) => createQueryKey("tasksGetColumns", options);

/**
 * Get Columns
 */
export const tasksGetColumnsOptions = (options: Options<TasksGetColumnsData>) =>
  queryOptions<
    TasksGetColumnsResponse,
    TasksGetColumnsError,
    TasksGetColumnsResponse,
    ReturnType<typeof tasksGetColumnsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await tasksGetColumns({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: tasksGetColumnsQueryKey(options),
  });

/**
 * Put Columns
 *
 * Renames, reorders, adds and removes columns in one request; every status keeps at
 * least one column (422 `status_without_column`).
 */
export const tasksPutColumnsMutation = (
  options?: Partial<Options<TasksPutColumnsData>>,
): UseMutationOptions<
  TasksPutColumnsResponse,
  TasksPutColumnsError,
  Options<TasksPutColumnsData>
> => {
  const mutationOptions: UseMutationOptions<
    TasksPutColumnsResponse,
    TasksPutColumnsError,
    Options<TasksPutColumnsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await tasksPutColumns({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reorder Project
 *
 * Moves the project between two neighbours (either may be null: an open end).
 */
export const projectsReorderProjectMutation = (
  options?: Partial<Options<ProjectsReorderProjectData>>,
): UseMutationOptions<
  ProjectsReorderProjectResponse,
  ProjectsReorderProjectError,
  Options<ProjectsReorderProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    ProjectsReorderProjectResponse,
    ProjectsReorderProjectError,
    Options<ProjectsReorderProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await projectsReorderProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Unarchive Project
 */
export const projectsUnarchiveProjectMutation = (
  options?: Partial<Options<ProjectsUnarchiveProjectData>>,
): UseMutationOptions<
  ProjectsUnarchiveProjectResponse,
  ProjectsUnarchiveProjectError,
  Options<ProjectsUnarchiveProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    ProjectsUnarchiveProjectResponse,
    ProjectsUnarchiveProjectError,
    Options<ProjectsUnarchiveProjectData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await projectsUnarchiveProject({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const tasksGetReviewCountQueryKey = (
  options?: Options<TasksGetReviewCountData>,
) => createQueryKey("tasksGetReviewCount", options);

/**
 * Get Review Count
 *
 * The badge: review items waiting now (not decided, trashed or snoozed).
 */
export const tasksGetReviewCountOptions = (
  options?: Options<TasksGetReviewCountData>,
) =>
  queryOptions<
    TasksGetReviewCountResponse,
    TasksGetReviewCountError,
    TasksGetReviewCountResponse,
    ReturnType<typeof tasksGetReviewCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await tasksGetReviewCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: tasksGetReviewCountQueryKey(options),
  });

export const tasksListReviewKindsQueryKey = (
  options?: Options<TasksListReviewKindsData>,
) => createQueryKey("tasksListReviewKinds", options);

/**
 * List Review Kinds
 *
 * The registered review kinds and their actions (R-03, R-05).
 */
export const tasksListReviewKindsOptions = (
  options?: Options<TasksListReviewKindsData>,
) =>
  queryOptions<
    TasksListReviewKindsResponse,
    TasksListReviewKindsError,
    TasksListReviewKindsResponse,
    ReturnType<typeof tasksListReviewKindsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await tasksListReviewKinds({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: tasksListReviewKindsQueryKey(options),
  });

export const agentsListRunnersQueryKey = (
  options?: Options<AgentsListRunnersData>,
) => createQueryKey("agentsListRunners", options);

/**
 * List Runners
 *
 * Runners by name, with their status judged from the last heartbeat (online after a
 * beat in the last 45 s, offline after that, never_seen before the first register).
 */
export const agentsListRunnersOptions = (
  options?: Options<AgentsListRunnersData>,
) =>
  queryOptions<
    AgentsListRunnersResponse,
    AgentsListRunnersError,
    AgentsListRunnersResponse,
    ReturnType<typeof agentsListRunnersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await agentsListRunners({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: agentsListRunnersQueryKey(options),
  });

export const agentsListRunnersInfiniteQueryKey = (
  options?: Options<AgentsListRunnersData>,
): QueryKey<Options<AgentsListRunnersData>> =>
  createQueryKey("agentsListRunners", options, true);

/**
 * List Runners
 *
 * Runners by name, with their status judged from the last heartbeat (online after a
 * beat in the last 45 s, offline after that, never_seen before the first register).
 */
export const agentsListRunnersInfiniteOptions = (
  options?: Options<AgentsListRunnersData>,
) => {
  const opts = infiniteQueryOptions<
    AgentsListRunnersResponse,
    AgentsListRunnersError,
    InfiniteData<AgentsListRunnersResponse>,
    QueryKey<Options<AgentsListRunnersData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<AgentsListRunnersData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<AgentsListRunnersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await agentsListRunners({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: agentsListRunnersInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Create Runner
 *
 * A runner and its device token, shown once. 409 `runner_exists`.
 */
export const agentsCreateRunnerMutation = (
  options?: Partial<Options<AgentsCreateRunnerData>>,
): UseMutationOptions<
  AgentsCreateRunnerResponse,
  AgentsCreateRunnerError,
  Options<AgentsCreateRunnerData>
> => {
  const mutationOptions: UseMutationOptions<
    AgentsCreateRunnerResponse,
    AgentsCreateRunnerError,
    Options<AgentsCreateRunnerData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await agentsCreateRunner({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Rotate Runner Token
 *
 * A new device token, shown once; the old one stops and the runner's socket closes.
 */
export const agentsRotateRunnerTokenMutation = (
  options?: Partial<Options<AgentsRotateRunnerTokenData>>,
): UseMutationOptions<
  AgentsRotateRunnerTokenResponse,
  AgentsRotateRunnerTokenError,
  Options<AgentsRotateRunnerTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    AgentsRotateRunnerTokenResponse,
    AgentsRotateRunnerTokenError,
    Options<AgentsRotateRunnerTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await agentsRotateRunnerToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const settingsListModulesQueryKey = (
  options?: Options<SettingsListModulesData>,
) => createQueryKey("settingsListModules", options);

/**
 * List Modules
 *
 * Every module, whether it is on for this workspace, and whether it can be off.
 */
export const settingsListModulesOptions = (
  options?: Options<SettingsListModulesData>,
) =>
  queryOptions<
    SettingsListModulesResponse,
    SettingsListModulesError,
    SettingsListModulesResponse,
    ReturnType<typeof settingsListModulesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await settingsListModules({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: settingsListModulesQueryKey(options),
  });

/**
 * Set Module
 *
 * Switches the module on or off for this workspace. 422 `module_required`.
 */
export const settingsSetModuleMutation = (
  options?: Partial<Options<SettingsSetModuleData>>,
): UseMutationOptions<
  SettingsSetModuleResponse,
  SettingsSetModuleError,
  Options<SettingsSetModuleData>
> => {
  const mutationOptions: UseMutationOptions<
    SettingsSetModuleResponse,
    SettingsSetModuleError,
    Options<SettingsSetModuleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await settingsSetModule({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const settingsGetWorkspaceSettingsQueryKey = (
  options?: Options<SettingsGetWorkspaceSettingsData>,
) => createQueryKey("settingsGetWorkspaceSettings", options);

/**
 * Get Workspace Settings
 */
export const settingsGetWorkspaceSettingsOptions = (
  options?: Options<SettingsGetWorkspaceSettingsData>,
) =>
  queryOptions<
    SettingsGetWorkspaceSettingsResponse,
    SettingsGetWorkspaceSettingsError,
    SettingsGetWorkspaceSettingsResponse,
    ReturnType<typeof settingsGetWorkspaceSettingsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await settingsGetWorkspaceSettings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: settingsGetWorkspaceSettingsQueryKey(options),
  });

/**
 * Put Workspace Settings
 */
export const settingsPutWorkspaceSettingsMutation = (
  options?: Partial<Options<SettingsPutWorkspaceSettingsData>>,
): UseMutationOptions<
  SettingsPutWorkspaceSettingsResponse,
  SettingsPutWorkspaceSettingsError,
  Options<SettingsPutWorkspaceSettingsData>
> => {
  const mutationOptions: UseMutationOptions<
    SettingsPutWorkspaceSettingsResponse,
    SettingsPutWorkspaceSettingsError,
    Options<SettingsPutWorkspaceSettingsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await settingsPutWorkspaceSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const settingsGetSectionQueryKey = (
  options: Options<SettingsGetSectionData>,
) => createQueryKey("settingsGetSection", options);

/**
 * Get Section
 *
 * The section's values without its secrets; 404 `not_found` for an unknown section.
 */
export const settingsGetSectionOptions = (
  options: Options<SettingsGetSectionData>,
) =>
  queryOptions<
    SettingsGetSectionResponse,
    SettingsGetSectionError,
    SettingsGetSectionResponse,
    ReturnType<typeof settingsGetSectionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await settingsGetSection({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: settingsGetSectionQueryKey(options),
  });

/**
 * Put Section
 *
 * Merges `values` into the section at `version`; 409 `stale_version`, 422
 * `validation_error`, 404 `not_found`.
 */
export const settingsPutSectionMutation = (
  options?: Partial<Options<SettingsPutSectionData>>,
): UseMutationOptions<
  SettingsPutSectionResponse,
  SettingsPutSectionError,
  Options<SettingsPutSectionData>
> => {
  const mutationOptions: UseMutationOptions<
    SettingsPutSectionResponse,
    SettingsPutSectionError,
    Options<SettingsPutSectionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await settingsPutSection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Setup
 *
 * First run: creates the workspace and its owner and shows the TOTP secret once.
 * 409 `already_set_up`; 403 `signup_disabled` in hosted mode.
 */
export const authSetupMutation = (
  options?: Partial<Options<AuthSetupData>>,
): UseMutationOptions<
  AuthSetupResponse,
  AuthSetupError,
  Options<AuthSetupData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthSetupResponse,
    AuthSetupError,
    Options<AuthSetupData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authSetup({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Setup Totp
 *
 * Confirms the first code; completes setup and signs the owner in.
 */
export const authSetupTotpMutation = (
  options?: Partial<Options<AuthSetupTotpData>>,
): UseMutationOptions<
  AuthSetupTotpResponse,
  AuthSetupTotpError,
  Options<AuthSetupTotpData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthSetupTotpResponse,
    AuthSetupTotpError,
    Options<AuthSetupTotpData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authSetupTotp({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const tasksListTasksQueryKey = (options?: Options<TasksListTasksData>) =>
  createQueryKey("tasksListTasks", options);

/**
 * List Tasks
 *
 * Tasks, optionally of one project and one status, and how many match (`total`).
 * `order=created` (default) is creation order; `order=today` is the Today order
 * (priority, then due date, then created time; P0-23).
 */
export const tasksListTasksOptions = (options?: Options<TasksListTasksData>) =>
  queryOptions<
    TasksListTasksResponse,
    TasksListTasksError,
    TasksListTasksResponse,
    ReturnType<typeof tasksListTasksQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await tasksListTasks({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: tasksListTasksQueryKey(options),
  });

export const tasksListTasksInfiniteQueryKey = (
  options?: Options<TasksListTasksData>,
): QueryKey<Options<TasksListTasksData>> =>
  createQueryKey("tasksListTasks", options, true);

/**
 * List Tasks
 *
 * Tasks, optionally of one project and one status, and how many match (`total`).
 * `order=created` (default) is creation order; `order=today` is the Today order
 * (priority, then due date, then created time; P0-23).
 */
export const tasksListTasksInfiniteOptions = (
  options?: Options<TasksListTasksData>,
) => {
  const opts = infiniteQueryOptions<
    TasksListTasksResponse,
    TasksListTasksError,
    InfiniteData<TasksListTasksResponse>,
    QueryKey<Options<TasksListTasksData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<TasksListTasksData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<TasksListTasksData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await tasksListTasks({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: tasksListTasksInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Create Task
 */
export const tasksCreateTaskMutation = (
  options?: Partial<Options<TasksCreateTaskData>>,
): UseMutationOptions<
  TasksCreateTaskResponse,
  TasksCreateTaskError,
  Options<TasksCreateTaskData>
> => {
  const mutationOptions: UseMutationOptions<
    TasksCreateTaskResponse,
    TasksCreateTaskError,
    Options<TasksCreateTaskData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await tasksCreateTask({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const tasksGetTaskQueryKey = (options: Options<TasksGetTaskData>) =>
  createQueryKey("tasksGetTask", options);

/**
 * Get Task
 */
export const tasksGetTaskOptions = (options: Options<TasksGetTaskData>) =>
  queryOptions<
    TasksGetTaskResponse,
    TasksGetTaskError,
    TasksGetTaskResponse,
    ReturnType<typeof tasksGetTaskQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await tasksGetTask({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: tasksGetTaskQueryKey(options),
  });

/**
 * Update Task
 */
export const tasksUpdateTaskMutation = (
  options?: Partial<Options<TasksUpdateTaskData>>,
): UseMutationOptions<
  TasksUpdateTaskResponse,
  TasksUpdateTaskError,
  Options<TasksUpdateTaskData>
> => {
  const mutationOptions: UseMutationOptions<
    TasksUpdateTaskResponse,
    TasksUpdateTaskError,
    Options<TasksUpdateTaskData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await tasksUpdateTask({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Add Comment
 */
export const tasksAddCommentMutation = (
  options?: Partial<Options<TasksAddCommentData>>,
): UseMutationOptions<
  TasksAddCommentResponse,
  TasksAddCommentError,
  Options<TasksAddCommentData>
> => {
  const mutationOptions: UseMutationOptions<
    TasksAddCommentResponse,
    TasksAddCommentError,
    Options<TasksAddCommentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await tasksAddComment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Link Context Item
 *
 * Links outside content by ContextItem id (FR-14.2); linking again keeps one link.
 */
export const tasksLinkContextItemMutation = (
  options?: Partial<Options<TasksLinkContextItemData>>,
): UseMutationOptions<
  TasksLinkContextItemResponse,
  TasksLinkContextItemError,
  Options<TasksLinkContextItemData>
> => {
  const mutationOptions: UseMutationOptions<
    TasksLinkContextItemResponse,
    TasksLinkContextItemError,
    Options<TasksLinkContextItemData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await tasksLinkContextItem({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Move Task
 *
 * One board drag: column, rank and version in one request (R-20).
 */
export const tasksMoveTaskMutation = (
  options?: Partial<Options<TasksMoveTaskData>>,
): UseMutationOptions<
  TasksMoveTaskResponse,
  TasksMoveTaskError,
  Options<TasksMoveTaskData>
> => {
  const mutationOptions: UseMutationOptions<
    TasksMoveTaskResponse,
    TasksMoveTaskError,
    Options<TasksMoveTaskData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await tasksMoveTask({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Change Status
 *
 * Moves the task through the state machine (FR-3.2).
 */
export const tasksChangeStatusMutation = (
  options?: Partial<Options<TasksChangeStatusData>>,
): UseMutationOptions<
  TasksChangeStatusResponse,
  TasksChangeStatusError,
  Options<TasksChangeStatusData>
> => {
  const mutationOptions: UseMutationOptions<
    TasksChangeStatusResponse,
    TasksChangeStatusError,
    Options<TasksChangeStatusData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await tasksChangeStatus({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usageGetUsageQueryKey = (options: Options<UsageGetUsageData>) =>
  createQueryKey("usageGetUsage", options);

/**
 * Get Usage
 */
export const usageGetUsageOptions = (options: Options<UsageGetUsageData>) =>
  queryOptions<
    UsageGetUsageResponse,
    UsageGetUsageError,
    UsageGetUsageResponse,
    ReturnType<typeof usageGetUsageQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usageGetUsage({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usageGetUsageQueryKey(options),
  });
